snowflakedb/snowflake-jdbc

src/main/java/net/snowflake/client/core/HttpUtil.java, src/main/java/net/snowflake/client/core/Incident.java, src/main/java/net/snowflake/client/core/SFSession.java, src/main/java/net/snowflake/client/core/SFStatement.java, src/main/java/net/snowflake/client/core/SessionUtil.java, src/main/java/net/snowflake/client/core/StmtUtil.java, src/main/java/net/snowflake/client/jdbc/RestRequest.java, src/main/java/net/snowflake/client/jdbc/SnowflakeChunkDownloader.java
This is a different fix for #13
=> Use closeable httpclient for better handling of resource cleanup

src/main/java/net/snowflake/client/jdbc/SnowflakeType.java
NULL and empty string are now converted to NULL and empty string, respectively
=> SNOW-45545: fixed data to CSV converter for Loader API.

src/main/java/net/snowflake/client/core/QueryExecDTO.java, src/main/java/net/snowflake/client/core/SFSession.java, src/main/java/net/snowflake/client/core/SFStatement.java, src/main/java/net/snowflake/client/core/SessionUtil.java, src/main/java/net/snowflake/client/core/StmtUtil.java, src/main/java/net/snowflake/client/core/bind/BindException.java, src/main/java/net/snowflake/client/core/bind/BindUploader.java, src/main/java/net/snowflake/client/jdbc/SnowflakePreparedStatementV1.java
=> SNOW-45631: Add support to GS and JDBC for bulk array binds uploaded to stage

pom.xml, src/main/java/net/snowflake/client/core/HttpUtil.java, src/main/java/net/snowflake/client/core/SFFixedViewResultSet.java, src/main/java/net/snowflake/client/core/SFTrustManager.java, src/main/java/net/snowflake/client/jdbc/RestRequest.java, src/main/java/net/snowflake/client/jdbc/SnowflakeDatabaseMetaData.java, src/main/java/net/snowflake/client/jdbc/SnowflakeDatabaseMetaDataResultSet.java, src/main/java/net/snowflake/client/jdbc/SnowflakePreparedStatementV1.java, src/main/java/net/snowflake/client/jdbc/SnowflakeStatementV1.java, src/main/java/net/snowflake/client/jdbc/SnowflakeUtil.java, src/main/java/net/snowflake/client/util/DecorrelatedJitterBackoff.java, src/test/java/net/snowflake/client/jdbc/StatementIT.java
This is the branch for JDBC 3.6.23.
=> Prep 3.6.23

CHANGELOG.rst, README.rst, pom.xml, src/main/java/net/snowflake/client/core/EventUtil.java, src/main/java/net/snowflake/client/core/FileCacheManager.java, src/main/java/net/snowflake/client/core/HttpUtil.java, src/main/java/net/snowflake/client/core/SFSession.java, src/main/java/net/snowflake/client/core/SessionUtil.java, src/main/java/net/snowflake/client/jdbc/SnowflakeConnectionV1.java, src/main/java/net/snowflake/client/jdbc/SnowflakeDatabaseMetaData.java, src/main/java/net/snowflake/client/jdbc/SnowflakeDriver.java, src/main/java/net/snowflake/client/loader/LoadingError.java, src/main/java/net/snowflake/client/log/JDK14Logger.java
@ankit-bhatnagar167 This is for JDBC 3.6.24
=> Prep 3.6.24

CHANGELOG.rst, pom.xml, src/main/java/net/snowflake/client/core/SFBaseResultSet.java, src/main/java/net/snowflake/client/jdbc/RestRequest.java, src/main/java/net/snowflake/client/jdbc/SnowflakeBaseResultSet.java, src/main/java/net/snowflake/client/jdbc/SnowflakeChunkDownloader.java, src/main/java/net/snowflake/client/jdbc/SnowflakeDatabaseMetaData.java, src/main/java/net/snowflake/client/jdbc/SnowflakePreparedStatementV1.java, src/main/java/net/snowflake/client/jdbc/SnowflakeResultChunk.java, src/main/java/net/snowflake/client/jdbc/SnowflakeResultSetV1.java, src/main/java/net/snowflake/client/jdbc/telemetryOOB/TelemetryService.java, src/test/java/net/snowflake/client/.gitignore, src/test/java/net/snowflake/client/jdbc/.gitignore, src/test/java/net/snowflake/client/jdbc/BindingDataIT.java, src/test/java/net/snowflake/client/jdbc/ConnectionIT.java, src/test/java/net/snowflake/client/jdbc/PrepareMultiStmtIT.java, src/test/java/net/snowflake/client/jdbc/PreparedStatementIT.java, src/test/java/net/snowflake/client/jdbc/telemetryOOB/TelemetryServiceIT.java
This is the branch for upcoming release.
=> Prep 3.7.0

src/test/java/net/snowflake/client/jdbc/ConnectionIT.java
@ankit-bhatnagar167 This is a hot patch. See SNOW-83424 for more detail.
=> SNOW-83424: Disabled testInvalidDbOrSchemaOrRole temporarily

pom.xml
Add netty reflection jvm options
=> Add netty jvm options

CHANGELOG.rst, FIPS/pom.xml, pom.xml, src/main/java/net/snowflake/client/core/SFSession.java, src/main/java/net/snowflake/client/core/SFSessionProperty.java, src/main/java/net/snowflake/client/jdbc/SFAsyncResultSet.java, src/main/java/net/snowflake/client/jdbc/SnowflakeDatabaseMetaData.java, src/main/java/net/snowflake/client/jdbc/SnowflakeDatabaseMetaDataResultSet.java, src/main/java/net/snowflake/client/jdbc/telemetry/TelemetryClient.java, src/main/java/net/snowflake/client/util/SecretDetector.java, src/test/java/net/snowflake/client/jdbc/ConnectionIT.java, src/test/java/net/snowflake/client/jdbc/DatabaseMetaDataIT.java, src/test/java/net/snowflake/client/util/SecretDetectorTest.java
=> Sync with mono repo

ci/container/upload_artifact.sh
This makes failure in RT-Language setup.
=> Remove preceding space

ci/container/wss.sh
trigger the build to pilot whitesource jira automation workflow
=> add new space line

pom.xml
Checks have passed and 4/4 precommits passed
=> SNOW-169191 updated lang from 3.7 to 3.10

pom.xml
@sfc-gh-mknister , looks like https://github.com/snowflakedb/snowflake-jdbc/commit/869cde8e reverted the change.
=> Fixed snowflake-common version

CHANGELOG.rst, FIPS/pom.xml, pom.xml
=> SNOW-174301: Bumped up the Client PATCH version from 3.12.8 to 3.12.9

ci/container/download_artifact.sh
This changes refers to `latest_commit` file to determine the target JDBC driver for test.
=> SNOW-166172 Use latest commit for target JDBC driver.

README.rst, src/main/java/net/snowflake/client/core/SFJsonResultSet.java, src/main/java/net/snowflake/client/core/SessionUtil.java, src/main/java/net/snowflake/client/core/TimestampNTZ.java, src/main/java/net/snowflake/client/core/arrow/ArrowResultUtil.java, src/main/java/net/snowflake/client/jdbc/SnowflakeTimestampNTZAsUTC.java, src/test/java/net/snowflake/client/jdbc/BaseJDBCTest.java, src/test/java/net/snowflake/client/jdbc/CallableStatementIT.java, src/test/java/net/snowflake/client/jdbc/ResultSetArrowForce0MultiTimeZone.java, src/test/java/net/snowflake/client/jdbc/ResultSetArrowForceLTZMultiTimeZoneIT.java, src/test/java/net/snowflake/client/jdbc/ResultSetArrowForceTZMultiTimeZoneIT.java, src/test/java/net/snowflake/client/jdbc/ResultSetJsonVsArrowIT.java, src/test/java/net/snowflake/client/jdbc/ResultSetJsonVsArrowMultiTZIT.java, src/test/java/net/snowflake/client/jdbc/ResultSetMultiTimeZoneIT.java, src/test/java/net/snowflake/client/jdbc/SnowflakeTimestampNTZAsUTCTest.java
@sfc-gh-mknister , in order to format TIMESTAMP_NTZ value in UTC mode, looks like we just need to introduce a new class. What do you think?
=> SNOW-136193 use SnowflakeTimestampNTZAsUTC to format timestamp in UTC

src/main/java/net/snowflake/client/util/SecretDetector.java, src/test/java/net/snowflake/client/util/SecretDetectorTest.java
Wufan thinks adding a space to filterPassword will fix issue.
=> SNOW-180274 adding space to filterPassword replacement

src/main/java/net/snowflake/client/jdbc/SnowflakeDatabaseMetaData.java, src/main/java/net/snowflake/client/jdbc/SnowflakeDatabaseMetaDataResultSet.java, src/main/java/net/snowflake/client/jdbc/telemetry/TelemetryField.java, src/test/java/net/snowflake/client/jdbc/ResultSetIT.java
We want to start collecting data on DatabaseMetadata API calls and their corresponding SHOW commands. Please read this Confluence page for more information before reviewing the code:
[https://snowflakecomputing.atlassian.net/wiki/spaces/MK/pages/1168703786/Collecting+Metrics+on+DatabaseMetadata+Get+Functions+JDBC+Driver](https://snowflakecomputing.atlassian.net/wiki/spaces/MK/pages/1168703786/Collecting+Metrics+on+DatabaseMetadata+Get+Functions+JDBC+Driver
)
=> SNOW-182450 Add telemetry to collect metrics on DatabaseMetadata Get functions

CHANGELOG.rst, FIPS/pom.xml, pom.xml
=> SNOW-186402: Bumped up the Client PATCH version from 3.12.10 to 3.12.11

src/main/java/net/snowflake/client/jdbc/SnowflakeFileTransferAgent.java, src/main/java/net/snowflake/client/jdbc/SnowflakeFileTransferConfig.java, src/test/java/net/snowflake/client/jdbc/SnowflakeDriverIT.java
This is the same PR as https://github.com/snowflakedb/snowflake-jdbc/pull/312 . Reposting because previous PR was from forked repo and cannot pass test. Meg has already reviewed this.
=> SNOW-173746 added credential caching for Kafka Connector

src/main/java/net/snowflake/client/core/SFJsonResultSet.java, src/main/java/net/snowflake/client/core/SFResultSetMetaData.java, src/main/java/net/snowflake/client/log/JDK14JCLWrapper.java, src/main/java/net/snowflake/client/log/SLF4JJCLWrapper.java
I removed 2 log lines that were redundant since the following log lines (getInt, getByte) were much more informational.
=> SNOW-180303 remove unnecessary log lines from JDBC

src/test/java/net/snowflake/client/jdbc/SnowflakeDriverIT.java, src/test/java/net/snowflake/client/jdbc/StatementIT.java
GCP issue sounds like it will be resolved by Monday or so. I am OOO 08/31-09/4 so I want to put the PUT tests back in while I'm gone.
=> SNOW-186894 reverting change to ignore all PUT tests until GCP issue is solved

.pre-commit-config.yaml
This satisfies the latest requirements sent out by the Security Team.
=> SNOW-190135 Added config files for secret scanning JDBC

Jenkinsfile, ci/container/upload_artifact.sh
Include Jenkins build and test status to the check list of Github PR. 
For JDBC going forward the status will be updated in PR also the jobs will be here https://ci44.int.snowflakecomputing.com/job/JDBC/job/snowflake-jdbc/view/change-requests/job/PR-334/.  this is for PR
=> Getting status of PR in same job which does build and test

FIPS/pom.xml, pom.xml, src/test/java/net/snowflake/client/core/SFTrustManagerPowerMockIT.java, src/test/java/net/snowflake/client/core/SessionUtilExternalBrowserTest.java, src/test/java/net/snowflake/client/jdbc/SSOConnectionTest.java, src/test/java/net/snowflake/client/jdbc/ServiceNameTest.java
Remove powermock and comment out related tests.
=> SNOW-189396: replace powermock with mockito

src/test/java/net/snowflake/client/jdbc/ResultSetMultiTimeZoneIT.java
I missed 1 test that had negative Time values that ran in Jenkins but not Github Actions :/
=> SNOW-194437 took out negative time values of 1 other test

src/main/java/net/snowflake/client/jdbc/SFAsyncResultSet.java, src/test/java/net/snowflake/client/jdbc/ResultSetAsyncIT.java, src/test/java/net/snowflake/client/jdbc/SnowflakeResultSetSerializableIT.java
Adding code coverage for every get function in SFAsyncResultSet
=> SNOW-201566 Add more testing to SFAsyncResultSetIT

src/test/java/net/snowflake/client/jdbc/ConnectionIT.java, src/test/java/net/snowflake/client/jdbc/ConnectionLatestIT.java
=> SNOW-183946: AsyncQueryOpenAndCloseConnection flaky test

src/main/java/net/snowflake/client/jdbc/SnowflakeChunkDownloader.java, src/test/java/net/snowflake/client/jdbc/ResultSetLatestIT.java
This is the new pr for https://github.com/snowflakedb/snowflake-jdbc/pull/371, because the old one's github action was messed up.
=> SNOW-204185: Resultset will hang when chunkdownloaders failed for some unexpected exceptions

src/test/java/net/snowflake/client/jdbc/SnowflakeDriverIT.java
A step needed to cleanup enable_fix_63095.
=> SNOW-214105 rm enable_fix_63095 used in JDBC tests

CHANGELOG.rst, FIPS/pom.xml, pom.xml
=> SNOW-224325: Bumped up the Client PATCH version from 3.12.14 to 3.12.15

pom.xml
Update commons-codec (contained in commons-lang3) and httpclient versions.
=> SNOW-223232 Update whitesource vulnerabilities

FIPS/pom.xml, pom.xml, src/main/java/net/snowflake/client/core/CredentialManager.java, src/main/java/net/snowflake/client/core/SFLoginInput.java, src/main/java/net/snowflake/client/core/SFLoginOutput.java, src/main/java/net/snowflake/client/core/SFSession.java, src/main/java/net/snowflake/client/core/SFSessionProperty.java, src/main/java/net/snowflake/client/core/SecureStorageAppleManager.java, src/main/java/net/snowflake/client/core/SecureStorageLinuxManager.java, src/main/java/net/snowflake/client/core/SecureStorageManager.java, src/main/java/net/snowflake/client/core/SecureStorageWindowsManager.java, src/main/java/net/snowflake/client/core/SessionUtil.java, src/test/java/net/snowflake/client/RunningNotOnLinux.java, src/test/java/net/snowflake/client/core/SecureStorageManagerTest.java, src/test/java/net/snowflake/client/core/SnowflakeMFACacheTest.java, src/test/java/net/snowflake/client/jdbc/SSOConnectionTest.java
Because the recent modify of master branch, the merged MFA change was erased unexpectedly. This pr squashs all 24 previous mfa commits of https://github.com/snowflakedb/snowflake-jdbc/pull/328 and cherry-pick it into current master branch to make sure we won't pollute master again.
=> SNOW-175899: Cherry-pick MFA token cache commits

CHANGELOG.rst, FIPS/pom.xml, pom.xml
=> SNOW-236835: Bumped up the Client PATCH version from 3.12.15 to 3.12.16

CHANGELOG.rst, FIPS/pom.xml, pom.xml
=> SNOW-258463: Bumped up the Client PATCH version from 3.12.16 to 3.12.17

CHANGELOG.rst, FIPS/pom.xml, pom.xml
=> SNOW-286727: Bumped up the Client MINOR version from 3.12.17 to 3.13.0

src/main/java/net/snowflake/client/jdbc/SnowflakeDatabaseMetaData.java
=> SNOW-297097 Add connection context, session schema, and session database to metadata telemetry message

src/main/java/net/snowflake/client/jdbc/SnowflakeDatabaseMetaData.java, src/test/java/net/snowflake/client/jdbc/DatabaseMetaDataIT.java, src/test/java/net/snowflake/client/jdbc/DatabaseMetaDataInternalLatestIT.java
=> SNOW-297092 Fix metadata schema scoping bug

pom.xml
=> SNOW-259063 Downgrade apache httpclient version to avoid regression

CHANGELOG.rst, FIPS/pom.xml, pom.xml
=> SNOW-329756: Bumped up the Client PATCH version from 3.13.1 to 3.13.2

src/main/java/net/snowflake/client/core/SFBaseSession.java, src/main/java/net/snowflake/client/core/SessionUtil.java, src/main/java/net/snowflake/client/jdbc/cloud/storage/SnowflakeS3Client.java, src/test/java/net/snowflake/client/jdbc/SnowflakeDriverIT.java
Reverts snowflakedb/snowflake-jdbc#475
=> Revert "use s3 regional url when parameter is set"

pom.xml, src/main/java/net/snowflake/client/core/SessionUtil.java, src/main/java/net/snowflake/client/jdbc/DefaultSFConnectionHandler.java
SNOW-330467
Changes:
1. updated Snowflake common version
2. added Snowpark parameter strings
3. Updated apis for Default connection handler for Snowpark to reuse most of the connection functions
=> SNOW-330467 update Snowpark parameters and update Snowflake common

pom.xml
=> SNOW-344455 Update commons-io for whitesource vulnerability

src/test/java/net/snowflake/client/jdbc/SnowflakeDriverIT.java, src/test/java/net/snowflake/client/jdbc/SnowflakeDriverLatestIT.java
SNOW-347230
These tests work on GithubActions but not Jenkins master run.
=> SNOW-347230 Ignoring tests that don't  work with testaccount

src/test/java/net/snowflake/client/RunningOnTestaccount.java
=> SNOW-347230 fixed logic for ignoring testaccounts

pom.xml
=> SNOW-334974 Fix json-smart whitesource vulnerability

CHANGELOG.rst, FIPS/pom.xml, pom.xml
=> SNOW-349156: Bumped up the Client PATCH version from 3.13.2 to 3.13.3

CHANGELOG.rst, FIPS/pom.xml, pom.xml
=> SNOW-360812: Bumped up the Client PATCH version from 3.13.3 to 3.13.4

src/main/java/net/snowflake/client/jdbc/cloud/storage/SnowflakeGCSClient.java, src/test/java/net/snowflake/client/jdbc/SnowflakeDriverLatestIT.java
=> SNOW-364846 Ignore failing test while figuring out why credentials don't work

pom.xml
=> SNOW-364253 Fix json-smart whitesource vulnerability

CHANGELOG.rst, FIPS/pom.xml, pom.xml
=> SNOW-370682: Bumped up the Client PATCH version from 3.13.4 to 3.13.5

Jenkinsfile
=> SNOW-359277 add semgrep merge gate to jdbc

CHANGELOG.rst, FIPS/pom.xml, pom.xml
=> SNOW-394789: Bumped up the Client PATCH version from 3.13.5 to 3.13.6

src/main/java/net/snowflake/client/jdbc/SnowflakeResultSetSerializableV1.java
=> SNOW-403461 Fix exception message

CHANGELOG.rst
SNOW-405617
Description
Remove a changelog item that doesn't correspond to a code change
=> SNOW-405617 Remove a changelog item that doesn't correspond to a code change

CHANGELOG.rst, FIPS/pom.xml, pom.xml
=> SNOW-430662: Bumped up the Client PATCH version from 3.13.6 to 3.13.7

CHANGELOG.rst, FIPS/pom.xml, pom.xml, src/main/java/net/snowflake/client/jdbc/SnowflakeDriver.java
=> Release  3.13.7

src/main/java/net/snowflake/client/jdbc/cloud/storage/StorageObjectSummary.java
SNOW-442579
There is an unknown flakiness with PUT command running against Azure. Please refer to https://snowflakecomputing.atlassian.net/browse/SNOW-344350 for previous investigation. This pr is the first quick step to add a log to verify our speculation.
Fixes #NNNN 
=> SNOW-442579: Add log to verify azure sdk flakiness

src/main/java/net/snowflake/client/jdbc/SnowflakeFileTransferAgent.java, src/main/java/net/snowflake/client/jdbc/cloud/storage/AzureObjectSummariesIterator.java, src/main/java/net/snowflake/client/jdbc/cloud/storage/StorageObjectSummary.java
SNOW-442579
We added a log line previously. But we didn't see it now. This time, we will catch all exceptions to avoid missing anything.
Fixes #NNNN 
=> SNOW-442579: Add more log to verify investigation

FIPS/pom.xml, pom.xml
=> SNOW-443760 fix jsoup whitesource vulnerability

CHANGELOG.rst, FIPS/pom.xml, pom.xml, src/main/java/net/snowflake/client/jdbc/SnowflakeDriver.java
=> Snow 458011 jdbc version bump

CHANGELOG.rst, FIPS/pom.xml, pom.xml, src/main/java/net/snowflake/client/jdbc/SnowflakeDriver.java
* SNOW-458011: Bumped up the Client PATCH version from 3.13.7 to 3.13.8
SNOW-458011
Fixes #NNNN 
=> Snow 458011 jdbc version bump (#573)

src/main/java/net/snowflake/client/jdbc/SnowflakeFileTransferAgent.java
SNOW-452445
Fix a stack trace bug for previous SNOW-452445 pr
Fixes #NNNN 
=> SNOW-452445: exception stack trace bug fix

src/main/java/net/snowflake/client/jdbc/SnowflakeFileTransferAgent.java
SNOW-464372
This pr is part of the https://github.com/snowflakedb/snowflake-jdbc/pull/578 as @sfc-gh-azhan suggested. The target is to refactor the code to make it more easier for adding error handling logic (or more human friendly).
Basically, we replace the usage of iterator apis and the while-true loop with a for-each loop. And extract the loop out to be a function.
Fixes #NNNN 
=> SNOW-464372: Refactor issue related code

src/main/java/net/snowflake/client/core/SFBaseSession.java, src/main/java/net/snowflake/client/jdbc/SnowflakeChunkDownloader.java, src/main/java/net/snowflake/client/jdbc/SnowflakeResultSetSerializableV1.java, src/test/java/net/snowflake/client/jdbc/ResultSetLatestIT.java
=> SNOW-441847 Cancel Prefetch threads to avoid endless ChunkDownloader hanging thread

Jenkinsfile
=> SNOW-474873 Change Jenkins node label

CHANGELOG.rst, FIPS/pom.xml, pom.xml
=> SNOW-500187: Bumped up the Client PATCH version from 3.13.10 to 3.13.11

.github/workflows/whitesource-issue.yml, .github/workflows/whitesource.yml
PRODSEC-1177
The PR is to integrate jira workflow for whitesource with the new jira token only available for public repos. 
Fixes #NNNN 
=> PRODSEC-1177 integrate jira workflow for whitesource

src/main/java/net/snowflake/client/core/SessionUtil.java, src/test/java/net/snowflake/client/jdbc/ConnectionIT.java, src/test/java/net/snowflake/client/jdbc/ConnectionLatestIT.java
SNOW-496117
This pr is to add a client end test for a backend bug fix. Please make sure this please is merged later than the backend fix https://github.com/snowflakedb/snowflake/pull/39749.
Fixes #NNNN 
=> SNOW-496117: Add test for backend bug fix

FIPS/pom.xml
=> BC FIPS update to latest

FIPS/pom.xml
=> SNOW-525623 Update JDBC FIPS dependencies in FIPS pom

CHANGELOG.rst, FIPS/pom.xml, pom.xml
=> SNOW-526740: Bumped up the Client PATCH version from 3.13.12 to 3.13.13

CHANGELOG.rst, FIPS/pom.xml, pom.xml, src/main/java/net/snowflake/client/jdbc/SnowflakeDriver.java
=> SNOW-526740 Version Bump for 3.13.13 

FIPS/public_pom.xml
=> SNOW-532783 Updating BC FIPS version in public POM

CHANGELOG.rst, FIPS/pom.xml, pom.xml, src/main/java/net/snowflake/client/jdbc/SnowflakeDriver.java
=> SNOW-533515: Bumped up the Client PATCH version from 3.13.13 to 3.13.14

src/main/java/net/snowflake/client/jdbc/SnowflakeChunkDownloader.java, src/test/java/net/snowflake/client/jdbc/ResultSetLatestIT.java
SNOW-508017 Fix ChunkDownloader hanging issue
Previously, we messed up chunk download state and waited on a condition that will never be signaled.
After the fix, JDBC will try to allocate memory until it exceeds the max retry. When user tries to consume the chunk that failed to download due to memory limitation, JDBC will ignore the internal memory management and just download the chunk.
To further understand the bug:
in `getNextChunkToConsume`, we first call `startNextDownloaders` to prefetch the chunk that we are trying to consume. If we already reaches the internal memory limit, prefetch will retry `MAX_RETRY` times and return. At this time the `DownloadState` of the chunk is `NOT_STARTED`. Then we call `waitForChunkReady`, which will call 
```
currentChunk
.getDownloadCondition() …
```
=> SNOW-508017 Fix ChunkDownloader hanging issue

CHANGELOG.rst, FIPS/pom.xml, pom.xml
=> SNOW-544031: Bumped up the Client PATCH version from 3.13.14 to 3.13.15

Jenkinsfile
Update jenkinsfile to run Regression tests from main
SNOW-XXXXX
Fixes #NNNN 
=> Update jenkinsfile to run Regression tests from main

.pre-commit-config.yaml, .whitesource, whitesource.config
=> PRODSEC-1454 update wss config

CHANGELOG.rst, FIPS/pom.xml, pom.xml
=> SNOW-559415: Bumped up the Client PATCH version from 3.13.15 to 3.13.16

src/main/java/net/snowflake/client/jdbc/SnowflakeTimestampWithTimezone.java, src/test/java/net/snowflake/client/jdbc/SnowflakeTimestampWithTimezoneTest.java
cherry picked from commit 5f1f8981ca9f0f5321963e6e29f20ddca43c3117
SNOW-348660
Fixes #501 
=> SNOW-348660: Add getters for the timezone in SnowflakeTimestampWithTimezone

CHANGELOG.rst, FIPS/pom.xml, pom.xml
=> SNOW-573633: Bumped up the Client PATCH version from 3.13.16 to 3.13.17

CHANGELOG.rst, FIPS/pom.xml, pom.xml
=> SNOW-582263: Bumped up the Client PATCH version from 3.13.17 to 3.13.18

src/main/java/net/snowflake/client/core/SFBaseSession.java, src/main/java/net/snowflake/client/core/SFSession.java, src/main/java/net/snowflake/client/jdbc/SnowflakeConnectionV1.java, src/test/java/net/snowflake/client/jdbc/MockConnectionTest.java
=> Update isValid function to send a heartbeat call instead of SELECT 1

src/main/java/net/snowflake/client/jdbc/SnowflakePreparedStatementV1.java, src/test/java/net/snowflake/client/jdbc/PreparedStatement1LatestIT.java
=> Add option to set byte[] in SnowflakePreparedStatement.setObject

FIPS/src/test/java/net/snowflake/client/jdbc/ConnectionFipsIT.java, pom.xml
=> Upgrade bouncy castle to 1.70

pom.xml
=> Update json-smart and google-cloud-storage to resolve vulnerabilities

pom.xml
Reverts snowflakedb/snowflake-jdbc#906. Having failures for put/get
=> Revert "Update json-smart and google-cloud-storage to resolve vulnerabilities"

CHANGELOG.rst, FIPS/pom.xml, pom.xml, src/main/java/net/snowflake/client/jdbc/SnowflakeDriver.java
=> SNOW-594850: Bumped up the Client PATCH version from 3.13.18 to 3.13.19

src/test/java/net/snowflake/client/jdbc/DatabaseMetaDataLatestIT.java
=> Fix JDBC master branch 1

FIPS/pom.xml, pom.xml
=> upgrade tika-core to 2.4.0 to resolve vulnerability

FIPS/pom.xml, pom.xml, src/test/java/net/snowflake/client/AbstractDriverIT.java
=> Update google library versions to resolve vulnerability with protobuf-java-3.7.1

src/main/java/net/snowflake/client/core/SFJsonResultSet.java
=> Added fix for failing tests from new timestamp type addition

src/test/java/net/snowflake/client/jdbc/SnowflakeDriverLatestIT.java
=> Fix downscopedcredential issue

src/test/java/net/snowflake/client/jdbc/SnowflakeDriverLatestIT.java
=> Trying to solve issue with new file

src/test/java/net/snowflake/client/jdbc/SnowflakeDriverLatestIT.java
=> Ignore test putgetgcsdownscopedcredential() which fails for no reason

src/main/java/net/snowflake/client/jdbc/SnowflakeChunkDownloader.java, src/test/java/net/snowflake/client/jdbc/ConnectionIT.java
SNOW-615824 Fix JDBC chunk downloader missing data issue
Fixes #NNNN 
=> SNOW-615824 Fix JDBC chunk downloader missing data issue

pom.xml
=> upgrade json-smart to 2.4.8

src/test/java/net/snowflake/client/jdbc/PreparedStatement1LatestIT.java, src/test/java/net/snowflake/client/jdbc/StatementIT.java
=> Add test for new CALL stmt type

src/main/java/net/snowflake/client/core/SFBaseSession.java, src/main/java/net/snowflake/client/core/SFSession.java, src/main/java/net/snowflake/client/core/SFStatement.java, src/main/java/net/snowflake/client/core/StmtUtil.java, src/main/java/net/snowflake/client/jdbc/SnowflakeResultSetSerializableV1.java, src/test/java/net/snowflake/client/jdbc/MockConnectionTest.java
Add query context support
Fixes #NNNN 
=> Add query context support

src/main/java/net/snowflake/client/jdbc/SnowflakeChunkDownloader.java
SNOW-615824 Update prefetch memory max retry number. Without this PR users might see performance regression when downloading chunks.
Design doc: https://docs.google.com/document/d/1BhsLA9WzFhLM3fwA9hDSDFt-vV6Bfb4nCWSY-B_TT3g/edit#heading=h.2j9a9btq5js9 
When we don’t have enough memory to prefetch a chunk, we will retry to see if there is available memory for 10 times with increased retry intervals. The total retry time will be around 2 minutes. It makes no sense to wait for memory to be freed for so long. Not to mention that this is only for prefetching, during which failing is acceptable. If prefetching fails, the consuming logic will download the chunk again.
This retry logic exists in all JDBC versions, but it is not triggered all the time. We have some conditions where we will skip …
=> SNOW-615824 Update prefetch memory max retry number

src/test/java/net/snowflake/client/jdbc/ConnectionIT.java
SNOW-615824 Fix testDataCompletenessInLowMemory  test on jenkins
Fixes #NNNN 
=> SNOW-615824 Fix testDataCompletenessInLowMemory  test on jenkins

CHANGELOG.rst, FIPS/pom.xml, pom.xml, src/main/java/net/snowflake/client/jdbc/SnowflakeDriver.java
=> SNOW-625427: Bumped up the Client PATCH version from 3.13.20 to 3.13.21

CHANGELOG.rst, FIPS/pom.xml, pom.xml, src/main/java/net/snowflake/client/jdbc/SnowflakeDriver.java
=> SNOW-625427: Bumped up the Client PATCH version from 3.13.21 to 3.13.22

FIPS/pom.xml
SNOW-XXXXX
The regular pom.xml was altered to include and relocate Google Guava classes from com/google/common/util/concurrent/** into the final assembly. However, this change was not made to the FIPS pom.xml equivalent, and thus some of the required classes to interact with GCP deployments (for file transfers in particular) are absent and fail to work.
Exception in thread "main" java.lang.NoClassDefFoundError: net/snowflake/client/jdbc/internal/google/common/util/concurrent/FutureCallback
at net.snowflake.client.jdbc.internal.google.cloud.storage.StorageOptions.getUnauthenticatedInstance(StorageOptions.java:163)
at net.snowflake.client.jdbc.cloud.storage.SnowflakeGCSClient.setupGCSClient(SnowflakeGCSClient.java:1083)
at net.snowflake.client.jdbc.cloud.storage.SnowflakeGCSClient.createSnow …
=> Relocate Google Guava classes from com/google/common/util/concurrent/** in FIPS driver

CHANGELOG.rst, FIPS/pom.xml, pom.xml, src/main/java/net/snowflake/client/jdbc/SnowflakeDriver.java
=> SNOW-665300: Bumped up the Client PATCH version from 3.13.22 to 3.13.23

CHANGELOG.rst, FIPS/pom.xml, pom.xml, src/main/java/net/snowflake/client/jdbc/SnowflakeDriver.java
=> SNOW-683722: Bumped up the Client PATCH version from 3.13.23 to 3.13.24

src/main/java/net/snowflake/client/core/SFBaseSession.java, src/test/java/net/snowflake/client/jdbc/MockConnectionTest.java
SNOW-685093 make JDBC compatible with stored proc JDBC
server side change: https://github.com/snowflakedb/snowflake/pull/74768
The changes are:
1. removed getHttpClientConnectionTimeout and getHttpClientSocketTimeout from SFBaseSession.
Fixes #NNNN 
3. Fill out the following pre-review checklist:
4. Please describe how your code solves the related issue.
=> SNOW-685093 make JDBC compatible with stored proc JDBC

pom.xml
SNOW-XXXXX
Fixes #1098
Update dependency to remove CVEs:
CVE-2022-31159
CVE-2020-28491
=> Bump aws-java-sdk-bom from 1.11.394 to 1.12.327

src/main/java/net/snowflake/client/core/SFResultSetMetaData.java, src/main/java/net/snowflake/client/jdbc/SnowflakeDatabaseMetaData.java
SNOW-689165 Handle session == null
Fixes #NNNN 
=> SNOW-689165 Handle Session is Null when returning result type

Jenkinsfile
SNOW-692694
Add a github api request call to snowflakedb/snowflake repo to fetch bptp-built tag which guarantees that a build artifact is created for testing.
Pass in the bptp-built commit hash into LanguageJDBC jobs as svn_revision parameters.
Fixes #NNNN 
=> SNOW-692694 Fix PR gate workflow to use bptp-built tag

CHANGELOG.rst, FIPS/pom.xml, pom.xml, src/main/java/net/snowflake/client/jdbc/SnowflakeDriver.java
=> SNOW-693785: Bumped up the Client PATCH version from 3.13.24 to 3.13.25

.github/repo_meta.yaml
=> Update repo_meta.yaml file to match script template

FIPS/pom.xml, pom.xml
Simba ticket 00411898
Description provided by Snowflake Support:
There are dependencies present in the final artifact we give to customers that are not declared in dependency manifest files and therefore not being scanned by our security tooling. Can we create manifest file for all drivers with dependency used by drivers during build/runtime? If manifest file exist, make sure it has all required dependencies. Please ignore "Product" field in this issue as we need to check all drivers builds.
Fixes #NNNN 
By …
=> Add classpath to manifest file 

FIPS/pom.xml, pom.xml
Reverts snowflakedb/snowflake-jdbc#1206
=> Revert "Add classpath to manifest file "

CHANGELOG.rst, FIPS/pom.xml, pom.xml, src/main/java/net/snowflake/client/jdbc/SnowflakeDriver.java
=> SNOW-707879: Bumped up the Client PATCH version from 3.13.25 to 3.13.26

src/main/java/net/snowflake/client/jdbc/RestRequest.java, src/test/java/net/snowflake/client/jdbc/RestRequestTest.java
=> Fix SNOW-724666: Retry http status code 429

CHANGELOG.rst, FIPS/pom.xml, pom.xml, src/main/java/net/snowflake/client/jdbc/SnowflakeDriver.java
=> SNOW-728260: Bumped up the Client PATCH version from 3.13.26 to 3.13.27

src/main/java/net/snowflake/client/core/QueryContextCache.java, src/main/java/net/snowflake/client/core/SFSession.java, src/main/java/net/snowflake/client/core/SFSessionProperty.java, src/test/java/net/snowflake/client/jdbc/ConnectionLatestIT.java
SNOW-728022: Allow to disable Query Context Cache
- Added a connection parameter
- Added a unit test
- Some other changes related to formatting
- Refactor code for replacing QCC
Fixes #NNNN 
=> SNOW-728022: Allow to disable Query Context Cache

src/main/java/net/snowflake/client/jdbc/RestRequest.java, src/main/java/net/snowflake/client/jdbc/cloud/storage/SnowflakeGCSClient.java, src/test/java/net/snowflake/client/jdbc/RestRequestTest.java
SNOW-705137 Fix retry issue in GCP uploadStream 
Fixes #NNNN 
=> SNOW-705137 Fix retry issue in GCP uploadStream

src/main/java/net/snowflake/client/core/ExecTimeTelemetryData.java, src/main/java/net/snowflake/client/core/SFSession.java, src/main/java/net/snowflake/client/core/SFSessionProperty.java, src/main/java/net/snowflake/client/jdbc/telemetryOOB/TelemetryService.java, src/test/java/net/snowflake/client/jdbc/ConnectionLatestIT.java, src/test/java/net/snowflake/client/jdbc/telemetryOOB/TelemetryServiceIT.java
[SNOW-727954](https://snowflakecomputing.atlassian.net/browse/SNOW-727954)
Fixes #NNNN 
[SNOW-727954]: https://snowflakecomputing.atlassian.net/browse/SNOW-727954?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SNOW-727954 Create HTAP telemetry parameter and separate HTAP telemetry enabling from regular OOB telemetry

.github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
=> Test pr 1245

CHANGELOG.rst, FIPS/pom.xml, pom.xml, src/main/java/net/snowflake/client/jdbc/SnowflakeDriver.java
=> SNOW-748124: Bumped up the Client PATCH version from 3.13.27 to 3.13.28

src/main/java/net/snowflake/client/pooling/LogicalConnection.java, src/test/java/net/snowflake/client/jdbc/BaseJDBCTest.java, src/test/java/net/snowflake/client/jdbc/ConnectionAlreadyClosedIT.java, src/test/java/net/snowflake/client/pooling/ConnectionPoolingDataSourceIT.java, src/test/java/net/snowflake/client/pooling/LogicalConnectionAlreadyClosedLatestIT.java, src/test/java/net/snowflake/client/pooling/LogicalConnectionFeatureNotSupportedLatestIT.java, src/test/java/net/snowflake/client/pooling/LogicalConnectionLatestIT.java
LogicalConnection.java has 0% code coverage. Adding tests to cover this class.
Fixes #NNNN 
=> Add tests for LogicalConnection.java

src/main/java/net/snowflake/client/core/Constants.java, src/main/java/net/snowflake/client/core/EventHandler.java, src/test/java/net/snowflake/client/core/CoreUtilsMiscellaneousTest.java
SNOW-748294
Add unit tests to uncovered code
Fixes #NNNN 
=> SNOW-748294 Add more code coverage to SnowflakeAssert, Constants, and HttpUtil

src/test/java/net/snowflake/client/core/IncidentUtilTest.java, src/test/java/net/snowflake/client/log/AbstractLoggerIT.java, src/test/java/net/snowflake/client/log/JDK14JCLWrapperLatestIT.java, src/test/java/net/snowflake/client/log/JDK14LoggerLatestIT.java, src/test/java/net/snowflake/client/log/JDK14LoggerTest.java, src/test/java/net/snowflake/client/log/SLF4JJJCLWrapperLatestIT.java, src/test/java/net/snowflake/client/log/SLF4JLoggerLatestIT.java
Add tests to IncidentUtil and logger classes
Fixes #NNNN 
=> Add more coverage to logger classes

.github/ISSUE_TEMPLATE/BUG_REPORT.md, .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
=> Change the template as per internal discussion

FIPS/pom.xml, FIPS/public_pom.xml, TestOnly/pom.xml, pom.xml, public_pom.xml
SNOW-349075
Update JNA version in pom.xml.
Fixes #NNNN 
=> SNOW-349075: Update jna version in pom.xml

src/test/java/net/snowflake/client/jdbc/DatabaseMetaDataLatestIT.java
=> SNOW-719614 fixing test

src/test/java/net/snowflake/client/jdbc/SnowflakeAzureClientHandleExceptionLatestIT.java, src/test/java/net/snowflake/client/jdbc/SnowflakeS3ClientHandleExceptionLatestIT.java
=> Add tests for S3 and Azure client exception handling

src/test/java/net/snowflake/client/jdbc/cloud/storage/SnowflakeAzureClientLatestIT.java, src/test/java/net/snowflake/client/jdbc/cloud/storage/SnowflakeAzureClientTest.java
=> Add tests for SnowflakeAzureClient

src/test/java/net/snowflake/client/jdbc/cloud/storage/SnowflakeS3ClientLatestIT.java
=> Add test S3Client with AmazonS3EncryptionClient builder

src/test/java/net/snowflake/client/jdbc/StreamIT.java
=> Run downloadToStream() test on azure and S3 accounts

src/main/java/net/snowflake/client/jdbc/SnowflakeFileTransferAgent.java, src/test/java/net/snowflake/client/jdbc/FileUploaderLatestIT.java
=> Add more tests for SnowflakeFileTransferAgent

CHANGELOG.rst, FIPS/pom.xml, pom.xml, src/main/java/net/snowflake/client/jdbc/SnowflakeDriver.java
=> SNOW-761717: Bumped up the Client PATCH version from 3.13.28 to 3.13.29

src/main/java/net/snowflake/client/core/HttpUtil.java, src/main/java/net/snowflake/client/core/OCSPTelemetryData.java, src/main/java/net/snowflake/client/core/QueryExecDTO.java, src/main/java/net/snowflake/client/core/SFLoginOutput.java, src/main/java/net/snowflake/client/core/SFSession.java, src/test/java/net/snowflake/client/core/CoreUtilsMiscellaneousTest.java, src/test/java/net/snowflake/client/core/IncidentUtilLatestIT.java, src/test/java/net/snowflake/client/core/SessionUtilLatestIT.java
=> SNOW-748294 Adding coverage to SnowflakeMutableProxyRouter, removing unused OCSP telemetry initializer, fixing IT tests so they run

src/test/java/net/snowflake/client/core/QueryExecDTOTest.java, src/test/java/net/snowflake/client/jdbc/DatabaseMetaDataResultSetLatestIT.java, src/test/java/net/snowflake/client/jdbc/DatabaseMetaDataResultsetIT.java, src/test/java/net/snowflake/client/jdbc/StatementLatestIT.java, src/test/java/net/snowflake/client/log/SFLoggerFactoryTest.java
=> Add tests in SnowflakeDatabaseMetaDataResultSet, SFLoggerFactory, QueryExecDTO and SFStatement

src/main/java/net/snowflake/client/jdbc/SnowflakeFileTransferAgent.java, src/main/java/net/snowflake/client/jdbc/SnowflakeFileTransferMetadataV1.java, src/main/java/net/snowflake/client/jdbc/cloud/storage/SnowflakeGCSClient.java, src/test/java/net/snowflake/client/jdbc/SnowflakeDriverLatestIT.java
SNOW-767998 Enhance JDBC API to upload file with downscoped token for Spark Connector
The design is https://docs.google.com/document/d/1MlGUyoFOAYEJx6skw2KZfduKp1EPQIJ2SFdsm3emOJ4/edit#
Fixes #NNNN 
=> SNOW-767998 Enhance JDBC API to upload file with downscoped token for Spark Connector

src/test/java/net/snowflake/client/jdbc/FileUploaderLatestIT.java
=> Add test for S3StorageObjectMetadata.java

src/test/java/net/snowflake/client/core/SecureStorageManagerTest.java
=> SNOW-777279: Fix unit test load native library

src/test/java/net/snowflake/client/core/arrow/DateConverterTest.java
=> [SNOW-777290] Fix failing tests on mac

src/test/java/net/snowflake/client/jdbc/MultiStatementLatestIT.java
SNOW-758262
Added test case on behalf of SQL team for testing anonymous blocks 
Fixes #NNNN 
=> SNOW-758262 Test anonymous blocks in JDBC multistatement

src/test/java/net/snowflake/client/jdbc/ResultSetLatestIT.java
=> Add test for uncovered getObject() for JSON resultset

pom.xml
SNOW-767090
Fixes #1310  
https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/304
=> Upgrade slf4j-api from 1.7.25 to 2.0.6 and logback-classic from 1.2.3 to 1.3.6

.github/workflows/snyk-issue.yml
=> PRODSEC-2566 fix snyk yaml config

ci/container/download_artifact.sh, ci/container/upload_artifact.sh
=> SNOW-735650: sfc-jenkins -> sfc-eng-jenkins s3 bucket change

CHANGELOG.rst, FIPS/pom.xml, pom.xml, src/main/java/net/snowflake/client/jdbc/SnowflakeDriver.java
=> SNOW-795852: Bumped up the Client PATCH version from 3.13.29 to 3.13.30

src/main/java/net/snowflake/client/core/EventUtil.java, src/test/java/net/snowflake/client/core/EventHandlerTest.java, src/test/java/net/snowflake/client/core/EventTest.java
=> Add tests for Event and EventHandler

src/test/java/net/snowflake/client/core/SessionUtilExternalBrowserTest.java
=> Add unit tests for default handler in ExternalBrowser auth

src/main/java/net/snowflake/client/jdbc/SnowflakeResultSetMetaDataV1.java, src/test/java/net/snowflake/client/jdbc/DatabaseMetaDataIT.java, src/test/java/net/snowflake/client/jdbc/ResultSetLatestIT.java
=> [SNOW-800418] ResultSetMetadata.isCaseSensitive implementation

src/test/java/net/snowflake/client/jdbc/ConnectionLatestIT.java, src/test/java/net/snowflake/client/jdbc/SnowflakeDriverIT.java
SNOW-748294
This adds coverage for
- Explicitly specifying SNOWFLAKE_JWT and SNOWFLAKE as authentication methods instead of implying them
- Adding a test for connecting with SNOWFLAKE_OAUTH authentication
Fixes #NNNN 
=> Add code coverage for uncovered authentication types

src/main/java/net/snowflake/client/jdbc/RestRequest.java, src/test/java/net/snowflake/client/jdbc/ResultSetLatestIT.java
SNOW-799391
Sample message:
Fixes #NNNN 
=> [SNOW-799391] Add troubleshoot msg for ssl errors

src/main/java/net/snowflake/client/jdbc/RestRequest.java
SNOW-782431 . Add a log statement at the beginning of the retry loop to log all the outgoing requests. 
Sample log:
```
POST http://snowflake.dev.local:8082/session/v1/login-request?databaseName=ASDF&schemaName=ASDF&warehouse=ASDF&roleName=ASDF&requestId=5615aa83-4da3-46ff-8a1b-53d5e7fdd3ed HTTP/1.1
```
Fixes #NNNN 
=> [SNOW-782431] Include request id log for failed connection

src/main/java/net/snowflake/client/log/SFLogLevel.java, src/main/java/net/snowflake/client/log/SFToJavaLogMapper.java, src/test/java/net/snowflake/client/log/SFLogLevelTest.java, src/test/java/net/snowflake/client/log/SFToJavaLogMapperTest.java
SNOW-804206
This change is part of adding sf client configuration.
PR's in this series:
1. https://github.com/snowflakedb/snowflake-jdbc/pull/1375
Fixes #NNNN 
=> [SNOW-804206] 2. Add Custom snowflake log levels

src/main/java/net/snowflake/client/config/SFClientConfig.java, src/main/java/net/snowflake/client/config/SFClientConfigParser.java, src/main/java/net/snowflake/client/core/SFSession.java, src/main/java/net/snowflake/client/core/SFSessionProperty.java, src/main/java/net/snowflake/client/jdbc/DefaultSFConnectionHandler.java, src/main/java/net/snowflake/client/log/JDK14Logger.java, src/main/java/net/snowflake/client/log/SFToJavaLogMapper.java, src/test/java/net/snowflake/client/log/JDK14LoggerTest.java, src/test/java/net/snowflake/client/log/JDK14LoggerWithClientLatestIT.java, src/test/java/net/snowflake/client/log/SFToJavaLogMapperTest.java
SNOW-804206
The SF CONFIG file introduces various logging possibilities when used in conjunction with the `tracing` connection property and `logging.properties` for JDK14Logger. Please note that the SF CONFIG file is only applicable to `JDK14Logger` as `SL4JLogger` cannot be instantiated.
If  `-Djava.util.logging.config.file `system property is not defined, the following actions will be taken:
| Property  | Actions                                                                                                                                                                                                                                   |
|-----------|-------------------------------------------------------------------------------------------------------------------------------------------- …
=> [SNOW-804206] 3. Instantiate JDK14Logger with sf client configuration 

src/main/java/net/snowflake/client/config/SFClientConfigParser.java, src/test/java/net/snowflake/client/config/SFClientConfigParserTest.java
SNOW-804206 
Context: As part of easy logging configuration, we have introduced a new config file where users can configure log level and log path. This PR fixes build issues introduced by earlier PR: https://github.com/snowflakedb/snowflake-jdbc/pull/1384 in windows os. 
```
Exception in thread "main" java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/git/snowflake-jdbc/target/classes/sf_config.json
at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229)
at …
```
=> [SNOW-804206]Fix ConfigFile parser issues in Windows

CHANGELOG.rst, FIPS/pom.xml, pom.xml, src/main/java/net/snowflake/client/jdbc/SnowflakeDriver.java
=> SNOW-824364_jdbc_version_bump

CHANGELOG.rst, FIPS/pom.xml, pom.xml, src/main/java/net/snowflake/client/jdbc/SnowflakeDriver.java
=> SNOW-828031: Bumped up the Client PATCH version from 3.13.31 to 3.13.32

src/test/java/net/snowflake/client/jdbc/SnowflakeDriverLatestIT.java
SNOW-834606
Updated the IntegrationTest system call logic in [GS](https://github.com/snowflakedb/snowflake/commit/ca90fbe54c5a56df4ff63aa781975b1f1cd402f4), updating the JDBC test here.
Fixes #NNNN 
Add new argument to the system call
=> SNOW-834606 update test

src/main/java/net/snowflake/client/jdbc/SnowflakeConnectString.java, src/main/java/net/snowflake/client/jdbc/SnowflakeDriver.java, src/test/java/net/snowflake/client/jdbc/SnowflakeDriverTest.java
=> Test pr 1393

CHANGELOG.rst, FIPS/pom.xml, pom.xml, src/main/java/net/snowflake/client/jdbc/SnowflakeDriver.java
=> SNOW-837490_jdbc_version_bump

README.rst
PR to update the read me to use the new Spotify's fmt maven plugin instead of coveo fmt plugin.
Fixes #NNNN 
=> [ReadMe]Update linter command

.github/workflows/snyk-issue.yml, .github/workflows/snyk-pr.yml
PRODSEC-2858
SNOW-838885
Fixes #NNNN 
=> PRODSEC-2858 fix GHA issue

linkage-checker-exclusion-rules.xml, pom.xml
SNOW-835679
Upgrade bouncy castle from bcprov-jdk16on 1.70 to bcprov-jdk18on 1.74.
https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/455
=> SNOW-835679: Upgrade bouncy castle to bcprov-jdk18on 1.74

src/main/java/net/snowflake/client/jdbc/SnowflakeChunkDownloader.java
Fixes https://github.com/snowflakedb/snowflake-jdbc/issues/1455
By adding more information to logs, users are more easily able to get connected to their Snowflake instance.
=> Log scrubbed URL for chunk download timeout

pom.xml
Reverts snowflakedb/snowflake-jdbc#1465
=> Revert SFL4J fix for Arrow best practices

README.rst
Added codecov badge.
SNOW-780822: Changed JDBC for storing codecov uploader and checksum files. Changed jenkin job to upload code coverage to codecov. Now changed README file to display codecov badge.
Fixes #NNNN 
=> Update README.rst add codecov badge

src/main/java/net/snowflake/client/core/SFBaseSession.java, src/main/java/net/snowflake/client/jdbc/ChunkDownloadContext.java, src/main/java/net/snowflake/client/jdbc/DefaultResultStreamProvider.java, src/main/java/net/snowflake/client/jdbc/SnowflakeChunkDownloader.java, src/main/java/net/snowflake/client/jdbc/SnowflakeResultSetSerializableV1.java, src/test/java/net/snowflake/client/jdbc/ChunkDownloaderS3RetryUrlLatestIT.java, src/test/java/net/snowflake/client/jdbc/MockConnectionTest.java, src/test/java/net/snowflake/client/jdbc/SnowflakeChunkDownloaderLatestIT.java
SNOW-872499
The driver doesn't implement httpMaxRetries in DefaultResultStreamProvider.getResultChunk(). It passes 0 for maxRetries which indicates no maximum and gets stuck in an infinite loop.
There is also an outer retry within the SnowflakeChunkDownloader.waitForChunkReady() that has a constant max retry value of 10. This outer retry is not hit because of the inner loop within RestRequest.execute().
If we make the maxRetries configurable in DefaultResultStreamProvider.getResultChunk() instead of passing in 0, we still won't get the expected number of retries. For example, if maxHttpRetries = 5, then we would see the internal retry happen 5 times and the outer retry happen 10 times, resulting in 50 retries altogether.
The proposed change:
- Disable retry in …
=> SNOW-872499: use maxHttpRetries on chunk downloader requests to prevent infinite retries

CHANGELOG.rst, FIPS/pom.xml, pom.xml, src/main/java/net/snowflake/client/jdbc/SnowflakeDriver.java
=> SNOW-875421: Bumped up the Client MINOR version from 3.13.33 to 3.14.0

src/main/java/net/snowflake/client/jdbc/SnowflakeChunkDownloader.java
SNOW-872499
To keep consistency on httpMaxRetries, disable max retries in chunk downloading if httpMaxRetries is 0.
Fixes #NNNN 
=> SNOW-872499: Disable max retries in chunk downloader if maxHttpRetries is 0

CHANGELOG.rst, FIPS/pom.xml, pom.xml, src/main/java/net/snowflake/client/jdbc/SnowflakeDriver.java
=> SNOW-896908: Bumped up the Client PATCH version from 3.14.0 to 3.14.1

src/test/java/net/snowflake/client/jdbc/ConnectionIT.java, src/test/java/net/snowflake/client/jdbc/ConnectionLatestIT.java
SNOW-924760
Fixes https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/672
Added the error code 390400 for the test `testHttpsLoginTimeoutWithOutSSL` to pass due to server change.
=> SNOW-924760: add error code 390400 to testHttpsLoginTimeoutWithOutSSL

CHANGELOG.rst, FIPS/pom.xml, pom.xml, src/main/java/net/snowflake/client/jdbc/SnowflakeDriver.java
=> SNOW-921835: Bumped up the Client PATCH version from 3.14.1 to 3.14.2

src/main/java/net/snowflake/client/core/SFBaseSession.java, src/main/java/net/snowflake/client/core/SFSession.java
SNOW-887071 Rename the method.
Fixes #NNNN 
=> SNOW-887071 : Rename method to setEnablePutGet from putEnablePutGet

src/test/java/net/snowflake/client/core/SFTrustManagerIT.java, src/test/java/net/snowflake/client/jdbc/FileUploaderPrepIT.java
=>  [SNOW-892541] Remove references to sfcdev1

src/test/java/net/snowflake/client/core/CoreUtilsMiscellaneousTest.java, src/test/java/net/snowflake/client/core/SessionUtilLatestIT.java, src/test/java/net/snowflake/client/jdbc/SnowflakeDriverLatestIT.java
SNOW-931788
https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/686
Add tests to increase coverage in SessionUtil(55.01%), SnowflakeDriver(73.12%) and HttpClientSettingsKey(78.18%).
Fixes [#686](https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/686)
=> SNOW-931788: Increase code coverage with CodeCov

FIPS/pom.xml
SNOW-848780
https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/495
Upgrade org.bouncycastle:bc-fips from 1.0.2.1 to 1.0.2.4
Fixes #1435
=> SNOW-848780: Upgrade org.bouncycastle:bc-fips to 1.0.2.4

FIPS/pom.xml, src/main/java/net/snowflake/client/jdbc/DefaultSFConnectionHandler.java, src/main/java/net/snowflake/client/jdbc/SnowflakeDriver.java, src/main/java/net/snowflake/client/jdbc/cloud/storage/SnowflakeGCSClient.java
Fixes: SNOW-943964
Fixes #NNNN 
=> [SNOW-943964] Fix GCP downscope token issue

src/main/java/net/snowflake/client/core/SessionUtil.java, src/main/java/net/snowflake/client/jdbc/DefaultSFConnectionHandler.java, src/main/java/net/snowflake/client/jdbc/SnowflakeDriver.java
Adds jar name with version to the client env. Sample output in the backend:
```
"clientEnvironment": "{\"schema\":\"PUBLIC\",\"tracing\":\"all\",\"role\":\"accountadmin\",\"OS\":\"Mac OS X\",\"OCSP_MODE\":\"FAIL_OPEN\",\"JAVA_VM\":\"OpenJDK 64-Bit Server VM\",\"APPLICATION\":\"\",\"warehouse\":\"rrj_wh\",\"database\":\"\",\"\":\"****\",\"JDBC_JAR_NAME\":\"snowflake-jdbc-fips-3.13.34\",\"OS_VERSION\":\"10.16\",\"serverURL\":\"[/](/)\",\"JAVA_VERSION\":\"11.0.11\",\"user\":\"\",\"account\":\"\",\"JAVA_RUNTIME\":\"OpenJDK Runtime Environment\"}"
```
Fixes #NNNN 
3. …
=> Add JDBC_JAR_NAME to client environment

FIPS/pom.xml, pom.xml
SNOW-924672
https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/671
Fixes [#671](https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/671)
Upgraded the following dependencies:
- aws-java-sdk 1.12.501 (to match the version in FIPS/pom.xml)
- jackson 2.15.3
- jackson-databind 2.15.3
- netty-buffer/netty-common 4.1.100.Final
- grpc related dependencies 1.59.0
=> SNOW-924672: Upgrade aws-java-sdk, grpc, jackson, netty

CHANGELOG.rst, FIPS/pom.xml, pom.xml, src/main/java/net/snowflake/client/jdbc/SnowflakeDriver.java
=> Bumped up the Client PATCH version from 3.14.2 to 3.14.3

src/main/java/net/snowflake/client/config/SFClientConfigParser.java, src/test/java/net/snowflake/client/config/SFClientConfigParserTest.java
SNOW-969200
Removed the temp directory search for client config file.
Fixes #NNNN 
=> SNOW-969200: Remove to look into temp directory for security reason

codecov.yml
SNOW-931788
https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/686
Fixes [#686](https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/686)
=> SNOW-931788: Add codecov.yml to count partial hit

src/test/java/net/snowflake/client/jdbc/cloud/storage/CloudStorageClientLatestIT.java
SNOW-565154 - test fail fast for not existing file
=> SNOW-565154: Test download stream should fail fast on not existing file

Jenkinsfile
SNOW-937199 - include JDK 11 and 17 in Jenkins jobs.
=> SNOW-937199 Use JDK 11 and 17 in Jenkins

parent-pom.xml
SNOW-946164
https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/710
Fixes #NNNN 
=> SNOW-946164: Upgrade grpc-netty-shaded version to 1.60.0

.github/workflows/cla_bot.yml
SNOW-989861
- sync jobs configuration between drivers, especially add snyk users to allow list for CLA bot
=> SNOW-989861: Update CLA github action

src/test/java/net/snowflake/client/jdbc/ResultSetLatestIT.java
=> SNOW-990009: Fix flaky test ResultSetLatestIT.testMetadataAPIMetricCollection

src/test/java/net/snowflake/client/jdbc/DatabaseMetaDataLatestIT.java
=> SNOW-987150: Fix flaky test DatabaseMetaDataLatestIT.testUseConnectionCtx

src/test/java/net/snowflake/client/jdbc/ConnectionLatestIT.java
=> SNOW-977628: Fix flaky test ConnectionLatestIT.testIsAsyncSession

src/main/java/net/snowflake/client/jdbc/telemetryOOB/TelemetryService.java, src/test/java/net/snowflake/client/jdbc/telemetryOOB/TelemetryServiceIT.java
=> SNOW-1016776 IT test to test against the new K8s app

Jenkinsfile
=> SNOW-1020081: Do not run CodeCoverage jenkins jobs on Pull Request

README.rst
=> SNOW-1020059: Describe driver installation from source

src/test/java/net/snowflake/client/TestUtil.java, src/test/java/net/snowflake/client/jdbc/DatabaseMetaDataIT.java, src/test/java/net/snowflake/client/jdbc/DatabaseMetaDataLatestIT.java, src/test/java/net/snowflake/client/jdbc/StatementLatestIT.java
=> SNOW-1003125: Fix flaky test DatabaseMetaDataIT.testGetSchemas

src/test/java/net/snowflake/client/jdbc/telemetryOOB/TelemetryServiceIT.java
=> SNOW-1022736: Update TelemetryServiceIT.java

FIPS/pom.xml, ci/scripts/check_content.sh, pom.xml
=> SNOW-1003783: Fix multi-release jar entries

src/main/java/net/snowflake/client/core/SnowflakeJdbcInternalApi.java
=> SNOW-1044219: Add marker annotation for internal API

src/main/java/net/snowflake/client/core/HttpUtil.java, src/main/java/net/snowflake/client/core/SFLoginInput.java, src/main/java/net/snowflake/client/core/SFLoginOutput.java, src/main/java/net/snowflake/client/core/SFSession.java, src/main/java/net/snowflake/client/core/SessionUtil.java, src/main/java/net/snowflake/client/core/SessionUtilExternalBrowser.java, src/main/java/net/snowflake/client/jdbc/RestRequest.java, src/main/java/net/snowflake/client/jdbc/cloud/storage/SnowflakeGCSClient.java, src/main/java/net/snowflake/client/jdbc/telemetry/TelemetryClient.java, src/test/java/net/snowflake/client/core/HttpUtilLatestIT.java
=> SNOW-1020043: Configure connection and socket timeout

src/main/java/com/snowflake/client/jdbc/SnowflakeDriver.java
=> SNOW-1050497: Mark com.snowflake.client.jdbc.SnowflakeDriver as deprecated

src/main/java/net/snowflake/client/core/HttpUtil.java, src/main/java/net/snowflake/client/core/SnowflakeMutableProxyRoutePlanner.java, src/main/java/net/snowflake/client/jdbc/SnowflakeResultSetSerializable.java, src/main/java/net/snowflake/client/jdbc/SnowflakeResultSetSerializableV1.java
=> SNOW-1059684: Fix deprecation links

TestOnly/pom.xml, parent-pom.xml, src/main/java/net/snowflake/client/core/QueryStatus.java, src/test/java/net/snowflake/client/jdbc/ConnectionLatestIT.java
=> SNOW-668836: Fix ConnectionLatestIt.testQueryStatusErrorMessageAndErrorCodeChangeOnAsyncQuery

src/main/java/net/snowflake/client/core/HttpClientSettingsKey.java, src/main/java/net/snowflake/client/core/HttpUtil.java, src/main/java/net/snowflake/client/jdbc/RestRequest.java, src/main/java/net/snowflake/client/jdbc/cloud/storage/S3HttpUtil.java, src/main/java/net/snowflake/client/util/Stopwatch.java, src/test/java/net/snowflake/client/util/StopwatchTest.java
=> SNOW-1167978: Logs - Transport

src/main/java/net/snowflake/client/core/SFBaseSession.java
=> SNOW-1167980: Logs - Proxy

src/main/java/net/snowflake/client/core/HttpClientSettingsKey.java, src/main/java/net/snowflake/client/core/HttpUtil.java, src/main/java/net/snowflake/client/core/URLUtil.java, src/main/java/net/snowflake/client/jdbc/RestRequest.java, src/main/java/net/snowflake/client/jdbc/cloud/storage/S3HttpUtil.java, src/main/java/net/snowflake/client/util/Stopwatch.java, src/test/java/net/snowflake/client/util/StopwatchTest.java
=> SNOW-1167981: Logs - Retry

CHANGELOG.rst
Added new link
https://docs.snowflake.com/en/release-notes/clients-drivers/jdbc
SNOW-XXXXX
Fixes #NNNN 
=> SNOW-1168175 Update CHANGELOG.rst

src/main/java/net/snowflake/client/jdbc/SnowflakeBaseResultSet.java, src/test/java/net/snowflake/client/jdbc/ResultSetLatestIT.java
…type)
SNOW-XXXXX
Fixes #NNNN 
=> SNOW-1232333 - add mapping for basic types in method getObject

src/main/java/net/snowflake/client/core/HttpUtil.java, src/main/java/net/snowflake/client/core/SessionUtil.java, src/main/java/net/snowflake/client/jdbc/cloud/storage/S3HttpUtil.java
=> SNOW-1167982: Logs - Authentication

src/main/java/net/snowflake/client/core/SFJsonResultSet.java, src/main/java/net/snowflake/client/core/json/Converters.java, src/main/java/net/snowflake/client/jdbc/SnowflakeBaseResultSet.java, src/main/java/net/snowflake/client/jdbc/SnowflakeUtil.java
=> SNOW-1234214 Fix for json Maps

src/main/java/net/snowflake/client/core/structs/StructureTypeHelper.java
=> SNOW-1234216: Read structured type enabled flag value

src/main/java/net/snowflake/client/config/SFClientConfigParser.java, src/test/java/net/snowflake/client/config/SFClientConfigParserTest.java
=> SNOW-1163212: InvalidPathException on Windows due to Nested file path

parent-pom.xml, thin_public_pom.xml
=> SNOW-1281598: Bump nimbus-jose-jwt

SECURITY.md
=> SNOW-1293828 Update security policy

.github/workflows/build-test.yml
=> SNOW-1304560: Cancel old PR builds on GH

src/main/java/net/snowflake/client/config/SFClientConfig.java, src/main/java/net/snowflake/client/config/SFClientConfigParser.java, src/test/java/net/snowflake/client/config/SFClientConfigParserTest.java
=> SNOW-1167984: Logs - Configuraiton

src/main/java/net/snowflake/client/pooling/LogicalConnection.java, src/main/java/net/snowflake/client/pooling/SnowflakePooledConnection.java
=> SNOW-1167987: Logs - Connection Pool

src/main/java/net/snowflake/client/jdbc/DefaultResultStreamProvider.java, src/main/java/net/snowflake/client/jdbc/SnowflakeChunkDownloader.java, src/main/java/net/snowflake/client/jdbc/SnowflakeResultChunk.java, src/test/java/net/snowflake/client/jdbc/SnowflakeChunkDownloaderLatestIT.java
=> SNOW-1167989: Logs - Result processing

src/main/java/net/snowflake/client/core/ExecTimeTelemetryData.java, src/main/java/net/snowflake/client/jdbc/SnowflakePreparedStatementV1.java, src/main/java/net/snowflake/client/jdbc/SnowflakeStatementV1.java, src/main/java/net/snowflake/client/util/TimeMeasurement.java
=> SNOW-1167988: Logs - Statement/query

src/main/java/net/snowflake/client/core/SFTrustManager.java
=> SNOW-1167993: Logs - OCSP

src/main/java/net/snowflake/client/core/FileCacheManager.java, src/main/java/net/snowflake/client/core/FileUtil.java, src/main/java/net/snowflake/client/core/SessionUtilKeyPair.java, src/main/java/net/snowflake/client/jdbc/FileBackedOutputStream.java, src/main/java/net/snowflake/client/jdbc/SnowflakeFileTransferAgent.java, src/main/java/net/snowflake/client/jdbc/cloud/storage/StorageClientFactory.java
=> SNOW-1167990: Logs - Filesystem operations

src/main/java/net/snowflake/client/core/HttpUtil.java, src/main/java/net/snowflake/client/core/SFSession.java, src/main/java/net/snowflake/client/core/SessionUtil.java, src/main/java/net/snowflake/client/jdbc/cloud/storage/S3HttpUtil.java, src/main/java/net/snowflake/client/log/SFLoggerUtil.java, src/main/resources/net/snowflake/client/jdbc/jdbc_error_messages.properties
=> SNOW-1167985: Logs - Session

src/main/java/net/snowflake/client/core/json/Converters.java, src/test/java/net/snowflake/client/jdbc/structuredtypes/ResultSetStructuredTypesLatestIT.java
=> SNOW-1312775 Fix double float converter

src/test/java/net/snowflake/client/core/SFTrustManagerIT.java, src/test/java/net/snowflake/client/jdbc/ConnectionLatestIT.java, src/test/java/net/snowflake/client/jdbc/HeartbeatAsyncLatestIT.java
SNOW-1213116
Replace sleep with awaitility to reduce overall test time
This is related it issue [894](https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/894)
=> SNOW-1213116-Replace sleep with awaitility to reduce overall test time

src/main/java/net/snowflake/client/jdbc/cloud/storage/SnowflakeAzureClient.java, src/main/java/net/snowflake/client/jdbc/cloud/storage/SnowflakeGCSClient.java, src/main/java/net/snowflake/client/jdbc/cloud/storage/SnowflakeS3Client.java, src/main/java/net/snowflake/client/jdbc/cloud/storage/StorageHelper.java
=> SNOW-1167991: Logs - Remote storage

TestOnly/pom.xml, src/main/java/net/snowflake/client/core/ArrowSqlInput.java, src/main/java/net/snowflake/client/core/BaseSqlInput.java, src/main/java/net/snowflake/client/core/JsonSqlInput.java, src/main/java/net/snowflake/client/core/SFSqlInput.java, src/test/java/net/snowflake/client/jdbc/structuredtypes/ResultSetStructuredTypesLatestIT.java, src/test/java/net/snowflake/client/jdbc/structuredtypes/sqldata/NestedStructSqlData.java
=> SNOW-1312775 - nested structures - readArray, readList, readMap

.github/workflows/build-test.yml, ci/container/test_component.sh
=> SNOW-1333078: Try to fix maven timeout on CI

src/test/java/net/snowflake/client/jdbc/BindingDataIT.java, src/test/java/net/snowflake/client/jdbc/CallableStatementIT.java, src/test/java/net/snowflake/client/jdbc/CallableStatementLatestIT.java, src/test/java/net/snowflake/client/jdbc/ChunkDownloaderS3RetryUrlLatestIT.java, src/test/java/net/snowflake/client/jdbc/ClientMemoryLimitParallelIT.java, src/test/java/net/snowflake/client/jdbc/ConnectionIT.java, src/test/java/net/snowflake/client/jdbc/ConnectionLatestIT.java, src/test/java/net/snowflake/client/jdbc/ConnectionManual.java, src/test/java/net/snowflake/client/jdbc/ConnectionPoolingIT.java, src/test/java/net/snowflake/client/jdbc/CustomProxyLatestIT.java, src/test/java/net/snowflake/client/jdbc/DatabaseMetaDataIT.java, src/test/java/net/snowflake/client/jdbc/DatabaseMetaDataInternalIT.java, src/test/java/net/snowflake/client/jdbc/DatabaseMetaDataInternalLatestIT.java, src/test/java/net/snowflake/client/jdbc/DatabaseMetaDataLatestIT.java, src/test/java/net/snowflake/client/jdbc/DatabaseMetaDataResultSetLatestIT.java, src/test/java/net/snowflake/client/jdbc/DatabaseMetaDataResultsetIT.java
=> SNOW-1213117: Wrap connection, statement and result set in try with resources(1/4)

src/main/java/net/snowflake/client/core/SFSession.java
=> SNOW-1161547: Set max retries for get query metadata

ci/container/test_component.sh, parent-pom.xml
=> SNOW-1333078: Add explicitly surefire autodetected dependencies

src/main/java/net/snowflake/client/core/SFJsonResultSet.java, src/main/java/net/snowflake/client/jdbc/SnowflakeUtil.java, src/test/java/net/snowflake/client/jdbc/ResultSetIT.java
=> SNOW-1416051: Fix getObject for array in json

CHANGELOG.rst, FIPS/pom.xml, parent-pom.xml, pom.xml
=> Bump version to 3.16.1 for release

.github/pull_request_template.md
=> SNOW-1009500: Update PR template

FIPS/pom.xml, pom.xml
SNOW-1454594 Removing shading of com.sun.* from pom.xml in JDBC and JDBC FIPS.
=> SNOW-1454594 Remove Shading of com.sun.*

src/main/java/net/snowflake/client/core/SFResultSetMetaData.java, src/main/java/net/snowflake/client/jdbc/SnowflakeColumnMetadata.java, src/main/java/net/snowflake/client/jdbc/SnowflakeDatabaseMetaData.java, src/main/java/net/snowflake/client/jdbc/SnowflakeResultSetMetaData.java, src/main/java/net/snowflake/client/jdbc/SnowflakeResultSetMetaDataV1.java, src/main/java/net/snowflake/client/jdbc/SnowflakeUtil.java, src/test/java/net/snowflake/client/jdbc/DatabaseMetaDataLatestIT.java, src/test/java/net/snowflake/client/jdbc/SnowflakeUtilTest.java
=> SNOW-1452552: Expose vector dimension in column metadata

.github/workflows/build-test.yml, FIPS/pom.xml, ci/test_windows.bat, pom.xml
SNOW-1016467: Support test Windows environment in Github actions.
=> SNOW-1016467: Support test Windows environment in Github actions.

src/test/java/net/snowflake/client/jdbc/ConnectionWithOCSPModeIT.java
=> SNOW-1446174: Accept 513 next to 403 for OCSP tests

src/main/java/net/snowflake/client/core/SFArrowResultSet.java, src/main/java/net/snowflake/client/core/SFJsonResultSet.java, src/main/java/net/snowflake/client/core/arrow/VectorTypeConverter.java, src/test/java/net/snowflake/client/jdbc/ResultSetVectorLatestIT.java
=> SNOW-1495591: Support getObject on vector column

.github/workflows/build-test.yml, Jenkinsfile, ci/_init.sh, ci/image/Dockerfile.jdbc-centos7-openjdk-test, parent-pom.xml
=> SNOW-1490931: Preparation for Java 21

CHANGELOG.rst, FIPS/pom.xml, parent-pom.xml, pom.xml, src/main/java/net/snowflake/client/jdbc/SnowflakeDriver.java
=> Bump version to 3.17.0 for release

FIPS/pom.xml, parent-pom.xml, pom.xml, src/main/java/net/snowflake/client/jdbc/SnowflakeDriver.java
=> Prepare next development version

src/main/java/net/snowflake/client/core/SFSession.java, src/main/java/net/snowflake/client/core/SessionUtil.java, src/main/java/net/snowflake/client/jdbc/SnowflakeDriver.java, src/main/java/net/snowflake/client/jdbc/telemetryOOB/TelemetryService.java, src/test/java/net/snowflake/client/jdbc/SnowflakeDriverLatestIT.java
=> SNOW-1528799: Disable OOB telemetry

src/test/java/net/snowflake/client/jdbc/LobSizeLatestIT.java
SNOW-1530843: Parametrized max lob size tests
Fixes #NNNN 
=> SNOW-1530843: Parametrized max lob size tests

src/main/java/net/snowflake/client/core/SFSession.java
=> SNOW-1526507: Add INFO log for connecting to host in China

src/main/java/net/snowflake/client/core/SessionUtil.java, src/main/java/net/snowflake/client/core/StmtUtil.java
=> SNOW-1454348: Remove duplicated consts

.github/pull_request_template.md
=> SNOW-1548029: Remove 'Fixes' from PR template to not close issues automatically

src/test/java/net/snowflake/client/jdbc/StatementIT.java
=> SNOW-1553640: Fix flaky test StatementArrowIT.testTelemetryBatch

src/main/java/net/snowflake/client/jdbc/cloud/storage/EncryptionProvider.java, src/main/java/net/snowflake/client/jdbc/cloud/storage/GcmEncryptionProvider.java, src/main/java/net/snowflake/client/jdbc/cloud/storage/SnowflakeAzureClient.java, src/main/java/net/snowflake/client/jdbc/cloud/storage/SnowflakeGCSClient.java, src/main/java/net/snowflake/client/jdbc/cloud/storage/SnowflakeS3Client.java, src/main/java/net/snowflake/client/jdbc/cloud/storage/SnowflakeStorageClient.java, src/test/java/net/snowflake/client/jdbc/cloud/storage/EncryptionProviderTest.java, src/test/java/net/snowflake/client/jdbc/cloud/storage/GcmEncryptionProviderTest.java
SNOW-1431870 Implemented GCM encryption to be used in cloud integration
=> SNOW-1431870 Implement GCM encryption

src/main/java/net/snowflake/client/config/SFConnectionConfigParser.java
=> SNOW-1454054: Clarifymessage about excessive permission

src/main/java/net/snowflake/client/core/SnowflakeJdbcInternalApi.java
=> SNOW-1566836: Make SnowflakeJdbcInternalApi visible on annotated elements in javadoc

src/test/java/net/snowflake/client/jdbc/SnowflakeDriverLatestIT.java
=> SNOW-1616480: GCS presigned URL test turn off

src/test/java/net/snowflake/client/jdbc/ConnectionIT.java
=> SNOW-1625156: Fix keypair tests

parent-pom.xml, thin_public_pom.xml
=> SNOW-1625000: Upgrade threeten-bp to 1.6.9

src/main/java/net/snowflake/client/core/SFArrowResultSet.java, src/main/java/net/snowflake/client/core/SFBaseResultSet.java, src/main/java/net/snowflake/client/core/arrow/fullvectorconverters/AbstractArrowFullVectorConverter.java, src/main/java/net/snowflake/client/core/arrow/fullvectorconverters/ArrowFullVectorConverter.java, src/main/java/net/snowflake/client/core/arrow/fullvectorconverters/BigIntVectorConverter.java, src/main/java/net/snowflake/client/core/arrow/fullvectorconverters/DecimalVectorConverter.java, src/main/java/net/snowflake/client/core/arrow/fullvectorconverters/IntVectorConverter.java, src/main/java/net/snowflake/client/core/arrow/fullvectorconverters/SimpleArrowFullVectorConverter.java, src/main/java/net/snowflake/client/core/arrow/fullvectorconverters/SmallIntVectorConverter.java, src/main/java/net/snowflake/client/core/arrow/fullvectorconverters/TinyIntVectorConverter.java, src/main/java/net/snowflake/client/jdbc/ArrowResultChunk.java, src/main/java/net/snowflake/client/jdbc/SFAsyncResultSet.java, src/main/java/net/snowflake/client/jdbc/SnowflakeResultSet.java, src/main/java/net/snowflake/client/jdbc/SnowflakeResultSetV1.java, src/test/java/net/snowflake/client/jdbc/ArrowBatchesTest.java
Initial version of the arrow batches interface, including handling of fixed point times.
=> Arrow batches initial

src/main/java/net/snowflake/client/jdbc/SnowflakeConnectString.java, src/main/java/net/snowflake/client/util/SecretDetector.java, src/test/java/net/snowflake/client/util/SecretDetectorTest.java
=> SNOW-144173: Add more cases

CHANGELOG.rst, FIPS/pom.xml
=> Bump version to 3.19.0 for release

CHANGELOG.rst, FIPS/pom.xml, parent-pom.xml, pom.xml, src/main/java/net/snowflake/client/jdbc/SnowflakeDriver.java
=> Bump version to 3.19.0 for release 

src/test/java/net/snowflake/client/jdbc/ConnectionIT.java
=> org_test_reintroducing

FIPS/pom.xml, parent-pom.xml, pom.xml, src/main/java/net/snowflake/client/jdbc/SnowflakeDriver.java
=> Prepare next development version 3.19.1-SNAPSHOT

parent-pom.xml, thin_public_pom.xml
Bump protobuf-java to 3.25.5 to address CVE-2024-7254
=> SNOW-1726146 bump protobuf-java to 3.25.5

CHANGELOG.rst, FIPS/pom.xml, parent-pom.xml, pom.xml
This reverts commit 1c36229b2556b56b9dc2f673f37edb843d9a4420.
SNOW-XXXXX
Issue: #NNNN
=> Revert "Bump version to 3.19.1 for release (#1907)"

FIPS/pom.xml
=> SNOW-1730937: Remove repopositories definition from FIPS pom

FIPS/pom.xml, FIPS/public_pom.xml, linkage-checker-exclusion-rules.xml, parent-pom.xml, pom.xml, thin_public_pom.xml
=> SNOW-1567156: Bump bouncy castle dependencies

src/main/java/net/snowflake/client/core/SFLoginOutput.java
=> SNOW-1752941: Fix SFLoginOutput connection timeout

src/test/java/net/snowflake/client/jdbc/ConnectionWithOCSPModeIT.java
=> SNOW-1759523: Accept 404 for OCSP tests with fakeaccount

parent-pom.xml, thin_public_pom.xml
=> SNOW-1732054: Bump commons io dependency

FIPS/scripts/check_content.sh, ci/scripts/check_content.sh
=> SNOW-1757822: Exclude directories from shaded packages check

README.rst
=> SNOW-1756807: Add note about GCP regional endpoints

src/main/java/net/snowflake/client/jdbc/cloud/storage/SnowflakeAzureClient.java, src/main/java/net/snowflake/client/jdbc/cloud/storage/SnowflakeGCSClient.java
=> SNOW-1553930: Fix incorrect key size condition check for GCP and Azure

src/test/java/net/snowflake/client/util/StopwatchTest.java
=> SNOW-1778027: Fix stopwatch flaky test

TestOnly/pom.xml
=> SNOW-1016464: Bump old driver version

FIPS/pom.xml, parent-pom.xml, pom.xml, thin_public_pom.xml
=> SNOW-1734031: Bump google dependencies

FIPS/pom.xml, pom.xml
=> SNOW-1803984: Fix shading of google properties

pom.xml
=> SNOW-1800995: Merge io.netty.versions.properties during shading thin

FIPS/pom.xml, README.rst, parent-pom.xml, pom.xml, src/main/java/net/snowflake/client/jdbc/SnowflakeDriver.java
This reverts commit 07510711e158af25c0a97bfda965bbda142b5436.
=> Revert "Prepare next development version 3.21.1 snapshot (#1987)"

src/main/java/net/snowflake/client/jdbc/SnowflakeFileTransferAgent.java, src/main/java/net/snowflake/client/jdbc/SnowflakeFileTransferConfig.java, src/test/java/net/snowflake/client/jdbc/SnowflakeFileTransferConfigTest.java
=> SNOW-1878090: Silent exception in uploadWithoutConnection

src/main/java/net/snowflake/client/core/SnowflakeOrgInternalApi.java, src/main/java/net/snowflake/client/jdbc/SnowflakeFileTransferAgent.java, src/main/java/net/snowflake/client/jdbc/SnowflakeFileTransferConfig.java
=> SNOW-1880020: Add marker annotation for Snowflake internal API

src/main/java/net/snowflake/client/core/SFBaseSession.java, src/main/java/net/snowflake/client/core/SFSession.java, src/main/java/net/snowflake/client/core/SFSessionProperty.java, src/main/java/net/snowflake/client/jdbc/SnowflakePreparedStatementV1.java, src/main/java/net/snowflake/client/jdbc/SnowflakeStatementV1.java, src/test/java/net/snowflake/client/TestUtil.java, src/test/java/net/snowflake/client/jdbc/BatchExecutionIT.java, src/test/java/net/snowflake/client/jdbc/BatchExecutionLatestIT.java, src/test/java/net/snowflake/client/jdbc/PreparedStatement2LatestIT.java
=> SNOW-1853752: Clear batch after successful execution

src/main/java/net/snowflake/client/jdbc/cloud/storage/SnowflakeGCSClient.java
=> SNOW-1889398: Handle endpoint without protocol for GCS

src/main/java/net/snowflake/client/core/HttpUtil.java, src/test/java/net/snowflake/client/core/HttpUtilTest.java, src/test/java/net/snowflake/client/core/SessionUtilTest.java
=> SNOW-1898533: Do not set proxy in global request config

src/test/java/net/snowflake/client/jdbc/SnowflakeBasicDataSourceTest.java
=> SNOW-1903631: Improve test assertions in datasource

src/main/java/net/snowflake/client/core/SessionUtil.java
=> SNOW-1940294: Convert string CLIENT_REQUEST_MFA_TOKEN to boolean

parent-pom.xml, thin_public_pom.xml
=> SNOW-1948960 Bump json smart dependency

CHANGELOG.rst, FIPS/pom.xml, parent-pom.xml, pom.xml, src/main/java/net/snowflake/client/jdbc/SnowflakeDriver.java
=> Bump version to 3.23.0 for release

FIPS/pom.xml, parent-pom.xml, pom.xml, src/main/java/net/snowflake/client/jdbc/SnowflakeDriver.java
=> Next verions 3.23.1

.github/workflows/build-test.yml, .github/workflows/check-style.yml
=> SNOW-1960924: Update GH Actions runner image

src/main/java/net/snowflake/client/core/FileCacheManager.java, src/test/java/net/snowflake/client/core/FileCacheManagerTest.java
=> SNOW-1965573 Fix file cache creation on windows

CHANGELOG.rst
SNOW-1963153 bump version to 3.23.1
Issue: #NNNN
=> SNOW-1963153 bump version to 3.23.1

CHANGELOG.rst, FIPS/pom.xml, parent-pom.xml, pom.xml
SNOW-1991221 bump-version-to-3.23.2
Issue: #NNNN
=> SNOW-1991221 bump version to 3.23.2

src/main/java/net/snowflake/client/core/SessionUtil.java, src/test/java/net/snowflake/client/core/SessionUtilTest.java
=>  NO-SNOW: Remove experimental feature check for PAT authentication

src/main/java/net/snowflake/client/core/JsonSqlOutput.java, src/main/java/net/snowflake/client/core/SFBaseSession.java, src/main/java/net/snowflake/client/core/SFSession.java, src/main/java/net/snowflake/client/core/SFSessionProperty.java, src/main/java/net/snowflake/client/core/bind/BindUploader.java, src/main/java/net/snowflake/client/jdbc/SnowflakePreparedStatementV1.java, src/test/java/net/snowflake/client/jdbc/BindingDataLatestIT.java
=> SNOW-1950032 Fix Gregorian dates handling in BindUploader and handling of TIME as wall clock time

CHANGELOG.rst, FIPS/pom.xml, parent-pom.xml, pom.xml, src/main/java/net/snowflake/client/jdbc/SnowflakeDriver.java
=> SNOW-2028394 - Bump version to 3.24.0 for release

FIPS/pom.xml, parent-pom.xml, pom.xml, src/main/java/net/snowflake/client/jdbc/SnowflakeDriver.java
=> SNOW-2028394 - Prepare next development version 3.24.1-SNAPSHOT

src/test/java/net/snowflake/client/jdbc/DatabaseMetaDataResultSetLatestIT.java, src/test/java/net/snowflake/client/jdbc/structuredtypes/ResultSetStructuredTypesLatestIT.java
=> NO-SNOW Enable structured types in FDN tables

src/main/java/net/snowflake/client/config/SFClientConfigParser.java
SNOW-2102874 Fixed easy logging error message
Issue: #NNNN
=> SNOW-2102874 Fix easy logging error message

src/main/java/net/snowflake/client/core/SessionUtil.java, src/main/java/net/snowflake/client/core/auth/wif/AwsAttestationService.java, src/main/java/net/snowflake/client/core/auth/wif/AwsIdentityAttestationCreator.java, src/test/java/net/snowflake/client/AbstractDriverIT.java, src/test/java/net/snowflake/client/core/auth/wif/AwsIdentityAttestationCreatorTest.java
=> SNOW-2110500: Fix WIF request signature for AWS

src/main/java/net/snowflake/client/core/bind/BindUploader.java, src/test/java/net/snowflake/client/jdbc/BindingDataLatestIT.java
=> SNOW-1950032 Fix Julian/Gregorian timestamps in bind uploader

src/main/java/net/snowflake/client/core/SFTrustManager.java
=> SNOW-2085856 Address OCSP check vulnerability in JDBC - Stop chain traversal if root certificate found

src/main/java/net/snowflake/client/core/AttributeEnhancingHttpRequestRetryHandler.java, src/main/java/net/snowflake/client/core/HeaderCustomizerHttpRequestInterceptor.java, src/main/java/net/snowflake/client/core/HttpUtil.java, src/main/java/net/snowflake/client/core/SFSession.java, src/main/java/net/snowflake/client/core/SFSessionProperty.java, src/main/java/net/snowflake/client/jdbc/DefaultResultStreamProvider.java, src/main/java/net/snowflake/client/jdbc/DefaultSFConnectionHandler.java, src/main/java/net/snowflake/client/jdbc/HttpHeadersCustomizer.java, src/main/java/net/snowflake/client/jdbc/SnowflakeBasicDataSource.java, src/main/java/net/snowflake/client/jdbc/cloud/storage/SnowflakeGCSClient.java, src/main/java/net/snowflake/client/jdbc/cloud/storage/SnowflakeS3Client.java, src/test/java/net/snowflake/client/core/AttributeEnhancingHttpRequestRetryHandlerTest.java, src/test/java/net/snowflake/client/core/HeaderCustomizerHttpRequestInterceptorTest.java, src/test/java/net/snowflake/client/core/HttpUtilLatestIT.java, src/test/java/net/snowflake/client/core/HttpUtilWiremockLatestIT.java, src/test/java/net/snowflake/client/jdbc/ChunkDownloaderS3RetryUrlLatestIT.java, src/test/java/net/snowflake/client/jdbc/DefaultSFConnectionHandlerTest.java, src/test/java/net/snowflake/client/jdbc/SnowflakeBasicDataSourceTest.java
=> SNOW-2041976 Add support for HTTP header customizers

src/main/java/net/snowflake/client/core/SessionUtil.java
=> SNOW-2082201 MFA caching does not work when using Duo authenticator #1268

prober/Dockerfile, prober/Jenkinsfile.groovy, prober/entrypoint.sh, prober/src/main/java/com/snowflake/client/jdbc/prober/Prober.java
=> SNOW-2117067 Add initial JDBC prober configuration

prober/Dockerfile, prober/entrypoint.sh, prober/src/main/java/com/snowflake/client/jdbc/prober/Prober.java
=> SNOW-2117067 Change probing behavior to single java & jdbc version mode

src/test/java/net/snowflake/client/jdbc/DatabaseMetaDataLatestIT.java
SNOW-1678618
A fix in GS requires a JDBC test to be updated.
=> SNOW-1678618: Fix "signature" formatting in "DESC ROW ACCESS POLICY"

CHANGELOG.rst, FIPS/pom.xml, parent-pom.xml, pom.xml, src/main/java/net/snowflake/client/jdbc/SnowflakeDriver.java
=> SNOW-2131869 Prepare 3.25.0 release

FIPS/pom.xml, parent-pom.xml, pom.xml, src/main/java/net/snowflake/client/jdbc/SnowflakeDriver.java
=> SNOW-2131869 Set up new development version 3.25.1-SNAPSHOT

FIPS/pom.xml, parent-pom.xml, pom.xml, src/main/java/net/snowflake/client/jdbc/SnowflakeDriver.java
Reverts snowflakedb/snowflake-jdbc#2238
=> Revert "SNOW-2131869 Set up new development version 3.25.1-SNAPSHOT"

parent-pom.xml
SNOW-2183215
Issue: #NNNN
Update Maven deploy plugin to 3.1.4
=> SNOW-2183215: Update Maven deploy plugin to 3.1.4

parent-pom.xml
=> NO-SNOW: Rollback maven plugins

FIPS/pom.xml, parent-pom.xml, pom.xml
=> NO-SNOW: Add maven profile that uses central-publishing-maven-plugin to release

FIPS/pom.xml, pom.xml, public_pom.xml
=> NO-SNOW: Change public_pom.xml path in release plugin

FIPS/pom.xml, parent-pom.xml, pom.xml
=> NO-SNOW: Add maven-deploy-plugin and deploy-file goal usage

prober/Dockerfile, prober/entrypoint.sh, prober/src/main/java/com/snowflake/client/jdbc/prober/Prober.java
=> SNOW-2117067 Fix prober Dockerfile

FIPS/pom.xml, parent-pom.xml, pom.xml, src/main/java/net/snowflake/client/jdbc/SnowflakeDriver.java
=> SNOW-2187998 Prepare development version 3.25.2

src/main/java/net/snowflake/client/core/auth/oauth/OAuthUtil.java, src/test/java/net/snowflake/client/core/auth/oauth/OAuthUtilTest.java
=> SNOW-2223974: Remove trailing slash from default RedirectUri

src/main/java/net/snowflake/client/core/FieldSchemaCreator.java, src/main/java/net/snowflake/client/core/SFArrowResultSet.java, src/main/java/net/snowflake/client/core/SFBaseResultSet.java, src/main/java/net/snowflake/client/core/SfSqlArray.java, src/main/java/net/snowflake/client/jdbc/SnowflakeConnectionV1.java, src/main/java/net/snowflake/client/jdbc/SnowflakePreparedStatementV1.java, src/test/java/net/snowflake/client/jdbc/BindingDataLatestIT.java
SNOW-2208978 Add time/date/timestamp array bindings
=> SNOW-2208978 Add time/date/timestamp array bindings

src/main/java/net/snowflake/client/core/SfSqlArray.java, src/test/java/net/snowflake/client/jdbc/BindingDataLatestIT.java
SNOW-2240471 Fix binding array of timestamps
=> SNOW-2240471 Fix binding array of timestamps

src/main/java/net/snowflake/client/core/SessionUtil.java, src/main/java/net/snowflake/client/core/auth/wif/WorkloadIdentityAttestationProvider.java, src/test/java/net/snowflake/client/core/auth/wif/WorkloadIdentityAttestationProviderTest.java, src/test/java/net/snowflake/client/wif/WIFLatestIT.java
=> SNOW-2251261 Remove cloud autodetect

src/main/java/net/snowflake/client/core/SessionUtil.java, src/main/java/net/snowflake/client/core/auth/wif/AwsAttestationService.java, src/main/java/net/snowflake/client/core/auth/wif/AwsIdentityAttestationCreator.java, src/main/java/net/snowflake/client/core/auth/wif/AzureAttestationService.java, src/main/java/net/snowflake/client/core/auth/wif/AzureIdentityAttestationCreator.java, src/main/java/net/snowflake/client/core/auth/wif/GcpIdentityAttestationCreator.java, src/main/java/net/snowflake/client/core/auth/wif/OidcIdentityAttestationCreator.java, src/main/java/net/snowflake/client/core/auth/wif/WorkloadIdentityAttestationCreator.java, src/main/java/net/snowflake/client/core/auth/wif/WorkloadIdentityAttestationProvider.java, src/main/java/net/snowflake/client/core/auth/wif/WorkloadIdentityUtil.java, src/test/java/net/snowflake/client/core/auth/wif/AwsIdentityAttestationCreatorTest.java, src/test/java/net/snowflake/client/core/auth/wif/AzureIdentityAttestationCreatorLatestIT.java, src/test/java/net/snowflake/client/core/auth/wif/GcpIdentityAttestationCreatorLatestIT.java, src/test/java/net/snowflake/client/core/auth/wif/OidcIdentityAttestationCreatorTest.java, src/test/java/net/snowflake/client/core/auth/wif/WorkloadIdentityAttestationProviderTest.java
=> SNOW-2256796: User friendly error handling for WIF

src/test/java/net/snowflake/client/jdbc/DatabaseMetaDataLatestIT.java
=> SNOW-2081602: Reenable test

src/main/java/net/snowflake/client/core/SFSSLConnectionSocketFactory.java, src/main/java/net/snowflake/client/core/SFSession.java, src/main/java/net/snowflake/client/core/SFSessionProperty.java, src/test/java/net/snowflake/client/core/SFSSLConnectionSocketFactoryTest.java
=> SNOW-2181352: Add support for TLSv1.3

FIPS/pom.xml, parent-pom.xml, pom.xml, src/main/java/net/snowflake/client/jdbc/SnowflakeDriver.java
=> SNOW-2266626: Prepare 3.26.2 development version

src/main/java/net/snowflake/client/core/arrow/ArrowVectorConverterUtil.java, src/main/java/net/snowflake/client/core/arrow/DecfloatToDecimalConverter.java, src/main/java/net/snowflake/client/core/arrow/DecfloatToRealConverter.java, src/main/java/net/snowflake/client/jdbc/SnowflakeType.java, src/main/java/net/snowflake/client/jdbc/SnowflakeUtil.java, src/test/java/net/snowflake/client/jdbc/DecfloatTypeLatestIT.java
=> SNOW-1877975 Decfloat read support

src/test/java/net/snowflake/client/jdbc/ConnectionIT.java
=> NO-SNOW remove disabled tests

prober/src/main/java/com/snowflake/client/jdbc/prober/Prober.java
SNOW-2220712: extending-probing-image
Issue: #NNNN
=> SNOW-2220712: extending-probing-image

src/test/java/net/snowflake/client/jdbc/PreparedStatement1IT.java, src/test/java/net/snowflake/client/jdbc/PreparedStatement2IT.java
=> SNOW-2372999: Prepared-statement fixing-flaky test

CHANGELOG.md, FIPS/pom.xml, parent-pom.xml, pom.xml, src/main/java/net/snowflake/client/jdbc/SnowflakeDriver.java
=> NO-SNOW: Bump version to 3.27.1-SNAPSHOT
