snowflakedb/snowflake-jdbc

src/main/java/net/snowflake/client/jdbc/SnowflakeUtil.java

Java uses BigDecimal to present decimal, a BigDecimal consists of an arbitrary precision integer unscaled value and a 32-bit integer scale.
https://docs.oracle.com/javase/7/docs/api/java/math/BigDecimal.html
https://www.cis.upenn.edu/~bcpierce/courses/629/jdkdocs/guide/jdbc/getstart/mapping.doc.html
1. 32 bit
2. May have arbitrary precision integer unscaled value.
While NUMBER(38,0)
1. 38 bit
2. Scale is 0
So decimal is not a suitable mapping for NUMBER(38,0), a better mapping maybe BIGINT.
https://www.cis.upenn.edu/~bcpierce/courses/629/jdkdocs/guide/jdbc/getstart/mapping.doc.html

Use BIGINT to represent NUMBER(38,0) as DECIMAL only range 2^31

---

src/main/java/net/snowflake/client/jdbc/SnowflakeBasicDataSource.java

setLoginTimeout is putting a Integer value into Properties,
the call to getProperty returns null in SnowflakeConnectionV1.

Fix NumberFormatException after calling setLoginTimeout

---

src/main/resources/META-INF/services/java.sql.Driver

https://docs.oracle.com/javase/7/docs/api/java/sql/DriverManager.html specifies that JDBC 4.0 Drivers include this file.  The presence of this file removes the need to do an explicit Class.forName call before calling getConnection.

Add java.sql.Driver file

---

pom.xml

Disabled shade relocation of slf4j to fix logger initialization

---

pom.xml
src/main/java/net/snowflake/client/jdbc/SnowflakeDatabaseMetaData.java
src/test/java/net/snowflake/client/jdbc/DatabaseMetaDataInternalIT.java

SNOW-163587
Calling getFunctionColumns(null, "%", "%", "%") resulted in a sql compilation error. I added more error checking so this does not happen.
However, all calls to "desc function" require the proper database and schema, and this data is not always available. So for built-in functions without a database and schema, getFunctionColumns() will not display their columns.

SNOW-163587 Fix sql compilation error for using wildcard % in getFunctionColumns()

---

FIPS/pom.xml
pom.xml

* Bump jackson-databind from 2.9.10.4 to 2.11.0
Bumps [jackson-databind](https://github.com/FasterXML/jackson) from 2.9.10.4 to 2.11.0.
- [Release notes](https://github.com/FasterXML/jackson/releases)
- [Commits](https://github.com/FasterXML/jackson/commits)
Signed-off-by: dependabot[bot] <support@github.com>
* updated the version
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: Shige Takeda <shige.takeda@snowflake.com>

SNOW-169174 Bump jackson-databind from 2.9.10.4 to newer version (#261)

---

src/main/java/net/snowflake/client/core/FileCacheManager.java
src/main/java/net/snowflake/client/core/HttpUtil.java
src/main/java/net/snowflake/client/core/SFTrustManager.java

When multiple threads/processes attempt to create the same directory in the same timing, one of them will be success but not others. This race condition makes the initialization of `FileCacheManager` fail and stop the process.
The fix is to change the order of 1) check the directory existence and 2) `mkdirp` so that the directory is always guaranteed to be created as long as the process has a write access to avoid the error.
Aside from it, this change completely removes `RuntimeException` from `FileCacheManager` to reduce a chance of unexpected error when `SFTrustManager` is initialized in `HttpUtil`.

Snow 169416 fix race condition in creating cachedir

---

src/main/java/net/snowflake/client/core/HttpUtil.java
src/main/java/net/snowflake/client/jdbc/RestRequest.java
src/main/java/net/snowflake/client/util/SecretDetector.java
src/test/java/net/snowflake/client/jdbc/SessionVariablesIT.java
src/test/java/net/snowflake/client/jdbc/SnowflakeResultSetSerializableIT.java
src/test/java/net/snowflake/client/util/SecretDetectorTest.java

JDBC Secret Detector now replace each sensitive data's character with a smiley face. 
However, it is causing two problems. 
> First, it will leak the length of the sensitive data.
> Second, for some unclear reason, RT-LanguageJDBC test fails to render smiley face in log files, which is causing detection issue.
> Besides, to keep it consistent with other drivers has no harm.
So, we choose to mask sensitive data with `****` constantly.

SNOW-170944: Change the way that secret detector masks sensitive data

---

src/main/java/net/snowflake/client/core/SessionUtil.java

The properties of app ID and app version are listed twice in Client_Environment field. They appear both in the list of connection parameters, and also in the list of runtime properties. I have removed these 2 properties from the connection parameters.

SNOW-171834 Remove redundant properties from ClientEnv

---

src/main/java/net/snowflake/client/core/SFArrowResultSet.java
src/main/java/net/snowflake/client/core/SFFixedViewResultSet.java
src/main/java/net/snowflake/client/core/SFResultSet.java
src/main/java/net/snowflake/client/core/SFResultSetFactory.java
src/main/java/net/snowflake/client/core/SFStatement.java
src/main/java/net/snowflake/client/core/SessionUtil.java
src/main/java/net/snowflake/client/jdbc/ArrowResultChunk.java
src/main/java/net/snowflake/client/jdbc/JsonResultChunk.java
src/main/java/net/snowflake/client/jdbc/ResultJsonParserV2.java
src/main/java/net/snowflake/client/jdbc/SnowflakeChunkDownloader.java
src/main/java/net/snowflake/client/jdbc/SnowflakeConnectionV1.java
src/main/java/net/snowflake/client/jdbc/SnowflakeDatabaseMetaData.java
src/main/java/net/snowflake/client/jdbc/SnowflakeDriver.java
src/main/java/net/snowflake/client/jdbc/SnowflakeFileTransferAgent.java
src/main/java/net/snowflake/client/jdbc/SnowflakeFixedView.java
src/main/java/net/snowflake/client/jdbc/SnowflakeResultSetSerializableV1.java
src/main/java/net/snowflake/client/jdbc/SnowflakeSQLException.java
src/main/java/net/snowflake/client/jdbc/SnowflakeSQLLoggedException.java
src/main/java/net/snowflake/client/jdbc/SnowflakeStatementV1.java
src/main/java/net/snowflake/client/jdbc/SnowflakeUtil.java
src/main/java/net/snowflake/client/jdbc/cloud/storage/SnowflakeAzureClient.java
src/main/java/net/snowflake/client/jdbc/cloud/storage/SnowflakeGCSClient.java
src/main/java/net/snowflake/client/jdbc/cloud/storage/SnowflakeS3Client.java
src/main/java/net/snowflake/client/jdbc/cloud/storage/SnowflakeStorageClient.java
src/main/java/net/snowflake/client/jdbc/cloud/storage/StorageClientFactory.java
src/test/java/net/snowflake/client/core/SFArrowResultSetIT.java
src/test/java/net/snowflake/client/jdbc/ResultJsonParserV2IT.java
src/test/java/net/snowflake/client/jdbc/SnowflakeDriverIT.java
src/test/java/net/snowflake/client/jdbc/telemetryOOB/TelemetryServiceIT.java

There is a set of exceptions in the JDBC driver that are raised due to internal errors.  
These could be caused by:
- Null or out-of-range values from other driver functions
- Invalid conversions of data types (attempt to turn an integer into a timestamp, or something like that)
- Unexpected errors caused by external library functions
This set of exceptions should not include errors due to:
- User-generated error
- Issues caused by a valid JSON response from GS. These are already recorded in Snowhouse
These internal errors have been refactored to send a telemetry message by changing their constructor to be SnowflakeSQLLoggedExceptions.

SNOW-164505 Refactor internal error exceptions to be SnowflakeSQLLoggedExceptions

---

src/main/java/net/snowflake/client/core/SFArrowResultSet.java
src/main/java/net/snowflake/client/core/SFResultSet.java
src/main/java/net/snowflake/client/core/SFResultSetMetaData.java
src/main/java/net/snowflake/client/core/SFSession.java
src/main/java/net/snowflake/client/core/SFStatement.java
src/main/java/net/snowflake/client/jdbc/ArrowResultChunk.java
src/main/java/net/snowflake/client/jdbc/RestRequest.java
src/main/java/net/snowflake/client/jdbc/SFAsyncResultSet.java
src/main/java/net/snowflake/client/jdbc/SnowflakeChunkDownloader.java
src/main/java/net/snowflake/client/jdbc/SnowflakeConnectionV1.java
src/main/java/net/snowflake/client/jdbc/SnowflakeFileTransferAgent.java
src/main/java/net/snowflake/client/jdbc/SnowflakePreparedStatementV1.java
src/main/java/net/snowflake/client/jdbc/SnowflakeResultSetMetaDataV1.java
src/main/java/net/snowflake/client/jdbc/SnowflakeResultSetSerializableV1.java
src/main/java/net/snowflake/client/jdbc/SnowflakeResultSetV1.java
src/main/java/net/snowflake/client/jdbc/SnowflakeStatementV1.java
src/main/java/net/snowflake/client/jdbc/cloud/storage/SnowflakeAzureClient.java
src/main/java/net/snowflake/client/jdbc/cloud/storage/SnowflakeGCSClient.java
src/main/java/net/snowflake/client/jdbc/cloud/storage/SnowflakeS3Client.java
src/main/java/net/snowflake/client/jdbc/cloud/storage/StorageClientFactory.java

Several types of exceptions are caught by JDBC driver functions due to external errors, and then these errors are caught and re-thrown as SQLExceptions, usually classified with the SQLState of "Internal Error." These have been refactored so that the exceptions are logged with telemetry.

SNOW-164505 Refactor caught and re-thrown SQLExceptions into SnowflakeSQLLoggedExceptions

---

src/main/java/net/snowflake/client/jdbc/SnowflakeFileTransferAgent.java

This is an issue resulting from a previous rebase. I tried to convert SnowflakeSQLException to SnowflakeSQLLoggedException but did not change constructor name in this case. Just added session, which showed up as a parameter for SnowflakeSQLException and displayed as the directory name in the error message. The fix is to change the exception constructor to SnowflakeSQLLoggedException.

SNOW-178702 Error during rebase - missed conversion from SnowflakeSQLException to SnowflakeSQLLoggedException

---

src/main/java/net/snowflake/client/core/SFArrowResultSet.java
src/main/java/net/snowflake/client/core/SFResultSet.java
src/main/java/net/snowflake/client/jdbc/SnowflakeFileTransferAgent.java
src/main/java/net/snowflake/client/jdbc/SnowflakePreparedStatementV1.java
src/main/java/net/snowflake/client/jdbc/SnowflakeType.java
src/main/java/net/snowflake/client/jdbc/SnowflakeUtil.java

There is a set of exceptions raised when a user tries to call on a JDBC driver feature or function that is not supported. We want to gather metrics on when these exceptions are raised and these features are attempted to be used. These exceptions have been refactored so that a telemetry message is sent when they are raised by changing them to SnowflakeSQLLoggedExceptions.

SNOW-164505 Refactor FEATURE_NOT_SUPPORTED exceptions into SnowflakeSQLLoggedExceptions

---

src/main/java/net/snowflake/client/jdbc/SnowflakeFileTransferAgent.java
src/main/java/net/snowflake/client/jdbc/cloud/storage/SnowflakeAzureClient.java
src/main/java/net/snowflake/client/jdbc/cloud/storage/SnowflakeGCSClient.java
src/main/java/net/snowflake/client/jdbc/cloud/storage/SnowflakeS3Client.java
src/main/java/net/snowflake/client/jdbc/cloud/storage/StageInfo.java
src/main/java/net/snowflake/client/jdbc/cloud/storage/StorageClientFactory.java
src/test/java/net/snowflake/client/jdbc/SnowflakeDriverIT.java

This checkin adds support for named stages that don't use client-side encryption for data lake scenarios. You can create a stage that doesn't use client-side encryption like this:
CREATE OR REPLACE STAGE testPutGet_unencstage encryption=(TYPE='SNOWFLAKE_SSE');
Unencrypted stages allow data lake users to create stand-alone presigned URLs to objects on internal stages so that other parts of the data lake pipeline can use the object without encryption/decryption (which only Snowflake can do). This enables customers to use their objects in image processing pipelines, unstructured data scenarios, and other things that Snowflake can't do directly on these objects.
To ensure there is server-side encryption on these objects, S3 objects without CSE are uploaded with SSE-S3 encryption specified. We …

SNOW-161456 Support for unencrypted stages in JDBC

---

src/main/java/net/snowflake/client/core/SFArrowResultSet.java
src/main/java/net/snowflake/client/core/SFFixedViewResultSet.java
src/main/java/net/snowflake/client/core/SFResultSet.java
src/main/java/net/snowflake/client/core/SFResultSetFactory.java
src/main/java/net/snowflake/client/core/SFSession.java
src/main/java/net/snowflake/client/core/SFStatement.java
src/main/java/net/snowflake/client/core/SessionUtil.java
src/main/java/net/snowflake/client/jdbc/ArrowResultChunk.java
src/main/java/net/snowflake/client/jdbc/JsonResultChunk.java
src/main/java/net/snowflake/client/jdbc/RestRequest.java
src/main/java/net/snowflake/client/jdbc/ResultJsonParserV2.java
src/main/java/net/snowflake/client/jdbc/SFAsyncResultSet.java
src/main/java/net/snowflake/client/jdbc/SnowflakeChunkDownloader.java
src/main/java/net/snowflake/client/jdbc/SnowflakeConnectionV1.java
src/main/java/net/snowflake/client/jdbc/SnowflakeDriver.java
src/main/java/net/snowflake/client/jdbc/SnowflakeFileTransferAgent.java
src/main/java/net/snowflake/client/jdbc/SnowflakePreparedStatementV1.java
src/main/java/net/snowflake/client/jdbc/SnowflakeResultSetMetaDataV1.java
src/main/java/net/snowflake/client/jdbc/SnowflakeResultSetSerializableV1.java
src/main/java/net/snowflake/client/jdbc/SnowflakeResultSetV1.java
src/main/java/net/snowflake/client/jdbc/SnowflakeSQLLoggedException.java
src/main/java/net/snowflake/client/jdbc/SnowflakeStatementV1.java
src/main/java/net/snowflake/client/jdbc/SnowflakeType.java
src/main/java/net/snowflake/client/jdbc/SnowflakeUtil.java
src/main/java/net/snowflake/client/jdbc/cloud/storage/SnowflakeAzureClient.java
src/main/java/net/snowflake/client/jdbc/cloud/storage/SnowflakeGCSClient.java
src/main/java/net/snowflake/client/jdbc/cloud/storage/SnowflakeS3Client.java
src/main/java/net/snowflake/client/jdbc/cloud/storage/SnowflakeStorageClient.java
src/test/java/net/snowflake/client/jdbc/ConnectionIT.java
src/test/java/net/snowflake/client/jdbc/telemetryOOB/TelemetryServiceIT.java

Change signatures from:
`public SnowflakeSQLLoggedException(int vendorCode, String SQLState, SFSession session, Object... params)`
to 
`public SnowflakeSQLLoggedException(SFSession, int vendorCode, String SQLState, Object... params)`
This will cause compilation error if someone tries to insert a session into a SnowflakeSQLException, which will make it easier to tell the 2 types of constructors apart.

SNOW-164505 change SnowflakeSQLLoggedException constructor to take session parameter first

---

ci/container/change_snowflake_test_pwd.py
src/main/java/net/snowflake/client/jdbc/SnowflakeSQLLoggedException.java
src/main/java/net/snowflake/client/jdbc/telemetry/TelemetryClient.java
src/main/java/net/snowflake/client/jdbc/telemetry/TelemetryData.java
src/main/java/net/snowflake/client/jdbc/telemetry/TelemetryUtil.java
src/main/java/net/snowflake/client/jdbc/telemetryOOB/TelemetryService.java
src/main/java/net/snowflake/client/log/JDK14Logger.java
src/main/java/net/snowflake/client/log/SFLogger.java
src/main/java/net/snowflake/client/log/SLF4JLogger.java
src/main/java/net/snowflake/client/util/SecretDetector.java
src/test/java/net/snowflake/client/util/SecretDetectorTest.java

Latest Update:
> Two things need to be aware of.    
1. Now inband telemetry's payload will be masked when it's built. 
2. `payloadLogStr` was added to solve the following issues.
The original string of telemetry OOB payload has no space as delimiter, which would cause false positive detection for log analyze ssm detector module. So we added a new smart-json output style class and store the payload with space as delimiter for dump usage.
Update:
The latest code introduces a function `debugNoMask` to solve the following issue.
> Issue: 
The main target of this pr is to include telemetry payload into our log files for log analyze module to detect potential leakage of sensitive data. The problem is if we use normal `logger.debug`, the payload will be masked by secret detector again. This …

SNOW-176125: Add two debug log

---

src/test/java/net/snowflake/client/jdbc/ConnectionIT.java

GS responses have gotten slower lately so this test is failing when it does not get the required response within 100ms. Now the test will retry for the response for up to 1 second (10 times) and still not fail if there is no GS data.

SNOW-183946 Fix flaky test

---

src/main/java/net/snowflake/client/jdbc/SnowflakeType.java
src/main/java/net/snowflake/client/jdbc/SnowflakeUtil.java
src/test/java/net/snowflake/client/jdbc/SnowflakeDriverIT.java

Description
When we parse the snowflake type, we got an exception because we never declared GEOGRAPHY as a type in the enum. Might need to add USER_DEFINED_TYPE later on if we allow users to create their own udts.
See https://github.com/snowflakedb/snowflake/pull/11930 for GS changes to `show columns`
Testing
Added test

SNOW-182763 Fix displaying GEOGRAPHY type in JDBC driver 

---

src/test/java/net/snowflake/client/jdbc/ResultSetIT.java
src/test/java/net/snowflake/client/jdbc/SnowflakeDriverIT.java
src/test/java/net/snowflake/client/jdbc/StatementIT.java

We are having an issue where PUT statements are returning a 400 Bad Response and all tests that test whether a file is uploaded with PUT are now failing. The BPTP team has requested that we disable the failing tests temporarily until we can find the GCP issue. A ticket has been opened with GCS. This relates to SNOW-186503. See Slack exchange https://snowflake.slack.com/archives/CUND9L30C/p1598288860026900

SNOW-186894 Ignore all PUT tests until GCP issue is solved

---

src/main/java/net/snowflake/client/core/SessionUtil.java
src/main/java/net/snowflake/client/jdbc/SnowflakeResultSetSerializable.java
src/main/java/net/snowflake/client/jdbc/SnowflakeResultSetSerializableV1.java
src/test/java/net/snowflake/client/core/SFTrustManagerTest.java
src/test/java/net/snowflake/client/jdbc/SnowflakeResultSetSerializableIT.java

Enhance SnowflakeResultSetSerializable.getResultSet() to support private link.
SNOW-190589
When JDBC connects to snowflake, the OCSP cache server is adjusted if the URL
is for private link. But the spark connector executors try to get the
ResultSet without connection. So the OCSP cache server adjusting is
skipped.
The fix proposal is:
1. Spark Connector needs to pass the snowflake URL into JDBC
2. JDBC adjusts the OCSP cache server if the URL is private link.
This PR is for item #2.

SNOW-190589 Support private link for Spark Connector

---

src/main/java/net/snowflake/client/jdbc/SnowflakeResultSetSerializable.java
src/main/java/net/snowflake/client/jdbc/SnowflakeResultSetSerializableV1.java

SnowflakeResultSetSerializable.getResultSet()

SNOW-190589 Keep deprecated API for spark connector compatibility

---

src/main/java/net/snowflake/client/core/SFStatement.java
src/main/java/net/snowflake/client/core/bind/BindUploader.java
src/main/java/net/snowflake/client/jdbc/SnowflakePreparedStatementV1.java
src/test/java/net/snowflake/client/jdbc/BindUploaderIT.java
src/test/java/net/snowflake/client/jdbc/PreparedStatement1IT.java

Currently, java Time objects can only be uploaded individually with insert statements, even if there are enough bind parameters to trigger bulk uploading via stage. This change allows time objects to be uploaded via stage by changing their serialization format.
Now the format is in HH:MM:SS.sssssssss instead of milliseconds.

SNOW-194437 Time values can now be uploaded via stage bind

---

src/main/java/net/snowflake/client/jdbc/telemetryOOB/TelemetryService.java

Some jdbc flaky tests failed with `Telemetry event has not been reported successfully. Error: Response: null; Error: Read timed out`. After some investigations, I think it's because we got timeout for sockets used by telemetryOOB. And the reason for timeout can be complex. Since this looks like a transient issue, retry failed tests would help. But IMO, retry would be the last solution for the issue, it comes with other risks which may give more pain. So I wanted to try to increase TIMEOUT settings for telemetry OOB first and see it that solves flaky tests.

SNOW-188629: Increase timeout for telemetry OOB

---

src/test/java/net/snowflake/client/jdbc/ResultSetIT.java

testReleaseDownloaderCurrentMemoryUsage can't finish for some unknown reason before on GH action. So it was ignored. But after retest, it looks good now. It's time to add it back.

SNOW-188218: testReleaseDownloaderCurrentMemoryUsage

---

src/main/java/net/snowflake/client/core/CredentialManager.java
src/main/java/net/snowflake/client/core/SecureStorageAppleManager.java
src/main/java/net/snowflake/client/core/SecureStorageWindowsManager.java

Since double-checked locking is a known bug in Java, we replace corresponding code with resource holder pattern.
Basically, the constructor is not guaranteed to finish before memory allocation. Then it's possible that thread A triggers the lazy initialization for `INSTANCE` and thread B might be able to see the allocated memory address for `INSTANCE` and use it while the constructor for it hasn't finished.
References:
https://rules.sonarsource.com/java/tag/multi-threading/RSPEC-2168
http://www.cs.umd.edu/~pugh/java/memoryModel/DoubleCheckedLocking.html

SNOW-198566: Replace double-checked locking with resource holder pattern

---

src/test/java/net/snowflake/client/jdbc/SnowflakeResultSetSerializableIT.java

The test that calls this function fails often with a ConcurrentModicationException. To prevent this, I think making the function synchronized will stop the exceptions.

SNOW-189408 fix ConcurrentModificationException

---

src/main/java/net/snowflake/client/jdbc/SnowflakePreparedStatementV1.java
src/test/java/net/snowflake/client/jdbc/PreparedStatement1IT.java
src/test/java/net/snowflake/client/jdbc/ResultSetMultiTimeZoneIT.java

While implementing the ability to upload Time values via a stage bind, we noticed that negative Time values (such as Time(-100) do not throw an exception when being bound (either via stage or just insert), so I added in an exception along with the ability to bind via stage in this PR: https://github.com/snowflakedb/snowflake-jdbc/pull/338
However, the addition of this exception is a behavior change for both binding Time values via stage or via individual insert statements. Given the current stability push, I think we should take this behavior change back out and re-visit the issue of negative Time values later. 
With this change, the behavior of setTime() will not be altered at all.

SNOW-194437 Revert small behavior change of negative time values

---

src/main/java/net/snowflake/client/loader/ProcessQueue.java
src/test/java/net/snowflake/client/loader/LoaderIT.java
src/test/java/net/snowflake/client/loader/LoaderLatestIT.java

[SNOW-201788](https://snowflakecomputing.atlassian.net/browse/SNOW-201788)
This is the same change as https://github.com/snowflakedb/snowflake-jdbc/pull/311 but the PR checks were failing on that one due to a permissions issue.

SNOW-201788 clustering key prevents temp table columns from being dropped

---

src/main/java/net/snowflake/client/jdbc/SnowflakePreparedStatementV1.java
src/test/java/net/snowflake/client/jdbc/PreparedStatement1IT.java
src/test/java/net/snowflake/client/jdbc/PreparedStatement1LatestIT.java
src/test/java/net/snowflake/client/jdbc/PreparedStatementArrow2IT.java

When there is no data in batch, we return directly.

SNOW-160809: Fix empty batch when using array bind

---

src/main/java/net/snowflake/client/core/arrow/ThreeFieldStructToTimestampTZConverter.java
src/main/java/net/snowflake/client/core/arrow/TwoFieldStructToTimestampTZConverter.java
src/test/java/net/snowflake/client/core/arrow/BigIntToFixedConverterTest.java
src/test/java/net/snowflake/client/core/arrow/BigIntToTimeConverterTest.java
src/test/java/net/snowflake/client/core/arrow/BigIntToTimestampLTZConverterTest.java
src/test/java/net/snowflake/client/core/arrow/BigIntToTimestampNTZConverterTest.java
src/test/java/net/snowflake/client/core/arrow/BitToBooleanConverterTest.java
src/test/java/net/snowflake/client/core/arrow/DateConverterTest.java
src/test/java/net/snowflake/client/core/arrow/DoubleToRealConverterTest.java
src/test/java/net/snowflake/client/core/arrow/IntToFixedConverterTest.java
src/test/java/net/snowflake/client/core/arrow/IntToTimeConverterTest.java
src/test/java/net/snowflake/client/core/arrow/SmallIntToFixedConverterTest.java
src/test/java/net/snowflake/client/core/arrow/ThreeFieldStructToTimestampTZConverterTest.java
src/test/java/net/snowflake/client/core/arrow/TinyIntToFixedConverterTest.java
src/test/java/net/snowflake/client/core/arrow/TwoFieldStructToTimestampLTZConverterTest.java
src/test/java/net/snowflake/client/core/arrow/TwoFieldStructToTimestampNTZConverterTest.java
src/test/java/net/snowflake/client/core/arrow/TwoFieldStructToTimestampTZConverterTest.java
src/test/java/net/snowflake/client/core/arrow/VarBinaryToBinaryConverterTest.java
src/test/java/net/snowflake/client/core/arrow/VarCharConverterTest.java

This fixes unexpected null check behaviors by overriding `isNull` methods.

SNOW-207061: fixed isNull for TimestampTZ converter

---

src/main/java/net/snowflake/client/log/JDK14Logger.java
src/test/java/net/snowflake/client/log/JDK14JCLWrapperLatestIT.java

Just noticed after looking through JDBC3 test console outputs at an unrelated failure that after adding tests for the logging wrappers (https://github.com/snowflakedb/snowflake-jdbc/pull/384), the JDK14JCLWrapper test messages are getting printed to the console in Jenkins tests, which is unnecessary.
This change of removing parent handlers for the test prevents the log output from being printed to the console.

SNOW-210997 Fix output of logging test for Jenkins

---

src/test/java/net/snowflake/client/jdbc/DatabaseMetaDataIT.java
src/test/java/net/snowflake/client/jdbc/DatabaseMetaDataLatestIT.java

Due to addition of GEOGRAPHY type in SnowflakeType, this test started failing old driver tests when Geography type didn't yet exist. Moving the failing test to LatestIT test category.

SNOW-227878 Fix failing JDBC3 test

---

src/test/java/net/snowflake/client/jdbc/GSRetryIT.java
src/test/java/net/snowflake/client/jdbc/GSRetryLatestIT.java

SNOW-225928 
Add JDBC specific Test which enables GS retry for the Prepare phase.

SNOW-225928 Add JDBC specific Test 

---

FIPS/pom.xml
pom.xml
src/main/java/net/snowflake/client/core/CredentialManager.java
src/main/java/net/snowflake/client/core/SFLoginInput.java
src/main/java/net/snowflake/client/core/SFLoginOutput.java
src/main/java/net/snowflake/client/core/SFSession.java
src/main/java/net/snowflake/client/core/SFSessionProperty.java
src/main/java/net/snowflake/client/core/SecureStorageAppleManager.java
src/main/java/net/snowflake/client/core/SecureStorageLinuxManager.java
src/main/java/net/snowflake/client/core/SecureStorageManager.java
src/main/java/net/snowflake/client/core/SecureStorageWindowsManager.java
src/main/java/net/snowflake/client/core/SessionUtil.java
src/test/java/net/snowflake/client/RunningNotOnLinux.java
src/test/java/net/snowflake/client/core/SecureStorageManagerTest.java
src/test/java/net/snowflake/client/core/SnowflakeMFACacheTest.java
src/test/java/net/snowflake/client/jdbc/SSOConnectionTest.java
src/test/java/net/snowflake/client/jdbc/SnowflakeMFACacheTest.java

**_NOTE!_**
This pr won't be merged until a thorough test with backend changes is done.
The whole context:
> For users who are using username-pwd plus MFA authentication, we plan to add a temporary mfa token cache. This mfa token cache helps prevent multiple MFA authentication with a short perioud of time, which is similar to previous ID_TOKEN. In other words, if user's connection request is sent with a correct pwd (yes, pwd is still needed) and a valid mfa token, then users don't need to do mfa authentication again.
What this pr does:
1. Add a new authenticator USERNAME_PASSWORD_MFA. CLIENT_REQUEST_MFA_TOKEN parameter is added.
2. Support both ID_TOKEN and MFATOKEN in Local Secure Storage.
3. Change the way we name local cache of ID_TOKEN
4. Change the SecureStorageLinuxManager to …

SNOW-175899: Username pwd mfa token cache

---

src/test/java/net/snowflake/client/jdbc/telemetryOOB/TelemetryServiceIT.java

There is some unexpected behavior with SSM regex password matching, causing these 2 tests to generate a failure with their log output. Ignoring them in Jenkins while we investigate this.
Created https://snowflakecomputing.atlassian.net/browse/SNOW-232702 for investigating regex.

SNOW-232411 ignoring OOB tests until we investigate SSM further

---

src/main/java/net/snowflake/client/core/HttpUtil.java

A few customers using connection pooling applications are experiencing issues related to expired connections that continue to sit in the pool after the connection to the cloud (Azure, GCP, etc) has marked them as expired. For these customers, we have provided custom jars with the "time to live" parameter exposed, which controls how long a connection can stay alive in the pool while unused. There have been several requests to expose this setting in GA with a jvm parameter.
I think this is a good idea because it will reduce the number of custom jars being sent and I don't see any security implications.
The time to live parameter can be configured with the jvm param **net.snowflake.jdbc.ttl**.

SNOW-213443 SNOW-206549

---

CHANGELOG.rst

Description
Remove the reference to the change that adds support for MFA token caching.
This feature isn't available to customers yet, so it's not useful for customers to know that the
driver supports this feature.

SNOW-173219 Remove the reference to the change that adds support for MFA token caching

---

src/main/java/net/snowflake/client/jdbc/SnowflakeBaseResultSet.java
src/test/java/net/snowflake/client/jdbc/ResultSetLatestIT.java

When getCharacterStream() calls getString(), a nullptrexception is thrown when the string returns a null value. That has been fixed by checking for null after getString() is called.

SNOW-255552 fix nullptrexception in ResultSet.getCharacterStream

---

src/main/java/net/snowflake/client/core/ResultUtil.java
src/main/java/net/snowflake/client/loader/ProcessQueue.java
src/test/java/net/snowflake/client/jdbc/ConnectionIT.java

This function throws an exception when a COPY type of statement is made and the number of rows altered is greater than INT_MAX. This is because the updateCount variable calls ResultSet#getInt(), which overflows. The solution is to have it call ResultSet#getLong() instead so no overflow is reached.
This is locally reproducible and the change works with manual testing. However, it is not feasible to add a test case because this only happens with statements of type COPY and for more than INT_MAX rows copied, which takes about an hour to run each time.

SNOW-250222 Fix integer overflow problem within calculateUpdateCount function

---

FIPS/pom.xml
FIPS/public_pom.xml
pom.xml
public_pom.xml
src/main/java/net/snowflake/client/core/CredentialManager.java
src/main/java/net/snowflake/client/core/SessionUtil.java

[Latest Update]
Now we will catch the `NoClassDefFoundError` and use `logger.info` to send out the msg. If the error is catched, then we fall back to normal process.
[Original description]
Make JNA as an optional dependency.
Question, how do we want to deal with FIPS version?

SNOW-180954 make jna lib optional dep

---

src/main/java/net/snowflake/client/core/ResultUtil.java
src/test/java/net/snowflake/client/jdbc/ResultSetIT.java
src/test/java/net/snowflake/client/jdbc/ResultSetMultiTimeZoneIT.java

Dates can be fetched with the getString() function and are fetched with their session offset in string form. They are then returned as strings by the JVM with no session offset. Currently, there is a bug where dates fetched with getString() are returned with an offset between UTC time and the JVM timezone. The dates should just be returned as the string values that they are with no offset. This change corrects that bug.

SNOW-251457 change timezone formatter to default timezone instead of utc

---

src/main/java/net/snowflake/client/jdbc/SnowflakeSQLLoggedException.java

We throw SQLFeatureNotSupportedExceptions for any JDBC API call that we do not currently support. We track these exceptions via client telemetry and display the failures on our telemetry dashboard. 
We now want to be able to sort our SQLFeatureNotSupportedExceptions by which function threw the exception on the telemetry dashboard. It's difficult to dig through the stacktrace to find it. So I am adding a "reason" field for these exceptions that details which function has thrown it.

SNOW-272337 Add reason to SQLFeatureNotSupportedExceptions

---

src/main/java/net/snowflake/client/jdbc/SnowflakeFileTransferAgent.java
src/test/java/net/snowflake/client/jdbc/SnowflakeDriverIT.java
src/test/java/net/snowflake/client/jdbc/SnowflakeDriverLatestIT.java

This PR is so the JDBC driver can read the put threshold value from the server side. This isn't affected by all the server-side threshold reverts. GS is still able to to send threshold data to the driver regardless.

SNOW-136474 Adjustable file threshold for put in jdbc

---

src/main/java/net/snowflake/client/core/SFArrowResultSet.java
src/main/java/net/snowflake/client/core/SFBaseStatement.java
src/main/java/net/snowflake/client/core/SFResultSet.java
src/main/java/net/snowflake/client/core/SFResultSetFactory.java
src/main/java/net/snowflake/client/core/SFSession.java
src/main/java/net/snowflake/client/core/SFStatement.java
src/main/java/net/snowflake/client/jdbc/DefaultSFConnectionHandler.java
src/main/java/net/snowflake/client/jdbc/SFConnectionHandler.java
src/main/java/net/snowflake/client/jdbc/SnowflakeConnectionV1.java
src/main/java/net/snowflake/client/jdbc/SnowflakePreparedStatementV1.java
src/main/java/net/snowflake/client/jdbc/SnowflakeStatementV1.java
src/test/java/net/snowflake/client/jdbc/MockConnectionTest.java

This PR introduces the second piece of the refactor for SNOW-256737, which contains the abstract class for `SFStatement`s, `SFBaseStatement`.
For more details, see explanations here.
Note that due to a Github Actions hanging issue, this PR is merging into `session_only`, so the diffs introduced by this set of changes can be reviewed without the diffs of the unmerged `session_only` branch.

SNOW-256737 Continued: Introduced SFBaseStatement

---

src/main/java/net/snowflake/client/core/SFJsonResultSet.java
src/test/java/net/snowflake/client/jdbc/ResultSetJsonVsArrowIT.java
src/test/java/net/snowflake/client/jdbc/ResultSetLatestIT.java

getObject() called getLong() in JSON for numbers of type BIGINT. Sometimes the numbers were too large for a type long to hold, resulting in an exception. getObject() now calls getBigDecimal() for type BIGINT to avoid this problem. In Arrow format, this was already the case.

SNOW-165204 Fix exception thrown by calling getObject() on very large number

---

src/main/java/net/snowflake/client/jdbc/SnowflakeBaseResultSet.java
src/main/java/net/snowflake/client/jdbc/SnowflakeResultSetV1.java

These classes, as part of the new `SFConnectionHandler` interface, need public visibility for outside packages to implement and use them.

Make SnowflakeBaseResultSet and SnowflakeResultSetV1 Public Classes

---

src/main/java/net/snowflake/client/jdbc/SnowflakeDatabaseMetaData.java

With this change, the original parameters for the DatabaseMetadata get API calls remain unaltered when used in the telemetry message. This will show which parameters have their wildcards escaped.
This fixes the bug where the escape characters were stripped from the parameters prior to them being passed into the telemetry message.

SNOW-274293 Fix telemetry message to show escaped characters

---

src/test/java/net/snowflake/client/jdbc/DatabaseMetaDataInternalLatestIT.java

Fixes BPTP failure. Someone pushed a server-side change that altered the number of functions in the Jenkins test account, which then caused this unit test to fail because it counted the number of function columns returned.

SNOW-285142 alter failing test due to account changes

---

src/main/java/net/snowflake/client/core/SFBaseSession.java
src/main/java/net/snowflake/client/core/SFSession.java
src/main/java/net/snowflake/client/core/SessionUtil.java
src/main/java/net/snowflake/client/jdbc/SFAsyncResultSet.java
src/test/java/net/snowflake/client/jdbc/ConnectionIT.java
src/test/java/net/snowflake/client/jdbc/ConnectionLatestIT.java
src/test/java/net/snowflake/client/jdbc/HeartbeatAsyncLatestIT.java
src/test/java/net/snowflake/client/jdbc/HeartbeatIT.java

A customer's issue with session token expiring exposed 2 bugs:
1. ResultSet#getQueryStatus() function did not contain any logic to renew the session token when GS sent back an error saying the session had expired. It simply threw a SQLException. This change adds in a retry to renew the session. This error should now not occur at all when the session token heartbeat is enabled.
2. The parameter value CLIENT_SESSION_KEEP_ALIVE_HEARTBEAT_FREQUENCY could be set by the user, but the value was not actually propagated to the scheduleHeartbeat() function. This means the heartbeats were always 3600 seconds apart, in spite of the fact that the frequency should be able to be changed (within range of 900 to 3600). Now, the heartbeat can actually be changed.

SNOW-281822 Fix session token expiry and heartbeat frequency settings

---

pom.xml
src/main/java/net/snowflake/client/core/SFBaseResultSet.java
src/main/java/net/snowflake/client/core/SFStatementMetaData.java
src/main/java/net/snowflake/client/jdbc/SFBaseFileTransferAgent.java
src/main/java/net/snowflake/client/jdbc/SnowflakeConnectionV1.java

SNOW-291736 Minor API changes for java stored procs 
1. Made the constructor of `SFStatementMetadata` public so it can be used by Stored Procs implementation.
2. Set the destination stage path for uploadStream in the `FileTransferAgent` object  so that it can be used by Stored Procs implementation.

SNOW-291736 Minor API changes for java stored procs

---

pom.xml

This is to fix the whitesource vulnerability from an earlier jackson version.

SNOW-290669 fix jacksonbind whitesource vulnerability

---

src/main/java/net/snowflake/client/jdbc/SnowflakeChunkDownloader.java
src/test/java/net/snowflake/client/jdbc/ConnectionLatestIT.java
src/test/java/net/snowflake/client/jdbc/ResultSetLatestIT.java

The Denodo application issues a Thread.interrupt() after cancelling statements. This led to the discovery that when an InterruptedException occurs, the JDBC driver simply throws an exception but does not clear available memory that is being used. 
This code change moves the memory-freeing code into a **finally** block so that it executes regardless of whether an interrupt happens or not. 
The test case injects a fake interrupt exception into the terminate() function and tests that all memory is released when the exception is caught.

SNOW-258666 Clean up memory chunks after thread is interrupted

---

CHANGELOG.rst
FIPS/pom.xml
pom.xml

* SNOW-294002: Bumped up the Client PATCH version from 3.13.0 to 3.13.1

Snow 294002 jdbc version bump to 3.13.1 

---

Jenkinsfile
src/test/java/net/snowflake/client/jdbc/SnowflakeDriverIT.java

Adding new test job for code coverage on PRs. Coupled with a change Ankit made to the Jenkins configuration, this will allow us to see code coverage on PRs before they are merged. This way we can monitor code coverage proactively and add tests to maintain current coverage levels before merging to master.
This also conditionally ignores a test that's been flaky on GithubActions.

SNOW-266144 added new code coverage test job and params to JDBC PC jobs

---

src/main/java/net/snowflake/client/core/SFBaseSession.java
src/main/java/net/snowflake/client/core/SessionUtil.java

SNOW-330467 Snowpark need to read some parameters from server's response. So we want JDBC to surface those parameters. It is not very elegant to add a getter and a setter for each Snowpark parameters, as they are Snowpark specific and JDBC won't be using them. So added a HashMap for Snowpark to get its parameters.

SNOW-330467 Added other parameters map to session for Snowpark to read

---

src/main/java/net/snowflake/client/core/SFArrowResultSet.java
src/test/java/net/snowflake/client/jdbc/ResultSetLatestIT.java

SNOW-334161
There is a function getBigDecimal(int colIndex, int scale) that throws a NullPointerException when the BigDecimal value is null and Arrow format is used. This change checks for null and returns the null value rather than throwing an exception when .setScale() is called.

SNOW-334161 fixing nullptrexception in Arrow getBigDecimal function

---

src/main/java/net/snowflake/client/core/SFBaseSession.java
src/main/java/net/snowflake/client/core/SessionUtil.java
src/main/java/net/snowflake/client/jdbc/cloud/storage/SnowflakeS3Client.java
src/test/java/net/snowflake/client/jdbc/SnowflakeDriverIT.java

SNOW-299374
When the parameter FORCE_REGIONAL_S3_ENDPOINTS_FOR_PRESIGNED_URLS is set to true then invoke a different API to generate S3 url. 
This does NOT break any existing customers. The above parameter will be set true to private link parameters in the AWS us-east-1 regions.

use s3 regional url when parameter is set

---

src/test/java/net/snowflake/client/jdbc/HeartbeatAsyncLatestIT.java

SNOW-331319
Often this test fails because it asserts that the query status should be SUCCESS, but GS can take a really long time to run so sometimes the query status is RUNNING instead. This change should fix the flakiness by 1.) Shortening the query runtime so it's more likely to be done, and 2.) Implementing a retry if the query is still running.

SNOW-331319 Fix flaky async test

---

src/main/java/net/snowflake/client/core/SFBaseSession.java
src/main/java/net/snowflake/client/core/SessionUtil.java
src/main/java/net/snowflake/client/jdbc/SnowflakeFileTransferConfig.java
src/main/java/net/snowflake/client/jdbc/cloud/storage/SnowflakeS3Client.java
src/main/java/net/snowflake/client/jdbc/cloud/storage/StageInfo.java
src/main/java/net/snowflake/client/jdbc/cloud/storage/StorageClientFactory.java
src/test/java/net/snowflake/client/AbstractDriverIT.java
src/test/java/net/snowflake/client/jdbc/SnowflakeDriverLatestIT.java

When the parameter ENABLE_STAGE_S3_PRIVATELINK_FOR_US_EAST_1 is set to true then driver invokes a different API to generate S3 regional url.
This does NOT break any existing customers. The above parameter will be set true to private link parameters in the AWS us-east-1 regions.
SNOW-299374

generate aws s3 regional urls when a param is set

---

src/main/java/net/snowflake/client/jdbc/ChunkDownloadContext.java
src/main/java/net/snowflake/client/jdbc/DefaultResultStreamProvider.java
src/main/java/net/snowflake/client/jdbc/ResultStreamProvider.java
src/main/java/net/snowflake/client/jdbc/SnowflakeChunkDownloader.java
src/main/java/net/snowflake/client/jdbc/SnowflakeResultSetSerializableV1.java

This PR is a refactor of `SnowflakeChunkDownloader` that enables supplying a custom `ResultStreamProvider` object that abstracts out the logic of converting between result-chunk metadata and a data stream (`InputStream`). This is needed for supporting result-file reads in stored procedures.
@sfc-gh-mrui I added you to this review because this touches `SnowflakeResultSetSerializableV1`. I think you added this class as a means to support partitioning within the Spark Connector, so PTAL also to make sure these changes don't screw anything up in that class, and that they will also work with the Spark Connector.

SNOW-343696: Create a ResultStreamProvider class to allow for overriding source of data streams for result chunks

---

src/main/java/net/snowflake/client/jdbc/SnowflakeFileTransferAgent.java
src/test/java/net/snowflake/client/jdbc/FileUploaderSessionlessTest.java

SNOW-348866
Allows clients to pass in data from a PUT command for file upload without creating a Snowflake session.

SNOW-348866 Expose PUT metadata parsing for sessionless PUT

---

src/main/java/net/snowflake/client/core/SessionUtil.java
src/test/java/net/snowflake/client/core/SessionUtilTest.java
src/test/java/net/snowflake/client/jdbc/MockConnectionTest.java

SNOW-330467 Fix a typo in setOtherParameter's logic.

SNOW-330467 Fix typo in setOtherParameter's logic

---

src/main/java/net/snowflake/client/core/Constants.java
src/main/java/net/snowflake/client/jdbc/cloud/storage/SnowflakeAzureClient.java
src/main/java/net/snowflake/client/jdbc/cloud/storage/SnowflakeGCSClient.java
src/main/java/net/snowflake/client/jdbc/cloud/storage/SnowflakeS3Client.java
src/test/java/net/snowflake/client/jdbc/SnowflakeGcsClientHandleExceptionLatestIT.java

SNOW-350701
Sessionless file uploads cannot renew their credentials if they expire.  Currently we throw a NPE trying if we try to renew tokens for sessionless upload.  This PR updates the logic to throw an ExpiredToken error instead if the session is null

SNOW-250701 Do not try to renew cloud storage tokens if the session is null

---

src/test/java/net/snowflake/client/jdbc/DatabaseMetaDataInternalIT.java
src/test/java/net/snowflake/client/jdbc/MultiStatementIT.java

SNOW-357353
Due to a GS-side change, current_account() returns the alias of the account name now instead of the actual account. current_account_locator() does what we want instead.

SNOW-357353 JDBC portion- change current_account() to current_account_locator()

---

src/main/java/net/snowflake/client/core/HttpUtil.java
src/test/java/net/snowflake/client/core/SessionUtilTest.java

SNOW-369447
Customer request to make these values configurable. They now are with JVM parameters.

SNOW-369447 Make MAX_CONNECTIONS and MAX_CONNECTIONS_PER_ROUTE changeable

---

src/main/java/net/snowflake/client/jdbc/SnowflakeDriver.java
src/test/java/net/snowflake/client/jdbc/SnowflakeDriverLatestIT.java

SNOW-373633
Hey @sfc-gh-abhatnagar, we would like to make the version string for JDBC a static value to avoid an issue with version retrieval when customers use the source jar vs a compiled jar. This change would require the version to now be changed in 2 places instead of 1- the` implementVersion` static string in SnowflakeDriver.java as well as in the pom.xml file. Is this okay with you?

SNOW-373633 Change JDBC version to be taken from static string instead of version.properties

---

Jenkinsfile

SNOW-359277
run semgrep in temp dir to prevent potential issue of .git folder ownership being changed to root
also use new baseline ref parameter to stop reporting issue in upstream branch since current branch was created
- [] This change has passed precommit
- [] I have reviewed code coverage report for my PR in  ([Sonarqube](https://sonarqube.int.snowflakecomputing.com/project/branches?id=snowflake-jdbc))

run semgrep in temp dir and use new baseline ref

---

src/main/java/net/snowflake/client/jdbc/SnowflakeSQLLoggedException.java
src/main/java/net/snowflake/client/jdbc/telemetry/NoOpTelemetryClient.java
src/main/java/net/snowflake/client/jdbc/telemetry/Telemetry.java
src/main/java/net/snowflake/client/jdbc/telemetry/TelemetryClient.java
src/test/java/net/snowflake/client/jdbc/MockConnectionTest.java

Cleanly send a shutdown signal to the `ExecutorService` responsible for in-band telemetry uploads.

Add shutdown() to the ExecutorService in sendTelemetryClient

---

.github/pull_request_template.md

SNOW-405374
Non-snowflake github users sometimes create PRs that go unnoticed because they have not created a linked github issue. Changing the template to tell them to create a github issue should fix the workflow.

SNOW-405374 Add questions to PR template for external pull request creators

---

src/main/java/net/snowflake/client/jdbc/SnowflakeConnectString.java
src/test/java/net/snowflake/client/jdbc/ConnectionIT.java

SNOW-394504
JDBC libraries do not support having underscores in account names, even though Snowflake GS is able to support this. After talking to Dennis (slack conversation here: [https://snowflake.slack.com/archives/C0292U1LEQP/p1628032200020600](https://snowflake.slack.com/archives/C0292U1LEQP/p1628032200020600)), it turns out there is GS support to handle the underscore-to-hyphen switch for both old and new account formats. So replacing all account underscores with hyphens in JDBC will fix the JDBC underscore issue.
Fixes #NNNN 
3. Please describe how your code …

SNOW-394504 Fix underscore issue in JDBC by replacing all underscores with hyphens in account names

---

src/main/java/net/snowflake/client/jdbc/SnowflakeConnectionV1.java
src/test/java/net/snowflake/client/jdbc/HeartbeatAsyncLatestIT.java

SNOW-449297
Snowflake's implementation of Connection.isValid() returns true whenever the connection is not closed, even if the connection is no longer able to connect due to an invalid/expired session. This fixes the behavior so isValid() only returns true whenever the session is not closed and not expired. Documentation for isValid:https://docs.oracle.com/javase/8/docs/api/java/sql/Connection.html#isValid-int-
Fixes #NNNN 

SNOW-449297 Fix implementation of Connection.isValid()

---

src/main/java/net/snowflake/client/jdbc/SnowflakeFileTransferAgent.java
src/main/java/net/snowflake/client/jdbc/cloud/storage/AzureObjectSummariesIterator.java

SNOW-464020
Basically, JDBC PUT command running against Azure fails intermittently. And it seems like the reason is azure object iterator's apis do some lazy work, e.g., azureIterator.hasNext() needs to connect to Azure instead of just a local operation. In this case, these apis may generate StorageException because of expired SAS token.
This pr is to add a retry logic to wrap the iterator enumeration.
Fixes #NNNN 

SNOW-464020: Azure iterator error handling

---

src/main/java/net/snowflake/client/core/SFFixedViewResultSet.java
src/main/java/net/snowflake/client/jdbc/SnowflakeFileTransferAgent.java
src/test/java/net/snowflake/client/jdbc/ConnectionLatestIT.java

SNOW-412040
PUT/GET statements are not supported for asynchronous querying execution, but some customers still want to use the framework of asynchronous resultsets so that they can get back the query IDs of their PUT or GET queries.
Currently, no query IDs are returned for PUT or GET statements. This PR fixes that. If there is a batch of PUT statements in 1 ResultSet (for example, using a put statement with wildcards), the query ID returned is the last query ID in the batch of statements.
Fixes #NNNN 
Please …

SNOW-412040 Fix ResultSet.getQueryID() so it returns correct query ID for PUT/GET statements

---

src/main/java/net/snowflake/client/jdbc/SnowflakeFileTransferAgent.java

SNOW-464020
The previous pr only wraps `compareAndSkipRemoteFiles` with a do-while retry loop. But it didn't work well. After checking the source code of azure-storage v5.0.0, it seems we need to regenerate the iterator from azure-client object. So in this pr, we move `compareAndSkipRemoteFiles` up into the do-while retry loop of `storageClient.listObjects`. If the SAS token expires, the `storageClient` will be refreshed, i.e., having a fresh new SAS token, then the returned `objectSummaries` will also contain the new SAS.
Fixes #NNNN 
3. Please describe how your code …

SNOW-464020: azure iterator exception bug fix

---

src/main/java/net/snowflake/client/core/arrow/ArrowResultUtil.java
src/test/java/net/snowflake/client/jdbc/ResultSetMultiTimeZoneLatestIT.java

SNOW-366563
A customer is having an issue where due to logic in the function ArrowUtil.moveToTimeZoneOffset(), the daylight savings appears wrong for London timezone because it's the same offset as UTC most, but not all, of the time.
Fixes #NNNN 

SNOW-366563 Fix London/Europe daylight savings offset with timestamp_ntz

---

src/main/java/net/snowflake/client/jdbc/cloud/storage/SnowflakeAzureClient.java
src/test/java/net/snowflake/client/jdbc/cloud/storage/SnowflakeAzureClientTest.java

SNOW-466639
Currently JDBC failed to log StorageExceptionExtendedInformation correctly. It's something like `Extended error info=net.snowflake.client.jdbc.internal.microsoft.azure.storage.StorageExtendedErrorInformation@408e96d9`. This pr is to  fix the issue.
Fixes #NNNN 

SNOW-466639: Fix logging StorageExceptionExtendedInformation

---

src/main/java/net/snowflake/client/jdbc/SFAsyncResultSet.java
src/test/java/net/snowflake/client/jdbc/ResultSetAsyncIT.java
src/test/java/net/snowflake/client/jdbc/SnowflakeResultSetSerializableIT.java

SNOW-411516
`SnowflakeResultSet.getResultSetSerializables(Long)` is an API for Spark Connector.
It is disabled for `SFAsyncResultSet` when developing this feature because it is not necessary at that time.
This PR is enable it for `SFAsyncResultSet`. The implementation is:
1. Call getRealResult() to wait for the real result is ready.
2. Call resultSetForNext.getResultSetSerializables() to get the result.

SNOW-411516 Support SFAsyncResultSet.getResultSetSerializables(Long)

---

src/main/java/net/snowflake/client/core/SFBaseStatement.java
src/main/java/net/snowflake/client/core/SFStatement.java
src/main/java/net/snowflake/client/jdbc/SnowflakeConnectionV1.java
src/main/java/net/snowflake/client/jdbc/SnowflakeStatementV1.java
src/test/java/net/snowflake/client/jdbc/ConnectionLatestIT.java
src/test/java/net/snowflake/client/jdbc/MockConnectionTest.java

SNOW-472364
Add below function to SnowflakeConnectionV1 to get child query ID for multiple statements query.
`public String[] getChildQueryIds(String queryID) throws SQLException
`
In general, we have the query ID for the multiple statements. We can use `StmtUtil.getQueryResultJSON(String queryId, SFSession session)` to get the JsonResult. And then we can parse out the query IDs from it.
Design doc is https://docs.google.com/document/d/19CysvhnivP8KLmRBo7U9-N1ILk51YCB5GCu_H0Rp4RA/edit#heading=h.74dz4sbkqqz8

SNOW-472364 Add API to get query IDs for multi statements

---

src/main/java/net/snowflake/client/core/arrow/IntToTimeConverter.java
src/test/java/net/snowflake/client/jdbc/ResultSetLatestIT.java
src/test/java/net/snowflake/client/jdbc/ResultSetMultiTimeZoneLatestIT.java

SNOW-473749
This is a PR to fix a bug where calling getTimestamp() on a Time object with precision of 3 or under in Arrow format didn't honor the session parameter USE_SESSION_TIMEZONE to display wallclock time.
Fixes #NNNN 

SNOW-473749 Fix bug where time(3) objects weren't honoring USE_SESSION_TIMEZONE when called with getTimestamp() in Arrow format

---

src/main/java/net/snowflake/client/core/SFBaseSession.java
src/main/java/net/snowflake/client/jdbc/SnowflakeUtil.java
src/test/java/net/snowflake/client/jdbc/CustomProxyLatestIT.java

SNOW-500624
When setting properties via the JVM, the http proxy properties were not passed along to the AzureClient or S3Clients, which means http proxies set via JVM were not used for PUT/GET. The fix for this is to pass the JVM properties to the driver, which then sets the proxy properties.
This fix was already made for https proxies, but not for http proxies.
Fixes #NNNN 

SNOW-500624 JVM http proxy properties do not work for PUT/GET

---

FIPS/pom.xml
pom.xml

SNOW-513708 Update gson whitesource vulnerability. Library is never used so I just excluded it.
I tested GCP PUT/GET and streaming manually with this change to double-check. Gson is a 3rd-level dependency (dependency of a dependency of a dependency), and upgrading the main dependency to update the gson version leads to adding about 6 more dependencies to the main jar that are not actually needed. So the best action is to just exclude this unused gson library.
Fixes #NNNN 
Please write a short description of …

SNOW-513708

---

src/main/java/net/snowflake/client/jdbc/SnowflakeConnectString.java

Description
Account names were incorrectly updated to replace underscores with hyphens. Host names on the contrary were not updated. This PR fixes the account names and updates host names to not have underscores in them.
Testing
Manually tested to confirm that both global URLs and URLs with underscores in them are correctly updated with no impact on account names.
SNOW-521194
Fixes #NNNN 

SNOW-521194 Fix account name breakage and update host url

---

src/main/java/net/snowflake/client/jdbc/SnowflakeFileTransferAgent.java
src/test/java/net/snowflake/client/jdbc/FileUploaderLatestIT.java
src/test/java/net/snowflake/client/jdbc/FileUploaderSessionlessTest.java

Description
Kafka connector depends on stageInfo to be updated for it to perform sessionless
"blind" put to stages. JDBC driver was not udpating the stageInfo instance with
s3RegionalURL related information. KC would hence skip using s3regionalURL even
if it was explicitly requested via backend param.
Testing
SNOW-520660
Fixes #NNNN 

SNOW-520660 Fix for S3 Regional URL not being updated in stageInfo

---

src/main/java/net/snowflake/client/core/SFBaseSession.java
src/main/java/net/snowflake/client/core/SFSession.java
src/main/java/net/snowflake/client/jdbc/DefaultSFConnectionHandler.java
src/main/java/net/snowflake/client/jdbc/SnowflakeChunkDownloader.java
src/main/java/net/snowflake/client/jdbc/SnowflakeFileTransferAgent.java
src/main/java/net/snowflake/client/jdbc/SnowflakeFileTransferConfig.java
src/main/java/net/snowflake/client/jdbc/cloud/storage/SnowflakeAzureClient.java
src/main/java/net/snowflake/client/jdbc/cloud/storage/SnowflakeGCSClient.java
src/main/java/net/snowflake/client/jdbc/cloud/storage/SnowflakeS3Client.java
src/main/java/net/snowflake/client/jdbc/cloud/storage/SnowflakeStorageClient.java
src/test/java/net/snowflake/client/jdbc/ConnectionLatestIT.java
src/test/java/net/snowflake/client/jdbc/DatabaseMetaDataInternalIT.java
src/test/java/net/snowflake/client/jdbc/ResultSetMultiTimeZoneLatestIT.java
src/test/java/net/snowflake/client/jdbc/SnowflakeDriverLatestIT.java

SNOW-524708
Adding streaming ingest client name and client key as part of the file metadata to support per client streaming ingest billing. 
Two things to note:
1. This PR contains a few changes made by automatic google java format
2. I spent a long time trying to add a test for GCP but failed, it always complains about no permission access stage object (errors below), let me know if you know how to fix it (i believe the problem is related to presigned URL)
`net.snowflake.client.jdbc.cloud.storage.StorageProviderException: com.google.cloud.storage.StorageException: Anonymous caller does not have storage.objects.get access to the Google Cloud Storage object
`
1. What GitHub issue is this PR adressing? Make sure …

SNOW-524708: Adding streaming ingest related metadata for streaming ingest billing

---

src/main/java/net/snowflake/client/jdbc/SnowflakeDatabaseMetaData.java
src/test/java/net/snowflake/client/jdbc/DatabaseMetaDataIT.java
src/test/java/net/snowflake/client/jdbc/DatabaseMetaDataLatestIT.java

SNOW-475617 SNOW-494684
This PR addresses 2 customer bugs:
1. Customers are attempting call getTables() and getColumns() with a schema that contains double quotes inside the name (for example, a name such as TEST_SCHEMA_"WITH_QHOTES"). This should be supported, but empty results were coming back for double quoted schemas. Now, that is fixed.
2. Customers were attempting to call getProcedureColumns() with a schema input containing wildcards (for example, a name like TEST%). Empty results were being returned there also. This is now fixed so getProcedureColumns() supports wildcards in the schema name.
Fixes #NNNN 
2. …

SNOW-475617 SNOW-494684 Fix DatabaseMetadata bugs -double quotes and wildcards

---

src/main/java/net/snowflake/client/core/SFBaseStatement.java
src/main/java/net/snowflake/client/core/SFStatement.java
src/main/java/net/snowflake/client/jdbc/SFBaseFileTransferAgent.java
src/main/java/net/snowflake/client/jdbc/SnowflakeFileTransferAgent.java

SNOW-414125
Making a few refactors to avoid duplication in jdbc-stored-procs
- Refactor the upload/download command facade classes and their related code from `SnowflakeFileTransferAgent` into `SFBaseFileTransferAgent`.
- Refactor `SFStatement.isFileTransfer` into `SFBaseStatement`.
Fixes #NNNN 

SNOW-414125 Refactor for stored proc put support

---

src/main/java/net/snowflake/client/jdbc/SnowflakeChunkDownloader.java
src/test/java/net/snowflake/client/jdbc/ResultSetLatestIT.java

SNOW-540172 
Two changes:
1. Reduced test time of testChunkDownloaderSetRetry from 20 minutes to 40 seconds. Total run time reduced from 1.5 hours to 1 hour.
2. Only when prefetch fails due to internal memory limitation, nextChunkToDownload equals nextChunkToConsume. In that case we need to increment nextChunkToDownload. For all other cases we want to follow the old JDBC path to not increase the value of nextChunkToDownload.
Fixes #NNNN 
Please write a short description of how your code change solves the …

SNOW-540172 Reduce test execution time

---

src/main/java/net/snowflake/client/jdbc/SnowflakeDriver.java

SNOW-538708
There is a bug with the current solution to depress illegal access warning.
Follow the repro steps mentioned in the ticket (https://github.com/oracle/graal/issues/4149 ) with the new jdbc jar, the test can finish successfully.
```
+ : Running native app
+ echo '[INFO] Running native app'
[INFO] Running native app
+ ./target/graalvm-segfault-bug
com.snowflake.client.jdbc.SnowflakeDriver@2d9d3270       <<< the correct output instead of getting a segfault
```
Also verified that the new logic can still depress the illegal access warning by running arrow result set IT.
Fixes #NNNN 
2. Fill out the following …

SNOW-538708: Unsafe warning segfault

---

src/main/java/net/snowflake/client/core/SFSessionProperty.java
src/main/java/net/snowflake/client/jdbc/SnowflakeConnectString.java
src/test/java/net/snowflake/client/jdbc/ConnectStringParseTest.java
src/test/java/net/snowflake/client/jdbc/SnowflakeDriverTest.java

Description
Introduced a parameter to control whether or not to have underscores in host.
Always check if the hostname has to be updated whether account name is set or not.
Testing
Added unit test for parsing logic.
SNOW-XXXXX
Fixes #NNNN 

SNOW-544896 Regionless URL support in JDBC Driver

---

src/main/java/net/snowflake/client/jdbc/SnowflakeConnectionV1.java
src/test/java/net/snowflake/client/jdbc/ConnectionIT.java
src/test/java/net/snowflake/client/jdbc/ConnectionLatestIT.java

SNOW-XXXXX
Fixes #NNNN 
A customer is using the jdbc driver with an application which calls the JDBC setReadOnly method. They are getting an exception since the driver does not support the method. This change is to log a message instead of throw an exception when setReadOnly is called so we can ignore it.

setReadOnly() is unsupported

---

src/main/java/net/snowflake/client/jdbc/SnowflakeDatabaseMetaData.java
src/test/java/net/snowflake/client/jdbc/DatabaseMetaDataLatestIT.java

SNOW-263598
Fixes [#432  ](https://github.com/snowflakedb/snowflake-jdbc/issues/432)
Some users are trying to integrate the driver with Collibra application which adds double quotes around database name for getSchemas() function. The driver also adds quotes around the database name, which was leading to is being double quoted and returning empty result sets. This change will only add quotes to the database name if the application hasn't done so first.

Fix issue where database name is double quoted in catalog function

---

src/test/java/net/snowflake/client/jdbc/PreparedStatement2LatestIT.java

SNOW-558738
It looks like this line does not relate to the behavior which the test is verifying. Adding more binds than bind variables will cause an exception going forward.
Fixes #NNNN 

Remove unnecessary line from bind test

---

FIPS/src/test/java/net/snowflake/client/jdbc/ConnectionFipsIT.java
src/main/java/net/snowflake/client/jdbc/SnowflakeDatabaseMetaData.java
src/test/java/net/snowflake/client/jdbc/DatabaseMetaDataLatestIT.java

SNOW-571607
getSchemas() should allow databases with double quotes in the name. To query a database without quotes, the application should refrain from including extra quotes around the database name because doing so will produce no results.
Fixes #NNNN 

SNOW-571607  Create patch for driver release v3.13.16 to fix incorrect behavior for getSchemas() function

---

FIPS/src/test/java/net/snowflake/client/jdbc/ConnectionFipsIT.java
src/main/java/net/snowflake/client/jdbc/RestRequest.java
src/test/java/net/snowflake/client/jdbc/RestRequestTest.java

SNOW-577665
Bug fix. The bug was introduced in https://github.com/snowflakedb/snowflake-jdbc/pull/241/commits/6594bc47b8480333b151b75d2dce2a4f24792113
The `isNonRetryableHttpCode` function returns wrong value for 403 http code. Please look at RestRequestTest.java for correct behavior on 403.
Fixes #NNNN 

SNOW-577665: Wrong retry 403 logic

---

src/test/java/net/snowflake/client/AbstractDriverIT.java
src/test/java/net/snowflake/client/jdbc/SnowflakeResultSetSerializableIT.java

SNOW-579524
The test manually hacked the result chunk URL, which results in a dead loop on retry 403. The fix is adding networkTimeout in the test.
https://ci70.int.snowflakecomputing.com/job/RT-LanguageJDBC1-PC/1280/ running time has back to normal.
Fixes #NNNN 

SNOW-579524: Test negative with chunk file not exist taking too long

---

src/main/java/net/snowflake/client/core/SFStatement.java
src/test/java/net/snowflake/client/jdbc/PreparedStatement1LatestIT.java

Changing TIMESTAMP_INPUT_FORMAT could change the expected format for stage binding as well but the driver is using default format to generate the input file.
Set TIMESTAMP_INPUT_FORMAT to default value in parameters for the query request so the default format is always used for stage binding.
SNOW-XXXXX
Fixes #NNNN 

bug fix for stage binding with TIMESTAMP_INPUT_FORMAT

---

src/test/java/net/snowflake/client/jdbc/ConnectionWithOCSPModeIT.java

SNOW-591431
https://ci70.int.snowflakecomputing.com/job/RT-LanguageJDBC2-PC/1309/ is green, which contains `testWrongHost`
Fixes #NNNN 

SNOW-591431: Fix ocsp wrong host name test failure

---

src/main/java/net/snowflake/client/jdbc/cloud/storage/SnowflakeS3Client.java
src/test/java/net/snowflake/client/jdbc/ConnectionLatestIT.java

SNOW-XXXXX
Fixes #NNNN 
An issue was reported for downloadStreams() where the driver would hang for 5 minutes when trying to retry the downloading of a file from S3 that doesn't exist before throwing the file not found error. This change is to check whether the status code of AmazonServiceException is 404 and not retry if true.

Implement fast fail for Amazon S3 404 exception

---

src/main/java/net/snowflake/client/core/SFArrowResultSet.java
src/main/java/net/snowflake/client/jdbc/SnowflakeResultSetSerializableV1.java
src/test/java/net/snowflake/client/core/SFArrowResultSetIT.java

SNOW-XXXXX
Fixes #NNNN 
Snowflake backend returns query result in Arrow Format. Since Arrow format is in binary and it needs to be embedded in JSON message from GS, GS encodes the arrow format result set into Base64 format.
JDBC in order to process result first gathers some metadata about the result set - number of rows in the current chunk, for example. This happens before any processing on the data can happen. For this JDBC driver decodes the result set from base64 to arrow native, calculates the number of rows but then discards the decoded result set. While processing the result later it again decodes the arrow …

Remove double decoding on arrow result sets

---

src/main/java/net/snowflake/client/core/SessionUtil.java
src/test/java/net/snowflake/client/jdbc/SessionUtilTest.java

SNOW-573507 Supporting parsing otherParameters in JDBC
Initially JDBC only support parsing parameters defined in `SessionUtil.STRING_PARAMS`, `SessionUtil.INT_PARAMS` and `SessionUtil.BOOLEAN_PARAMS`. This is a limitation for Snowpark client because if we want to add a new server side parameter in for Snowpark client, we need to also change JDBC to recognize the new parameter.
As a result we added a new API in Session called getOtherParameter to get parameters that are not in the three lists. We had a PR to add support to that, https://github.com/snowflakedb/snowflake-jdbc/pull/474. But it is missing the change in getCommonParams. This PR will fix this issue. Without this PR, parameters that are not listed in `SessionUtil.STRING_PARAMS`, `SessionUtil.INT_PARAMS` and …

SNOW-573507 Supporting parsing otherParameters in JDBC

---

src/main/java/net/snowflake/client/jdbc/ArrowResultChunk.java

When using arrow format, the driver stores a 2-D array of arrow ValueVectors for each chunk. 
`private final ArrayList<List<ValueVector>> batchOfVectors;`
When freeData() is called on the chunk once it is no longer needed, the list of ValueVectors is cleared but the outer list of record batches is not. This is causing the memory to be retained in the heap and for larger datasets a 'java.lang.OutOfMemoryError: GC overhead limit exceeded' error can be thrown.
SNOW-XXXXX
Fixes #NNNN 
When freeData() is called on …

Clear batchOfVectors list when freeing chunk data to fix memory issue

---

src/main/java/net/snowflake/client/jdbc/DefaultSFConnectionHandler.java
src/main/java/net/snowflake/client/jdbc/SFAsyncResultSet.java
src/test/java/net/snowflake/client/jdbc/ResultSetAsyncITLatest.java
src/test/java/net/snowflake/client/jdbc/ResultSetAsyncLatestIT.java

Description provided in #1034 :
When calling the createResultSet method of the Snowflake connection to get the result of an async query, the Snowflake connection creates a statement for us, but there is no accessible reference to it, making it impossible to close.
https://github.com/snowflakedb/snowflake-jdbc/blob/master/src/main/java/net/snowflake/client/jdbc/SnowflakeConnectionV1.java#L169
ResultSet rs = sfConnectionHandler.createResultSet(queryID, createStatement());
This results in a memory leak in the connection's openStatement object, because this open statement will never be removed for as long as the connection stays opened.
SNOW-XXXXX
1. What GitHub issue is this PR adressing? Make sure that there is an …

Set statement for async result set to fix memory leak

---

src/main/java/net/snowflake/client/core/SFSession.java
src/main/java/net/snowflake/client/jdbc/cloud/storage/SnowflakeGCSClient.java

SNOW-500881 This is a fix for the previous PR https://github.com/snowflakedb/snowflake-jdbc/pull/715 for when the GCS client is session-less.
Fixes #NNNN 

SNOW-500881 Fix nullptr exception for sessionless GCS client

---

src/main/java/net/snowflake/client/jdbc/SnowflakePreparedStatementV1.java
src/test/java/net/snowflake/client/jdbc/PreparedStatement2LatestIT.java

When calling executeLargeBatch() for prepared statements, no rows were being inserted. 
Fixes #1006 
Add implementation for array binding with executeLargeBatch, similar to executeBatch(), for prepared statements.

Implement executeLargeBatch() for SnowflakePreparedStatementV1

---

src/main/java/net/snowflake/client/jdbc/SnowflakeDatabaseMetaData.java
src/test/java/net/snowflake/client/jdbc/DatabaseMetaDataIT.java

A customer is facing an issue where the application is calling getSQLStateType() while retrieving the database metadata. The current implementation throws a SnowflakeLoggedFeatureNotSupportedException. 
Fixes #NNNN 
The driver uses SQLState codes that are not listed under sqlStateXOpen, so return sqlStateSQL when getSQLStateType() is called.

Implement DatabaseMetadata.getSQLStateType()

---

src/main/java/net/snowflake/client/core/SFSession.java
src/test/java/net/snowflake/client/jdbc/ConnectionLatestIT.java

SNOW-XXXXX
Description from #1005 
enum QueryStatus has setErrorMessage and setErrorCode methods [ref](https://github.com/snowflakedb/snowflake-jdbc/blob/master/src/main/java/net/snowflake/client/core/QueryStatus.java#L48-L54) to put error message and error code.
Since Java's enum has single instance, if we change error message and error code these values will maintain permanently unless we call setErrorMessage and setErrorCode again.
Fixes #1005 
If the query status is not an error, set the error code and …

Reset query status error code and error message after error

---

src/main/java/net/snowflake/client/jdbc/SnowflakeType.java
src/test/java/net/snowflake/client/jdbc/ResultSetLatestIT.java

SNOW-XXXXX
Method getColumnClassName (for ResultSetMetaData object type) throws exception if the column type is TIMEZONETZ
Fixes #NNNN 
Add a case for TIMESTAMP_WITH_TIMEZONE to SnowflakeType.javaTypeToClassName()

fix getColumnClassName() for timestamp_tz column

---

src/main/java/net/snowflake/client/core/SFSession.java
src/main/java/net/snowflake/client/core/SFStatement.java
src/main/java/net/snowflake/client/core/StmtUtil.java
src/main/java/net/snowflake/client/jdbc/SFAsyncResultSet.java
src/test/java/net/snowflake/client/jdbc/ConnectionLatestIT.java
src/test/java/net/snowflake/client/jdbc/ResultSetAsyncLatestIT.java

SNOW-644887
Once async queries are added to the active async query list, they are not removed. With this PR, logic is added to the getStatus() function so that queries which are no longer running are removed from the active query list.
Note that since the queries are async, there is no way to remove queries from the active query list without first checking their status. **So the async query list will be out of date if no query status checking occurs.**
getQueryStatus() is called by SFSession.isSafeToClose(), and SFAsyncResultSet.getQueryStatus(queryId). Calling isSafeToClose() will iterate through all query IDs in the active async query list and remove queries that are not active. Calling SFAsyncResultSet.getQueryStatus(queryID) will only remove the query corresponding to its query ID if …

SNOW-644887 Remove inactive async queries from active query list

---

src/main/java/net/snowflake/client/jdbc/SnowflakeDatabaseMetaData.java
src/test/java/net/snowflake/client/jdbc/DatabaseMetaDataLatestIT.java

Overview from Snowflake support:
The customer is connecting to the Snowflake reader account via JDBC driver using their tool (name: Rhapsody). This tool performs schema discovery and calls the getProcedures() function when it establishes connectivity but since the Snowflake reader account doesn’t support it, it gets the error: “Operation not supported in Snowflake reader account”. Since this is failing the schema discovery process is getting interrupted.
SNOW-XXXXX
Fixes #NNNN 
This change will return an empty …

Return an empty resultset for getProcedures() when connected with a reader account

---

src/main/java/net/snowflake/client/jdbc/cloud/storage/SnowflakeAzureClient.java
src/test/java/net/snowflake/client/jdbc/SnowflakeDriverLatestIT.java

The Snowflake JDBC driver provides upload method that a customer is using to upload files to internal stages within their Azure Snowflake accounts. The JDBC driver has an internal threshold ("big file" threshold) defined as 200MB. 
For small files, we upload files in parallel, so we don't want the remote store uploader to upload parts in parallel for each file. For large files, we upload them in serial, and we want remote store uploader to upload parts in parallel for each file. This is the reason for the parallel value.
For files over 200MB the JDBC driver relies on the object store provider to do the splitting and parallel uploading, and that because Azure does not provide this capability, the result is that the JDBC driver serializes (does not parallelize) uploads for any files …

Use parallelism parameter for PUT/GET with Azure

---

pom.xml

NO-SNOW
We use Log4j for logging in my project. We could see the following messages in our logs:
```
May 30, 2022 3:18:59 PM net.snowflake.client.jdbc.internal.amazonaws.http.apache.client.impl.ApacheHttpClientFactory addProxyConfig
INFO: Configuring Proxy. Proxy Host: some.proxy Proxy Port: 8080
```
Our initial thought was that we need to set up appropriate log level for `net.snowflake.client.jdbc.internal.amazonaws.http.apache.client.impl.ApacheHttpClientFactory` but it did not work. This class uses shaded Apache Commons Logging (JCL) as logging abstraction, supporting Log4j as logging implementation. The issue …

Fix excessive logging by allowing commons-logging (JCL) to initialize Log4j properly.

---

pom.xml

SNOW-676071 Snyk PR accidentally upgraded httpclient version but this will cause certain customers using S3 to be unable to connect.
Fixes #NNNN 

SNOW-676071 Revert whitesource upgrade to avoid customer regression

---

src/main/java/net/snowflake/client/jdbc/SnowflakeConnectString.java

Add log warnings for each of the error return paths of `SnowflakeConnectString.parse`.
Fixes https://github.com/snowflakedb/snowflake-jdbc/issues/1165
This code adds additional logging for each of the error return paths of `SnowflakeConnectString.parse`.  This helps users who see the errors determine what is wrong with their provided connection string.

Add warnings for errors while parsing a SnowflakeConnectString

---

src/main/java/net/snowflake/client/core/SFBaseSession.java
src/main/java/net/snowflake/client/core/SFResultSetMetaData.java
src/main/java/net/snowflake/client/jdbc/SnowflakeDatabaseMetaData.java
src/test/java/net/snowflake/client/jdbc/DatabaseMetaDataLatestIT.java
src/test/java/net/snowflake/client/jdbc/ResultSetLatestIT.java

SNOW-685100 Add enable timestamp with timezone parameter. This change is a no op for JDBC client, because on client side we never want to disable the timestamp with timezone feature. We only want to disable the timestamp with timezone feature in stored proc JDBC on server side. server side test here: https://github.com/snowflakedb/snowflake/pull/76365 . Client side test should be covered by the tests added in this PR: https://github.com/snowflakedb/snowflake-jdbc/commit/15e0c18984b5820e4c6d85d361b7ac416857e3cb 
Fixes #NNNN 
3. Please describe how your code solves the …

SNOW-685100 Add enable timestamp with timezone parameter

---

src/main/java/net/snowflake/client/jdbc/SnowflakeConnectString.java
src/test/java/net/snowflake/client/jdbc/ConnectStringParseTest.java

JDBC Driver HTTP library does not allow URLs with underscores in them. This creates a problem for customers that have account names that have underscores in them. In order to resolve this problem we added ALLOW_UNDERSCORES_IN_HOST parameter that was suppose to trigger the change of all underscores to hyphens and all the hyphenated URLs were supported by Snowflake.
Only there is a bug in the driver that the parameter is not set by default leading to the conversion not happening till the said parameter is added to the connection properties. The expected behavior is that this conversion should happen by default. …

Set ALLOW_UNDERSCORES_IN_HOST to false by default

---

src/main/java/net/snowflake/client/jdbc/cloud/storage/SnowflakeGCSClient.java
src/test/java/net/snowflake/client/jdbc/SnowflakeDriverLatestIT.java

SNOW-683245: Bug fix in JDBC for GET command when GCS_USE_DOWNSCOPED_CREDENTIAL in GS is true
When code was added not to use presigned url and use GCS API to download the file, it was using GCS GUNZIP stuff. In pre-signed URL logic the driver download the file as is i.e. in GZIP format. So added same logic when use the GCS API to get file without decompression i.e. in RAW format of the file.  This optimize the data transfer on the wire.
Sent the new JDBC Jar to Timothy as he has setup already. He confirm the change works fine.
Fixes #NNNN 
3. Please describe how your …

Fix SNOW-683245 and format the file

---

pom.xml

Simba ticket 00410526.
Fixes #1193. Bouncy castle was upgrade to 1.70 which has become a multi-release JAR (#914). The files under META-INF/versions are shaded but they were not relocated due to the maven bug: https://issues.apache.org/jira/browse/MSHADE-406
This PR manually relocates the shaded bouncycastle files under "META-INF/versions" to "META-INF/versions/<version_number>/net/snowflake/client/jdbc/internal"
Fixes #1193.
This is causing problems for applications which have a dependency on both the Snowflake JDBC driver and a direct dependency on Bouncy Castle, as now those applications are including two …

Relocate bouncycastle files under META-INF/versions

---

src/main/java/net/snowflake/client/jdbc/SnowflakeDatabaseMetaData.java

- then catalog or schema are quoted
SNOW-XXXXX
Fixes #550
Hello! We use your excellent driver in DBeaver to connect to Snowflake and read some metadata. We found an issue with procedures columns reading for special cases. For catalogs or schemas with quoted names (lowercase as an example).
Then I used the catalog name in `getProcedureColumns` like "test" - I had an empty resultset even though my procedure had columns. It's because `getFirstResultSetCommand` set my catalog name in quotes, but …

#550 fix the special case for procedure parameters reading

---

src/main/java/net/snowflake/client/jdbc/SnowflakeDatabaseMetaData.java
src/test/java/net/snowflake/client/jdbc/DatabaseMetaDataInternalLatestIT.java

https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/84
'showCommand' variable for Database Metadata functions getTables and getColumns may cause a race condition.
Fixes #1207 
Use 'showCommand' for testing only. Each function should have it's own local command string i.e showTablesCommand/showColumnsCommand.

Fix race condition in SnowflakeDatabaseMetaData.java show command

---

src/test/java/net/snowflake/client/jdbc/DatabaseMetaDataInternalIT.java

SNOW-695007
This is a test-only change.
As part of enabling hybrid table information_schema views, they will be controlled by `ENABLE_KEY_VALUE_TABLE` instead of just a separate parameter.  Therefore, when we turn off `ENABLE_KEY_VALUE_TABLE` these views will no longer be visible to show commands or queries of `information_schema.tables`/`information_schema.views`.  `DatabaseMetaDataInternalIt:testGetTables` is failing in precommits for that change.
In `DatabaseMetaDataInternalIt:testGetTables`, we have disabled `ENABLE_KEY_VALUE_TABLE` because it changes the output format in show commands and was previously causing the test to fail.  However, since `getAllObjectCountInDBViaInforSchema` is running in a different session, it does not see that this param has been disabled and therefore …

SNOW-695007 Fix IT test in preparation for rollout of hybrid table infoschema views

---

src/main/java/net/snowflake/client/jdbc/RestRequest.java
src/test/java/net/snowflake/client/jdbc/ChunkDownloaderS3RetryUrlLatestIT.java
src/test/java/net/snowflake/client/jdbc/ConnectionIT.java
src/test/java/net/snowflake/client/jdbc/RestRequestTest.java

SNOW-618683
I have read the CLA Document and I hereby sign the CLA
If the driver issues a retry, the query parameter "retry" is now added. "Retry" contains the value of the HTTP status code from the server's previous response. If the response or the status code is null, then the value is set as "0" (as a string value). The parameter "retryCount" is already added.
Note that neither "retry" nor "retryCount" parameters will be included when:
1.) The driver is fetching using a AWS presigned URL because this causes a bug
2.) The driver is issuing a login request. I am not sure if there's any real reason not to include these query parameters for the login request so they could be added back in if needed.
Link to dummy PR (merge to master) so that precommit jobs run: …

SNOW-618683 Add previous status code as parameter "retry", update tests

---

src/main/java/net/snowflake/client/jdbc/SnowflakeDatabaseMetaData.java
src/test/java/net/snowflake/client/jdbc/DatabaseMetaDataInternalIT.java
src/test/java/net/snowflake/client/jdbc/DatabaseMetaDataInternalLatestIT.java
src/test/java/net/snowflake/client/jdbc/DatabaseMetaDataLatestIT.java

(https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/110)
getProcedureColumns() and getFunctionColumns() are returning procedureColumnOut/functionColumnOut for column_type when the stored procedure or function returns a resultset.
https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/110
Add support for stored procedures and functions that return a result set. Return procedureColumnResult for resultset columns in procedures and functionColumnResult for resultset …

Support resultset columns in getProcedureColumns() and getFunctionColumns()

---

src/main/java/net/snowflake/client/loader/StreamLoader.java

After enabling debugging for the JDBC driver to look into a problem, I noticed the following message being logged a lot, making it very difficult to go through the logs:
2022-02-01 14:17:03.931 n.s.c.loader.StreamLoader FINE resetOperation:709 - Reset Loader
This was logged 15,894,396 times in comparison to the following log message which was only logged 8 times:
2022-02-01 10:55:43.107 n.s.c.loader.StreamLoader FINE resetOperation:716 - Operation is changing from INSERT to MODIFY
The latter offers some kind of information, but I believe we can do without the first log message. 
SNOW-540328
GitHub Issue #694

[SNOW-540328] Excessive logging by StreamLoader

---

src/main/java/net/snowflake/client/jdbc/SnowflakeBaseResultSet.java
src/main/java/net/snowflake/client/jdbc/SnowflakePreparedStatementV1.java
src/test/java/net/snowflake/client/jdbc/ResultSetAsyncIT.java
src/test/java/net/snowflake/client/jdbc/ResultSetLatestIT.java

getClob() methods didn't account for null values resulting in a NullPointerException raised by StringBuffer. The methods will now return a null if the column holds a SQL NULL.
SNOW-749517
Fixes #1247 
We simply check if the value in a given column is null or not. If so, we return a Java null in order to avoid passing a null String to the StringBuffer's constructor. 
The JDK documentation for ResultSet didn't mention anything about how nulls should be treated: …

SNOW-749517: NullPointerException when trying to read a null Clob

---

src/main/java/net/snowflake/client/core/Constants.java
src/main/java/net/snowflake/client/jdbc/SnowflakeFileTransferAgent.java
src/main/java/net/snowflake/client/jdbc/cloud/storage/SnowflakeAzureClient.java
src/main/java/net/snowflake/client/jdbc/cloud/storage/SnowflakeGCSClient.java
src/main/java/net/snowflake/client/jdbc/cloud/storage/SnowflakeS3Client.java
src/test/java/net/snowflake/client/jdbc/SnowflakeDriverLatestIT.java
src/test/java/net/snowflake/client/jdbc/SnowflakeGcsClientHandleExceptionLatestIT.java

SNOW-741463
https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/180
When a GET is issued on a file which when downloaded, cannot fit the target filesystem, the driver retries with backoff 25 times causing a delay.
Fixes SNOW-741463
Catch and throw the exception instead of retrying when the error is "No space left on device"

Handle 'java.io.IOException: No space left on device' instead of retrying

---

src/main/java/net/snowflake/client/jdbc/SnowflakeDatabaseMetaData.java
src/test/java/net/snowflake/client/jdbc/DatabaseMetaDataLatestIT.java

SNOW-719164 Escape quotes for 'like' commands in DatabaseMetadata to protect against SqlInjections

---

src/main/java/net/snowflake/client/jdbc/SnowflakeUtil.java
src/test/java/net/snowflake/client/jdbc/ResultSetLatestIT.java

SNOW-753565
Fixes https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/222
If the server returns empty string for extTypeName, instead of resetting columnTypeName to an empty string keep the value from internalColTypeName node.
https://github.com/snowflakedb/snowflake-jdbc/blob/master/src/main/java/net/snowflake/client/jdbc/SnowflakeUtil.java#L151

Fix: driver returns empty column type name for stored procedure metadata when new statement type call is enabled

---

src/main/java/net/snowflake/client/jdbc/cloud/storage/SnowflakeAzureClient.java
src/test/java/net/snowflake/client/jdbc/StreamIT.java
src/test/java/net/snowflake/client/jdbc/StreamLatestIT.java

Azure client retries with backoff on 404 resource not found exception.
Fixes #NNNN 
Throw exception when the resource is not found instead of retying with a backoff.

Propagate error for 404 resource not found instead of retry for Azure client

---

src/test/java/net/snowflake/client/jdbc/FileUploaderLatestIT.java
src/test/java/net/snowflake/client/jdbc/StreamIT.java
src/test/java/net/snowflake/client/jdbc/StreamLatestIT.java

SNOW-748294
Fix failing StreamIT test by moving to LatestIT
Add GCS_DOWNSCOPING_CREDENTIAL=true for GCS stream download tests. Presigned URL is not set up for these tests. This param is false by default and must be set explicitly for jenkins testing (Note that Simba has this param set to true by default)
Fixes #NNNN 

SNOW-748294 Fix test failures

---

src/main/java/net/snowflake/client/jdbc/SnowflakeFileTransferAgent.java
src/test/java/net/snowflake/client/jdbc/FileUploaderExpandFileNamesTest.java
src/test/java/net/snowflake/client/jdbc/FileUploaderLatestIT.java
src/test/java/net/snowflake/client/jdbc/FileUploaderMimeTypeToCompressionTypeTest.java
src/test/java/net/snowflake/client/jdbc/FileUploaderSessionlessTest.java

Add tests for SnowflakeFileTransferAgent (part 1)

---

src/main/java/net/snowflake/client/core/SessionUtilExternalBrowser.java
src/main/java/net/snowflake/client/core/URLUtil.java
src/test/java/net/snowflake/client/core/URLUtilTest.java

SNOW-760534
Snowflake JDBC Driver does not validate SSO URL before executing it. Added a URLValidator utility to address that.
Also added URL Encoder to be used by OCSP Code to URL Encode the base64 encoded OCSP Request before sending it out on the wire. 
Fixes #NNNN 

SNOW-760534 Added URLValidator and URLEncoder

---

src/main/java/net/snowflake/client/core/SFBaseSession.java
src/test/java/net/snowflake/client/jdbc/CustomProxyLatestIT.java

SNOW-745310
The JDBC driver always defaults to HTTPS proxy protocol if:
- proxy params are not set in the connection url
- And both HTTPS and HTTP proxy parameters are set at the JVM level.
Fixes [#195
](https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/195)
Add http.proxyProtocol that allows users to specify which proxy protocol they want to use if both https and http proxies are set in the JVM. The default will be http to match the default for proxyProtocol set through connection …

Add http.proxyProtocol property for JVM proxy settings

---

src/main/java/net/snowflake/client/core/HttpUtil.java
src/test/java/net/snowflake/client/core/SessionUtilLatestIT.java

This is configured using the JVM argument -Dnet.snowflake.jdbc.ttl in order to ensure that idle connections were closed. The default now is to close those after 60 seconds if idle. The reasoning behind this change is that the load balancers across all the cloud providers have some idle timeout configuration so there's no reason for us to leave idle connections open indefinitely. This is referring to the Apache HttpClient's connection pool and is transparent to the user/developer.
SNOW-760642
Fixes #1294 

SNOW-760642 Change Default TTL From -1 to 60 seconds

---

src/main/java/net/snowflake/client/jdbc/SnowflakeStatementV1.java
src/test/java/net/snowflake/client/jdbc/StatementLatestIT.java

SNOW-755712
Fixes #1219 https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/234
Check resultset.isClosed() before adding the resultset to the set of openResultSets.

Fix memory leak by checking isClosed() before adding resultset to openResultSets

---

src/main/java/net/snowflake/client/jdbc/cloud/storage/SnowflakeGCSClient.java

SNOW-761784
Unintentionally committed a change to the gcs file upload error message where the entire stack trace is printed. This was just for debugging. Reverting to make it consistent with AWS and S3 (and fix failing gcs regression tests)
Fixes #NNNN 

SNOW-761784 fix gcs error message

---

src/main/java/net/snowflake/client/jdbc/SnowflakeDriver.java

SNOW-XXXXX
Fixes #1270  
By adding support for a system property `snowflake.jdbc.enable.reflective.access` we can enable users to opt out of suppressing the `IllegalAccessLogger`. We can do this by passing the argument:
```-Dsnowflake.jdbc.enable.reflective.access=true```.
Current users won't be affected by this change and default behaviour will remain as it is.

Config to disable Illegal Access Warning

---

src/test/java/net/snowflake/client/jdbc/ResultSetJsonVsArrowIT.java

SNOW-730981
Without implementing any support, JDBC should still be able to fetch such columns.
Fixes #NNNN 

SNOW-730981: added a test case for fetching columns of structured types

---

src/main/java/net/snowflake/client/jdbc/RestRequest.java

HTTP requests will now fail immediately after an SSLHandshakeException occurs and the error will be redirected to the standard error stream.
SNOW-759147
Fixes #NNNN 

SNOW-759147 Do Not Retry Requests That Fail With SSLHandshakeException

---

src/main/java/net/snowflake/client/jdbc/SnowflakeConnectString.java
src/test/java/net/snowflake/client/jdbc/SnowflakeDriverTest.java

SNOW-752232
Some of the logs in SnowflakeConnectString are warn level, which sometimes cause unnecessary concerns, e.g. `SnowflakeDriver.acceptsURL`. Change the log level to either debug or info to mitigate the issue.
Fixes #NNNN 

SNOW-752232: change warn level log to debug/info level in SnowflakeConnectString parse

---

src/main/java/net/snowflake/client/jdbc/SnowflakeDatabaseMetaData.java

SNOW-622919
In some rare cases, the resultSetStepTwo result set can be empty result set. This PR adds a check. However, I haven't figure out a reasonable way to add an exact test for the it (hard to repro empty result set).
Fixes #NNNN 

SNOW-622919: Check empty result set for get procedure columns

---

src/main/java/net/snowflake/client/jdbc/RestRequest.java

SNOW-755302
Fixes [#228](https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/228)
The message "SEVERE: HTTP request took longer than 5 min: 302 sec" in the driver logs is not show-stopper or critical. Customer requested changing it from SEVERE to WARNING.

Snow 755302 change non critical msg to warning

---

src/main/java/net/snowflake/client/core/SFTrustManager.java

SNOW-761217 URL Encode OCSP Requests

---

src/main/java/net/snowflake/client/jdbc/SnowflakeResultSetSerializableV1.java

SNOW-760517 
#715 added auth timeout of 10 seconds for JWT authentication. This is for login requests and doesn't need to be used on chunk downloader requests that don't use Snowflake JWT token.
Fixes https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/254
Set the auth timeout for chunk downloader requests back to default.

SNOW-760517 Fix auth timeout issue on chunk downloader requests

---

src/main/java/net/snowflake/client/core/SessionUtil.java

Improved error message related to SAML2 assertion failures due to a mismatch between the hostname the driver is trying to connect to and the hostname in the SAML response returned by the IdP. This error is very common for users that have underscore characters in the account name and upgrade to JDBC driver 3.13.25 where we set allowUnderscoresInHost to false by default.
SNOW-782480
Fixes #1341 
Before this change we just threw the following error to the standard error stream:
```
Exception in thread "main" …
```

SNOW-782480 Misleading SAML2 Assertion Error Message When Hostnames Mismatch

---

src/main/java/net/snowflake/client/jdbc/SnowflakeUtil.java

SNOW-785336
Fixes #1351 
By using the _try-with-resources_ pattern, the `PrintWriter` is automatically closed.

Moved PrintWriter to a try-with-resources block to avoid a resource leak

---

src/main/java/net/snowflake/client/jdbc/SnowflakePreparedStatementV1.java
src/test/java/net/snowflake/client/jdbc/PreparedStatement2LatestIT.java

SNOW-778564
https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/333
When the updated row count value returned in executeBatchInternal() is larger than max integer, the driver throws the exception: 
```
java.sql.BatchUpdateException: Value is too large to be stored as integer at batch index 0. Use executeLargeBatch() instead.
at net.snowflake.client.jdbc.SnowflakeStatementV1.executeBatchInternal(SnowflakeStatementV1.java:460)
at net.snowflake.client.jdbc.SnowflakePreparedStatementV1.executeBatchInternalWithArrayBind(SnowflakePreparedStatementV1.java:857)
at net.snowflake.client.jdbc.SnowflakePreparedStatementV1.executeLargeBatch(SnowflakePreparedStatementV1.java:796)
```
1. What GitHub …

SNOW-778564 Fix issue with executeLargeBatch() when updating is greater than max integer value

---

src/main/java/net/snowflake/client/core/QueryContextCache.java
src/test/java/net/snowflake/client/core/QueryContextCacheTest.java

Consider a simple situation : 
```
current state:
<id, priority, timestamp, context>
<1, 1, 1, None>
<2,2,2, None>
```
incoming changes:
```
merge <1, 2,1, None> 
call remove QCE(<1,1,1, None>) -> remove priorityMap(1, <1,1,1, None>)
call add QCE(<1,2,1, None>) -> add priorityMap(2, <1,2,1, None>) this map insertion will fail due to collision of priority key(there are two priority keys of 2)
merge <2,1,1, None>
```
Although this bug does not affect the contents in `treeSet` in this simple example (this is also why I thought I fixed the issue before, I only checked the final QCC entries embedded into the HTTP request, and found the previous multi-db missing query context issue was gone. However, the priorityMap contents are not correctly maintained), it can trigger inconsistent QCC …

Fix priority collision corner case for QCC client side

---

src/main/java/net/snowflake/client/jdbc/telemetryOOB/TelemetryService.java

When recording logging messages, the following string concatenation for messages is causing an issue:
`logger.debug("telemetry server request hit server cap on response: " + response);`
but the error disappears when the logging message is changed so that the additional string is put as an argument to the debug function instead, like so:
`logger.debug("telemetry server request hit server cap on response: {}", response);`
The odd part is that these logging messages have been the same for quite some time but the tests just started failing now. Fixing the ones I see for now, still trying to find the root cause of why the issue just now is popping up.
1. What GitHub issue is this PR addressing? Make sure that there is …

Debugging logger issue causing failing tests

---

src/main/java/net/snowflake/client/jdbc/DBMetadataResultSetMetadata.java
src/main/java/net/snowflake/client/jdbc/SnowflakeDatabaseMetaData.java

Reverts snowflakedb/snowflake-jdbc#1337 
Introduces regression as `SELECT DISTINCT` query always assumes that current db is set.

Revert "[SNOW-747966] Fetch metadata.getTableTypes() from the backend service"

---

src/main/java/net/snowflake/client/core/SFJsonResultSet.java
src/main/java/net/snowflake/client/core/arrow/BigIntToTimeConverter.java
src/main/java/net/snowflake/client/core/arrow/IntToTimeConverter.java
src/main/java/net/snowflake/client/jdbc/SnowflakeUtil.java
src/test/java/net/snowflake/client/jdbc/ResultSetLatestIT.java

SNOW-807489
https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/359
The java.sql.Time library uses UTC so when calling getTime().getHours() the result is skewed and not returned in the session timezone. 
Fixes #NNNN 
Use java.time.LocalTime for the conversion, that way we can get granular functions in the same timezone as getTime()

SNOW-807489: use LocalDateTime for getTime() when useSessionTimezone is enabled

---

src/main/java/net/snowflake/client/jdbc/ResultJsonParserV2.java

when calling the int position(int) API
Without the type-cast the compiler uses a newer Java API signature that returns a ByteBuffer object instead
Fixes the Java 8 runtime error of:
java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer
SNOW-XXXXX
Fixes #NNNN 

SNOW-828029 Force use of the Buffer API

---

src/test/java/net/snowflake/client/jdbc/SnowflakeDriverLatestIT.java

SNOW-835387
A change was made in GS code to use downscoped token for [get and put by default](https://github.com/snowflakedb/snowflake/pull/102264). This parameter needs to be set to false to use presigned URL. Note: for future reference, a get or put in JDBC should be expected to return a downscope token. Pre-signed URLS are only for large results.
Fixes #NNNN 

SNOW-835387 alter parameter to upload using presigned url

---

src/main/java/net/snowflake/client/log/JDK14Logger.java
src/test/java/net/snowflake/client/log/JDK14LoggerWithClientLatestIT.java

SNOW-835640: `MessageFormat.format` throws `IllegalArgumentException` if the message contains either `{` or `'`. This change will gracefully handle the `IllegalArgumentException`
Fixes #NNNN 

[SNOW-835640] Gracefully handle MessageFormat.format exceptions

---

src/main/java/net/snowflake/client/jdbc/telemetry/TelemetryClient.java
src/test/java/net/snowflake/client/jdbc/telemetry/TelemetryIT.java

SNOW-352846 requires a stateless telemetry service client with OAuth authentication.
This is a precedence task of SNOW-352846. 
Add an additional param in telemetry client to switch between key-pair JWT or OAuth.

SNOW-352846 OAuth authentication for sessionless telemetry client

---

src/main/java/net/snowflake/client/core/HttpUtil.java
src/main/java/net/snowflake/client/core/SFSession.java
src/main/java/net/snowflake/client/core/SFSessionProperty.java
src/main/java/net/snowflake/client/core/SFStatement.java
src/main/java/net/snowflake/client/core/StmtUtil.java
src/main/java/net/snowflake/client/jdbc/RestRequest.java
src/main/java/net/snowflake/client/jdbc/cloud/storage/SnowflakeGCSClient.java
src/test/java/net/snowflake/client/core/SFSessionPropertyTest.java
src/test/java/net/snowflake/client/jdbc/RestRequestTest.java

SNOW-811880 - Limits the retries to 7 when network timeout isn't defined for `/queries/v1/query-request `and `/queries/%s/result` endpoints.
Fixes #NNNN 

[SNOW-811880] Prevent Infinite retries!

---

src/main/java/net/snowflake/client/jdbc/SnowflakeConnectString.java
src/test/java/net/snowflake/client/jdbc/SnowflakeDriverTest.java

SNOW-823977
https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/381
Fixes #1388 
A NullPointerException is thrown from account.contains("_") if the account is nul:
` if (account.contains("_") && !allowUnderscoresInHost && host.startsWith(account)) {...}`
Check if account is still null after parsing connection string and parameters.

SNOW-823977: Fix NPE when calling driver.getPropertyInfo()

---

src/test/java/net/snowflake/client/jdbc/telemetry/TelemetryIT.java

SNOW-844604 Fix Failing Tests for JDBC in JDBC Connector and the Code Coverage. TelemetryIT test failed due to invalid privilege when setting up OAuth integration, switch session roles to fix it.
Fixes failing TelemetryIT
Upgrade the privilege to accountadmin before setting up oauth integration for telemetry test.

SNOW-844604 Fix Failing TelemetryIT for JDBC in JDBC-3 and the Code Coverage

---

src/main/java/net/snowflake/client/core/SFBaseStatement.java
src/main/java/net/snowflake/client/core/SFPreparedStatementMetaData.java
src/main/java/net/snowflake/client/core/SFStatement.java
src/main/java/net/snowflake/client/jdbc/SnowflakeParameterMetadata.java
src/main/java/net/snowflake/client/jdbc/SnowflakePreparedStatementV1.java
src/main/java/net/snowflake/client/jdbc/SnowflakeStatementV1.java
src/test/java/net/snowflake/client/jdbc/MockConnectionTest.java
src/test/java/net/snowflake/client/jdbc/PreparedStatement2LatestIT.java

SNOW-830719
After trying to fix metadata issue (https://github.com/snowflakedb/snowflake-jdbc/pull/1301/files), this led to a regression where using the same PreparedStatement object to call executeBatch() several times was no longer using array binding even when the threshold was met; instead, it was inserting the bind values in the payload.
The reason for this is that inside the execute() call when using array bind, there is an embedded call to the server to create a stage if needed. The resultset returned from creating the stage is what was being used to re-populate the metadata, and array binding is not supported for stage creation.
We do not need to continuously re-write over the metadata after every query execution anyway; in the original before the metadata fix, we were only …

SNOW-830719 Fix issue with consecutive batch array binding not working

---

src/main/java/net/snowflake/client/jdbc/SnowflakeDatabaseMetaData.java
src/test/java/net/snowflake/client/jdbc/DatabaseMetaDataIT.java
src/test/java/net/snowflake/client/jdbc/DatabaseMetaDataLatestIT.java

SNOW-844431
If an application makes a call to DatabaseMetadata describe function locatorsUpdateCopy(), a SnowflakeLoggedFeatureNotSupportedException is thrown and causes cascading failures.
Fixes #1416 
https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/475
Return false for this function instead of exception.

SNOW-844431: Return false for unsupported  locatorsUpdateCopy() function in SnowflakeDatabaseMetadata.java

---

src/main/java/net/snowflake/client/jdbc/SnowflakePreparedStatementV1.java
src/main/java/net/snowflake/client/jdbc/SnowflakeStatement.java
src/main/java/net/snowflake/client/jdbc/SnowflakeStatementV1.java

SNOW-849814
Follow up PR for https://github.com/snowflakedb/snowflake-jdbc/pull/1439 where we are unnecessarily creating `SFPreparedStatementMetaData` for simple Snowflake statement types. This PR introduces a new method in snowflakestatement.java which enables the sub-classes of SnowflakeStatementV1 to access the resultset constructed in execute* methods. 
Fixes #NNNN 

[SNOW-849814] Remove un-neccassary SFPreparedStatementMetaData object creation in SnowflakeStatement.java

---

config.json
src/main/java/net/snowflake/client/jdbc/SnowflakeConnectionV1.java
src/test/java/net/snowflake/client/jdbc/StreamLatestIT.java

SNOW-845270
https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/479
When a user tries to download a file whose filename contains Japanese or special characters or whitespace, a SQL Compilation Error will occur.
```
InputStream out = connection.unwrap(SnowflakeConnection.class).downloadStream(
"@TEST_STAGE",
"テストファイル.txt",
true);
```
This is because Snowflake requires such filename to be single-quoted.
`If the stage name or path includes spaces or special characters, it must be enclosed in single quotes (e.g. '@"my stage"' for a stage named "my stage").`
However, as the [current implementation](https://github.com/snowflakedb/snowflake-jdbc/blob/75f5e31a42ed3956fea373cd23cf8b621d27e1cd/src/main/java/net/snowflake/client/jdbc/SnowflakeConnectionV1.java#LL945C1-L965C65 …

SNOW-845270: DownloadStream() does not allow filenames that contains Japanese

---

ci/scripts/check_content.sh
pom.xml

SNOW-848855
https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/497
Arrow library has SLF4J implemented in its projects. Previously we used custom arrow jars where we replaced the SLF4J dependence with a NOOP logger implementation. Since #1382, we are no longer using the custom arrow jars and the scope was changed to provided which causes a ClassNotFoundException for SLF4J when trying to fetch with arrow format. 
We will need to add a notes to the docs that this change will try to configure SLF4J logger by default when using arrow and if users don't include a logging implementation it will print on the console:
```
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See …
```

SNOW-848855: Change SLF4J scope to compile

---

ci/scripts/check_content.sh
pom.xml

Reverts snowflakedb/snowflake-jdbc#1462
We need to make this change without including the following lines:
> SLF4J: No SLF4J providers were found.
! SLF4J: Defaulting to no-operation (NOP) logger implementation
! SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
! SLF4J: Class path contains SLF4J bindings targeting slf4j-api versions 1.7.x or earlier.
! SLF4J: Ignoring binding found at [jar:file:/mnt/jenkinsSF_REGRESS_ROOT/Client/henplus/lib/slf4j-jdk14-1.7.26.jar!/org/slf4j/impl/StaticLoggerBinder.class]
! SLF4J: See https://www.slf4j.org/codes.html#ignoredBindings for an explanation.

Revert "SNOW-848855: Change SLF4J scope to compile"

---

config.json
src/main/java/net/snowflake/client/core/SFSessionProperty.java
src/test/java/net/snowflake/client/log/JDK14LoggerWithClientLatestIT.java

SNOW-XXXXX
PR to rename `clientConfigFile` connection property name to `client_config_file` to make the connection property name consistent with rest of the sdk's.
Fixes #NNNN 

[Easy Logger Config] Rename connection property name

---

FIPS/pom.xml

SNOW-848763
aws-java-sdk-s3 in FIPS/pom.xml uses a vulnerable version of jackson-dataformat-cbor.
Fixes #1434 
https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/494
-    Upgrade awssdk to 1.12.501 in FIPS/pom.xml which uses jackson-dataformat-cbor 2.12.6.

SNOW-848763 upgrade awssdk to 1.12.501

---

ci/scripts/check_content.sh
pom.xml

SNOW-859796
This must be merged after https://github.com/snowflakedb/snowflake/pull/112537 so as to avoid BPTP failures.
Fixes #NNNN 

SNOW-859796 Get rid of SFL4J logging messages

---

src/main/java/net/snowflake/client/core/SFSession.java
src/test/java/net/snowflake/client/jdbc/telemetryOOB/TelemetryServiceIT.java

SNOW-844477
Out-of-band telemetry is enabled by default in the driver until a session is opened and the session properties are read. If CLIENT_OUT_OF_BAND_TELEMETRY_ENABLED is disabled on the account level and returned in the session properties, the telemetry will then be disabled. But since it is enabled before connection, if there are OCSP exceptions they will send telemetry requests. 
https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/478
To allow …

SNOW-844477: Allow connection property CLIENT_OUT_OF_BAND_TELEMETRY_ENABLED to disable OOB telemetry

---

src/main/java/net/snowflake/client/jdbc/cloud/storage/StorageClientFactory.java
src/test/java/net/snowflake/client/jdbc/cloud/storage/SnowflakeS3ClientLatestIT.java

SNOW-837400
The jdbc driver should only use proxy settings that are specified in connection properties or JVM properties. 
During the setup of the S3 client in SnowflakeS3Client.java, the aws-java-sdk-core library will try to resolve the client configuration including the proxy host, port, user and password settings. It will try to read proxy settings in the following order:
1. If provided, returns the value set on the ClientConfiguration object i.e clientConfig.setProxyHost("value")
2. If not provided, checks the java system properties i.e http.proxyHost
3. If neither above two are provided, checks the environment variables HTTP_PROXY/HTTPS_PROXY
The value will be used in all requests to the external stage. There is no option to disable the proxy in the aws library.
Please answer these …

SNOW-837400: Fix S3 client builder reading proxy environment variables

---

ci/scripts/check_content.sh
pom.xml

SNOW-859796
Even though this change looks simple - this introduces a behavior change on how developers are going to use snowflake-jdbc package and sl4j logging library.
This change makes the `Sl4J-api` as a compile-time dependency and removes the SL4J-API from the snowflake-jdbc jar. However, when the user uses any build tools such as maven, gradle etc., sl4j-api will be shown as depedency for snowflake jar as below:
> Note log: Excluding org.slf4j:slf4j-api: jar:2.0.6 from the shaded jar.
```
[INFO] org.example:test-sdk:jar:1.0-SNAPSHOT
[INFO] \- net.snowflake:snowflake-jdbc:jar:3.13.45-SNAPSHOT:compile
[INFO]    \- org.slf4j:slf4j-api:jar:2.0.6:compile
[INFO] ------------------------------------------------------------------------
```
Building the Java application will download the …

[SNOW-859796] Get rid of SFL4J logging messages

---

src/main/java/net/snowflake/client/config/SFClientConfigParser.java

SNOW-836396
When the driver tries to load the path of the jar directory as part of the easy logging configuration process, sometimes the path can have a prefix on Windows. This was partially fixed in #1390 but a customer faced another issue where the path had file:\ prefix:
```
Caused by: java.nio.file.InvalidPathException: Illegal char <:> at index 4: file:\C:\dev\<snip>\build\libs\<snip>-application.jar!\BOOT-INF\lib\snowflake-jdbc-3.13.31.jar!\sf_client_config.json
at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182) ~[?:?]
at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153) ~[?:?]
at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77) ~[?:?]
at sun.nio.fs.WindowsPath.parse(WindowsPath.java:92) ~[?:?]
at …
```

SNOW-836396: InvalidPathException loading client config file on Windows

---

src/main/java/net/snowflake/client/core/SFSessionProperty.java
src/main/java/net/snowflake/client/jdbc/cloud/storage/SnowflakeAzureClient.java
src/main/java/net/snowflake/client/jdbc/cloud/storage/SnowflakeGCSClient.java
src/main/java/net/snowflake/client/jdbc/cloud/storage/SnowflakeS3Client.java
src/test/java/net/snowflake/client/core/SFSessionPropertyTest.java
src/test/java/net/snowflake/client/jdbc/SnowflakeS3ClientHandleExceptionLatestIT.java
src/test/java/net/snowflake/client/jdbc/cloud/storage/SnowflakeS3ClientLatestIT.java

SNOW-854356
https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/512
The driver retries on 400 Bad Request error codes. The S3 client can return this error response if the token is expired and the driver will retry using the same request with sleep and backoff. This will continuously fail until the max retry of 25 is reached. 
1. Check the error response and renew the token on 400 Bad Request. 
2. Add a connection property to configure the max retries for PUT/GET exceptions for storage clients.
Reproduced the exception using a sleep of 1.5 hours in the code to test the fix.
Fixes #NNNN …

SNOW-854356: Renew S3 token on 400 Bad Request and add putGetMaxRetries property

---

src/main/java/net/snowflake/client/core/SFBaseStatement.java
src/main/java/net/snowflake/client/jdbc/SnowflakeResultSetSerializableV1.java
src/test/java/net/snowflake/client/jdbc/SnowflakeDriverLatestIT.java

SNOW-880860 Cache statement parameter values for HTAP change

---

src/main/java/net/snowflake/client/core/SFTrustManager.java
src/test/java/net/snowflake/client/jdbc/SnowflakeDriverLatestIT.java

SNOW-872558
Fixes [#559](https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/559)
Add the path and port, if exist, to the OCSP retry URL instead of taking just the host.

SNOW-872558: add path to private link OCSP retry url

---

src/test/java/net/snowflake/client/jdbc/SnowflakeDriverLatestIT.java

SNOW-780605 - before, if test failed on any assertions, account parameter would not be unset. Also, resources would not be closed.

SNOW-780605: Better handle resource closing in testHTAPOptimizations

---

src/test/java/net/snowflake/client/jdbc/SnowflakeDriverIT.java

Tests with old driver was failing with this error message: "net.snowflake.client.jdbc.SnowflakeSQLException: Your client app version, JDBC 3.9.2, is using a deprecated pre-signed URL for PUT. Please upgrade to a version that supports GCP downscoped token. See https://community.snowflake.com/s/article/faq-2023-client-driver-deprecation-for-GCP-customers." This happens because server side change. After talking to Timothy, he suggest to add session parameter to go back to previous behavior in the test: alter session set ENABLE_GCP_PUT_EXCEPTION_FOR_OLD_DRIVERS = false; 
This change is server is intended for GCP downscope token changes and early adoption of the new driver.
1. What GitHub issue is this PR addressing? …

Change the session parameter to run tests as is before with old driver

---

src/main/java/net/snowflake/client/jdbc/SnowflakeFileTransferAgent.java
src/test/java/net/snowflake/client/jdbc/FileUploaderPrepIT.java
src/test/java/net/snowflake/client/jdbc/FileUploaderSessionlessTest.java

SNOW-913746
Currently, uploadWithoutConnection creates a Storage Client and uses StageInfo object. For Snowpipe Streaming, we need to enable useS3RegionalURL which doesn't use session instance. `getStageInfo` is the used by uploadWithoutConnection from JsonNode and doesn't check for useS3RegionalURL which will be passed from Server Side in client/configure API. Please keep an eye on Server side PR where I make changes in the response from `ConfigureClientResponse`

SNOW-913746 Honor useS3RegionalUrl from JsonNode in getStageInfo

---

src/main/java/net/snowflake/client/core/SFBaseSession.java
src/main/java/net/snowflake/client/core/SFSession.java
src/main/java/net/snowflake/client/core/SFSessionProperty.java
src/main/java/net/snowflake/client/core/SFStatement.java
src/main/java/net/snowflake/client/core/SessionUtil.java
src/test/java/net/snowflake/client/jdbc/SnowflakeDriverLatestIT.java

SNOW-887071 : Added connection property to disable PUT/GET command

---

src/test/java/net/snowflake/client/jdbc/ConnectionIT.java

SNOW-933005 Fix Wrong Error Code Issues in testProdConnectivity and testInsecureMode
The error code of wrong account name was changed from 390100 (incorrect username and password) to 390400 (bad request). This PR fixes all related tests.
Fixes #NNNN 

 SNOW-933005 Fix Wrong Error Code Issues in testProdConnectivity and testInsecureMode

---

src/main/java/net/snowflake/client/jdbc/SnowflakeFileTransferAgent.java

SNOW-928802
While debugging, I saw this error message but there is no stack trace so makes it hard to debug. 
Fixes #NNNN 

SNOW-928802 Fix logger error where the message/stack trace is not printed

---

src/main/java/net/snowflake/client/jdbc/telemetry/TelemetryClient.java
src/test/java/net/snowflake/client/jdbc/telemetry/TelemetryIT.java

SNOW-931105
Issue 698: https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/698
Fixes #1524
Add an additional overload of the createSessionlessTelemetry method with 2 parameters and by default, it uses "KEYPAIR_JWT" as the auth type. This fix helps the snowflake-ingest-sdk to work correctly with the latest version of the driver.

SNOW-931105: Add createSessionlessTelemetry(CloseableHttpClient, String) method

---

src/main/java/net/snowflake/client/core/arrow/VarCharConverter.java
src/test/java/net/snowflake/client/core/arrow/VarCharConverterTest.java

SNOW-898376 Issues on handling NULLs to Date Datatype conversion
Fixes https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/623
When trying to retrieve a Date type result using the syntax "Select NULL as Date_Colum from Table", the NULL was being interpreted as a varchar by the converters. I've added some logic for how to convert this type of NULL to a null date in the VarCharConverter.

Fix issue with using Null as DateType

---

src/main/java/net/snowflake/client/core/SFLoginInput.java
src/main/java/net/snowflake/client/core/SFSession.java
src/main/java/net/snowflake/client/core/SFSessionProperty.java
src/main/java/net/snowflake/client/core/SessionUtil.java
src/main/java/net/snowflake/client/core/SessionUtilExternalBrowser.java
src/main/java/net/snowflake/client/jdbc/RestRequest.java
src/main/java/net/snowflake/client/util/DecorrelatedJitterBackoff.java
src/test/java/net/snowflake/client/core/SessionUtilTest.java
src/test/java/net/snowflake/client/jdbc/ConnectionLatestIT.java
src/test/java/net/snowflake/client/jdbc/RestRequestTest.java

SNOW-878076: Retry Strategy for JDBC
Fixes https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/577
Implementing new retry strategy for login related endpoints.

SNOW-878076: Retry Strategy for JDBC

---

src/main/java/net/snowflake/client/jdbc/DefaultSFConnectionHandler.java

SNOW-969200
Change the default LogPath to home directory if not specified in the config file. Previously it was default to temp directory.
Fixes #NNNN 

SNOW-969200: Default logpath to home directory instead of temp directory

---

.github/workflows/build-test.yml
FIPS/pom.xml
ci/_init.sh
ci/build.sh
ci/image/.gitignore
ci/image/Dockerfile.jdbc-centos7-openjdk-test
ci/image/build.sh
ci/image/update.sh
ci/test.sh
pom.xml
src/test/java/net/snowflake/client/core/SessionUtilLatestIT.java
src/test/java/net/snowflake/client/core/StmtUtilTest.java
src/test/java/net/snowflake/client/jdbc/ConnectionWithOCSPModeIT.java

SNOW-937197 SNOW-837198
1. Provided new image for Java 8 - based on new centos version
2. Provided images for Java 11 and 17
3. Updated dependencies to work on Java 8, 11 and 17

Snow 937198 use new images

---

src/main/java/net/snowflake/client/jdbc/SnowflakeUtil.java
src/test/java/net/snowflake/client/core/CoreUtilsMiscellaneousTest.java

SNOW-968787
[#752](https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/752)
Fixes [#752](https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/752)
Null check was missing in convertProxyPropertiesToHttpClientKey() when the property key "gzipDisabled" is not specified, resulting in NullPointerException.

SNOW-968787: Fix NullPointerException when property key "gzipDisabled" is not specified

---

src/test/java/net/snowflake/client/pooling/LogicalConnectionLatestIT.java

SNOW-977206 Fix testPreparedStatement
When `use database` was called, the schema was switched to public. When the same test was run on multiple parallel builds, they possibly use the same table in the same time.
Also fixed resource management in this test class.

SNOW-977206 Fix testPreparedStatement

---

src/main/java/net/snowflake/client/core/SFChildResult.java
src/main/java/net/snowflake/client/core/SFStatement.java
src/main/java/net/snowflake/client/jdbc/SFAsyncResultSet.java

SNOW-957349
Fixes #NNNN 
As part of changes we made for enabling async child job in JVM stored procs, we needed to access some classes/APIs from the public library that are not public. Hence we had to create util methods in `net/snowflake/client` package (see this PR [...braries/jdbc-stored-proc/src/main/java/net/snowflake/client/core/StoredProcCoreUtils.java](https://github.com/snowflakedb/snowflake/pull/114773/files#diff-bb0f0d7b309b4b22ebeef522d0c556a4592aa80c198354099ee37ebd8551dae5)). This is a follow up …

SNOW-957349: Make some API/classes needed in stored procs public

---

src/main/java/net/snowflake/client/core/SFLoginInput.java
src/main/java/net/snowflake/client/core/SFSession.java
src/main/java/net/snowflake/client/core/SFSessionProperty.java
src/main/java/net/snowflake/client/core/SessionUtil.java
src/main/java/net/snowflake/client/core/SessionUtilExternalBrowser.java
src/test/java/net/snowflake/client/core/SessionUtilExternalBrowserTest.java
src/test/java/net/snowflake/client/jdbc/SSOConnectionTest.java

SNOW-877275 : Build the console login url

---

src/main/java/net/snowflake/client/core/SFBaseSession.java
src/main/java/net/snowflake/client/core/SFSession.java
src/main/java/net/snowflake/client/core/SFStatement.java
src/main/java/net/snowflake/client/jdbc/QueryStatusV2.java
src/main/java/net/snowflake/client/jdbc/SFAsyncResultSet.java
src/main/java/net/snowflake/client/jdbc/SnowflakeResultSet.java
src/main/java/net/snowflake/client/jdbc/SnowflakeResultSetV1.java
src/test/java/net/snowflake/client/jdbc/ConnectionLatestIT.java
src/test/java/net/snowflake/client/jdbc/MockConnectionTest.java

SNOW-980046 Implemented new query status type, which is not based on singleton.

SNOW-980046 Implement queryStatusV2

---

src/main/java/net/snowflake/client/jdbc/SnowflakeFileTransferAgent.java
src/main/java/net/snowflake/client/jdbc/SnowflakeSQLException.java
src/main/java/net/snowflake/client/jdbc/SnowflakeSQLLoggedException.java
src/main/java/net/snowflake/client/jdbc/cloud/storage/QueryIdHelper.java
src/main/java/net/snowflake/client/jdbc/cloud/storage/SnowflakeAzureClient.java
src/main/java/net/snowflake/client/jdbc/cloud/storage/SnowflakeGCSClient.java
src/main/java/net/snowflake/client/jdbc/cloud/storage/SnowflakeS3Client.java
src/main/java/net/snowflake/client/jdbc/cloud/storage/SnowflakeStorageClient.java
src/test/java/net/snowflake/client/jdbc/ConnectionLatestIT.java
src/test/java/net/snowflake/client/jdbc/FileUploaderExpandFileNamesTest.java
src/test/java/net/snowflake/client/jdbc/SnowflakeAzureClientHandleExceptionLatestIT.java
src/test/java/net/snowflake/client/jdbc/SnowflakeDriverLatestIT.java
src/test/java/net/snowflake/client/jdbc/SnowflakeGcsClientHandleExceptionLatestIT.java
src/test/java/net/snowflake/client/jdbc/SnowflakeS3ClientHandleExceptionLatestIT.java
src/test/java/net/snowflake/client/jdbc/StatementLatestIT.java
src/test/java/net/snowflake/client/jdbc/cloud/storage/SnowflakeS3ClientLatestIT.java

SNOW-909180: Pass query id in exceptions from file agent
- Added new methods with query id passed as parameters
- Deprecating methods without query id paramter

SNOW-909180: Pass query id in exceptions from file agent

---

src/test/java/net/snowflake/client/jdbc/DatabaseMetaDataLatestIT.java

SNOW-999847: Fix flaky test DatabaseMetaDataLatestIT-testUnderscoreInSchemaNamePatternForPrimaryAndForeignKeys

---

src/test/java/net/snowflake/client/TestUtil.java
src/test/java/net/snowflake/client/ThrowingConsumer.java
src/test/java/net/snowflake/client/ThrowingRunnable.java
src/test/java/net/snowflake/client/jdbc/DatabaseMetaDataLatestIT.java

SNOW-1001928: Fix flaky test DatabaseMetaDataLatestIT.testHandlingSpecialChars

---

src/main/java/net/snowflake/client/jdbc/SnowflakePreparedStatementV1.java
src/test/java/net/snowflake/client/jdbc/PreparedStatement2LatestIT.java

Invoking the PreparedStatement's toString() method will now return the actual SQL query and
query ID if available rahter than the object's hashCode. This is helpful when using features
in frameworks like Spring Boot to monitor and log information about slow running queries.
SNOW-1003959
Fixes #1601 

SNOW-1003959: Implement toString() in SnowflakePreparedStatementV1

---

src/main/java/net/snowflake/client/jdbc/telemetryOOB/TelemetryService.java

SNOW-997216 When using upload without connection the OOB telemetry is not initialized properly - server deployment is not set. Now we set it to PROD by default.

SNOW-997216 Init serverDeployment to default value

---

src/main/java/net/snowflake/client/jdbc/cloud/storage/SnowflakeGCSClient.java

SNOW-999358 Handle GCP downscoped tokens with same logic as for presigned URLs.

SNOW-999358 Handle GCP token expiration correctly when using connectionless mode

---

src/main/java/net/snowflake/client/core/HttpUtil.java
src/main/java/net/snowflake/client/jdbc/DefaultResultStreamProvider.java

[SNOW-965966] Move http client creation to HttpUtil class from DefaultResultStreamProvider
[Fixes ](https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/750)
Moved the http client creation out of DefaultResultStreamProvider
[SNOW-965966]: https://snowflakecomputing.atlassian.net/browse/SNOW-965966?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SNOW-965966: Remove unnecessary TODOs from DefaultResultStreamProvider

---

src/main/java/net/snowflake/client/core/ObjectMapperFactory.java

SNOW-1003775: Mark object mapper factory constant property name as internal

---

src/main/java/net/snowflake/client/jdbc/SnowflakeDatabaseMetaData.java
src/test/java/net/snowflake/client/jdbc/DatabaseMetaDataIT.java
src/test/java/net/snowflake/client/jdbc/DatabaseMetaDataLatestIT.java

SNOW-995481
Fixes https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/808
This updates the JDBC version reported by the driver metadata to 4.2 to reflect the currently supported API version.

Updated JDBC version to 4.2

---

src/test/java/net/snowflake/client/jdbc/DatabaseMetaDataLatestIT.java

SNOW-1050447: Cleanup schemas in testGetProcedureColumnsWildcards

---

.github/pull_request_template.md
README.rst
pom.xml
src/main/java/net/snowflake/client/config/SFClientConfig.java
src/main/java/net/snowflake/client/core/ExecTimeTelemetryData.java
src/main/java/net/snowflake/client/core/QueryContextCache.java
src/main/java/net/snowflake/client/core/ResultUtil.java
src/main/java/net/snowflake/client/core/SFSession.java
src/main/java/net/snowflake/client/core/SessionUtil.java
src/main/java/net/snowflake/client/core/UUIDUtils.java
src/main/java/net/snowflake/client/jdbc/SnowflakePreparedStatementV1.java
src/main/java/net/snowflake/client/jdbc/cloud/storage/SnowflakeAzureClient.java
src/main/java/net/snowflake/client/jdbc/cloud/storage/SnowflakeGCSClient.java
src/main/java/net/snowflake/client/jdbc/cloud/storage/SnowflakeS3Client.java
src/test/java/net/snowflake/client/jdbc/DatabaseMetaDataInternalLatestIT.java
src/test/java/net/snowflake/client/jdbc/HeartbeatIT.java
src/test/java/net/snowflake/client/jdbc/ResultSetLatestIT.java
src/test/java/net/snowflake/client/jdbc/SnowflakeDriverIT.java

SNOW-1063844: Force braces for condition and loop bodies

---

src/test/java/net/snowflake/client/TestUtil.java

SNOW-1063992: Exclude JDBC perf test schemas from DatabaseMetaDataIT.testGetSchemas

---

src/main/java/net/snowflake/client/core/SFBaseSession.java

Fix for Github issue 629 (SNOW-902727)

---

parent-pom.xml
src/main/java/net/snowflake/client/core/SFBaseSession.java
src/main/java/net/snowflake/client/core/SFSession.java
src/main/java/net/snowflake/client/core/SFSessionProperty.java
src/main/java/net/snowflake/client/jdbc/SnowflakeUtil.java
src/main/java/net/snowflake/client/jdbc/cloud/storage/SnowflakeGCSClient.java
src/main/java/net/snowflake/client/jdbc/cloud/storage/StorageClientFactory.java
src/test/java/net/snowflake/client/jdbc/ConnectionLatestIT.java
src/test/java/net/snowflake/client/jdbc/SnowflakeDriverLatestIT.java
thin_public_pom.xml

SNOW-1196041: Ignore default credentials in GCS client

---

src/main/java/net/snowflake/client/core/SFBaseSession.java
src/main/java/net/snowflake/client/core/SFSession.java
src/main/java/net/snowflake/client/core/SFSessionProperty.java
src/main/java/net/snowflake/client/core/arrow/AbstractArrowVectorConverter.java
src/main/java/net/snowflake/client/core/arrow/BigIntToFixedConverter.java
src/main/java/net/snowflake/client/core/arrow/IntToFixedConverter.java
src/main/java/net/snowflake/client/core/arrow/SmallIntToFixedConverter.java
src/main/java/net/snowflake/client/core/arrow/TinyIntToFixedConverter.java
src/test/java/net/snowflake/client/jdbc/ResultSetArrowLatestIT.java
src/test/java/net/snowflake/client/jdbc/ResultSetLatestIT.java

SNOW-1170182
[   Fixes #NNNN ](https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/889)
Added new connection property jdbc_arrow_treat_decimal_as_int to allow for resultSet.getObject for certain numeric types to report the object class more consistently.

SNOW-1170182: Return decimal as int in ARROW results configured by flag

---

src/main/java/net/snowflake/client/core/arrow/AbstractArrowVectorConverter.java
src/main/java/net/snowflake/client/core/arrow/BigIntToFixedConverter.java
src/main/java/net/snowflake/client/core/arrow/IntToFixedConverter.java
src/main/java/net/snowflake/client/core/arrow/SmallIntToFixedConverter.java
src/main/java/net/snowflake/client/core/arrow/TinyIntToFixedConverter.java

SNOW-1170182: Simplify condition returning decimal in ARROW

---

src/main/java/net/snowflake/client/core/SFArrowResultSet.java
src/main/java/net/snowflake/client/core/SFBaseResultSet.java
src/main/java/net/snowflake/client/core/SFJsonResultSet.java
src/main/java/net/snowflake/client/core/structs/StructureTypeHelper.java
src/main/java/net/snowflake/client/jdbc/SnowflakeType.java
src/main/java/net/snowflake/client/jdbc/SnowflakeUtil.java
src/test/java/net/snowflake/client/jdbc/ResultSetStructuredTypesLatestIT.java
src/test/java/net/snowflake/client/jdbc/SnowflakeDriverLatestIT.java

SNOW-1234378
Before structured types are fully implemented, we hide new functionalities behind a flag. This flag should be taken into account when deciding about column type for structs.

SNOW-1234378 Return correct column type for structs depending on the run flag

---

src/main/java/net/snowflake/client/core/ArrowSqlInput.java
src/main/java/net/snowflake/client/core/JsonSqlInput.java
src/main/java/net/snowflake/client/core/SFBaseResultSet.java
src/main/java/net/snowflake/client/jdbc/SnowflakeBaseResultSet.java
src/main/java/net/snowflake/client/jdbc/SnowflakeUtil.java
src/test/java/net/snowflake/client/AbstractDriverIT.java
src/test/java/net/snowflake/client/jdbc/ResultSetStructuredTypesLatestIT.java

SNOW-1232333 - add mapping for basic types form arrays and maps

---

src/main/java/net/snowflake/client/jdbc/SnowflakeResultSetSerializableV1.java

SNOW-1270256
This change fixes ConcurrentModificationException when one thread updates parameters (line 603, right below the changed line) and another iterates over the session parameters. The code itself is not supposed to update the session parameters in the first place, so it must make a copy (the fix) instead of referencing the session's parameters map directly.

SNOW-1270256 - Concurrency bug around ResultSet and Session parameters

---

src/main/java/net/snowflake/client/core/SFArrowResultSet.java
src/main/java/net/snowflake/client/core/SFBaseResultSet.java
src/main/java/net/snowflake/client/core/SFJsonResultSet.java
src/main/java/net/snowflake/client/core/SFResultSetMetaData.java
src/main/java/net/snowflake/client/jdbc/FieldMetadata.java
src/main/java/net/snowflake/client/jdbc/SnowflakeBaseResultSet.java
src/main/java/net/snowflake/client/jdbc/SnowflakeResultSetMetaData.java
src/main/java/net/snowflake/client/jdbc/SnowflakeResultSetMetaDataV1.java
src/test/java/net/snowflake/client/jdbc/structuredtypes/ResultSetStructuredTypesLatestIT.java

SNOW-1313555 - make fields metadata visible for customers

---

src/test/java/net/snowflake/client/jdbc/PutFileWithSpaceIncludedIT.java
src/test/java/net/snowflake/client/jdbc/PutUnescapeBackslashIT.java
src/test/java/net/snowflake/client/jdbc/ResultSet0IT.java
src/test/java/net/snowflake/client/jdbc/ResultSetAlreadyClosedIT.java
src/test/java/net/snowflake/client/jdbc/ResultSetArrowForce0MultiTimeZone.java
src/test/java/net/snowflake/client/jdbc/ResultSetArrowForceLTZMultiTimeZoneIT.java
src/test/java/net/snowflake/client/jdbc/ResultSetArrowForceTZMultiTimeZoneIT.java
src/test/java/net/snowflake/client/jdbc/ResultSetAsyncIT.java
src/test/java/net/snowflake/client/jdbc/ResultSetAsyncLatestIT.java
src/test/java/net/snowflake/client/jdbc/ResultSetFeatureNotSupportedIT.java
src/test/java/net/snowflake/client/jdbc/ResultSetIT.java
src/test/java/net/snowflake/client/jdbc/ResultSetJsonVsArrowIT.java
src/test/java/net/snowflake/client/jdbc/ResultSetJsonVsArrowMultiTZIT.java
src/test/java/net/snowflake/client/jdbc/ResultSetLatestIT.java
src/test/java/net/snowflake/client/jdbc/ResultSetMultiTimeZoneIT.java
src/test/java/net/snowflake/client/jdbc/ResultSetMultiTimeZoneLatestIT.java

SNOW-1213117: Wrap connection, statement and result set in try with resources(3/4)

---

src/main/java/net/snowflake/client/core/ArrowSqlInput.java
src/main/java/net/snowflake/client/core/JsonSqlInput.java
src/main/java/net/snowflake/client/core/SFArrowResultSet.java
src/main/java/net/snowflake/client/core/SFBaseResultSet.java
src/main/java/net/snowflake/client/core/SFJsonResultSet.java
src/main/java/net/snowflake/client/core/SFSqlInput.java
src/main/java/net/snowflake/client/jdbc/SnowflakeBaseResultSet.java
src/main/java/net/snowflake/client/jdbc/SnowflakeResultSetV1.java
src/test/java/net/snowflake/client/jdbc/BindingAndInsertingStructuredTypesLatestIT.java
src/test/java/net/snowflake/client/jdbc/PreparedStatementFeatureNotSupportedIT.java
src/test/java/net/snowflake/client/jdbc/structuredtypes/ResultSetStructuredTypesLatestIT.java

[SNOW-1232333](https://snowflakecomputing.atlassian.net/browse/SNOW-1232333)
Fixes #NNNN 
[SNOW-1232333]: https://snowflakecomputing.atlassian.net/browse/SNOW-1232333?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Structured types backward compatibility for getObject method

---

src/test/java/net/snowflake/client/core/SessionUtilTest.java
src/test/java/net/snowflake/client/jdbc/CustomProxyLatestIT.java
src/test/java/net/snowflake/client/jdbc/FileUploaderExpandFileNamesTest.java
src/test/java/net/snowflake/client/jdbc/SnowflakeDriverConnectionStressTest.java
src/test/java/net/snowflake/client/jdbc/SnowflakeDriverIT.java
src/test/java/net/snowflake/client/jdbc/SnowflakeDriverLatestIT.java
src/test/java/net/snowflake/client/jdbc/StatementLatestIT.java
src/test/java/net/snowflake/client/pooling/LogicalConnectionLatestIT.java

SNOW-1356389: Use junit assertions instead of jvm assert in tests

---

src/main/java/net/snowflake/client/core/SFLoginInput.java
src/main/java/net/snowflake/client/core/SFSession.java
src/main/java/net/snowflake/client/core/SFSessionProperty.java
src/main/java/net/snowflake/client/core/SessionUtil.java
src/test/java/net/snowflake/client/core/SessionUtilLatestIT.java

SNOW-1226600: Add parameter to disable SAML URL check

---

src/main/java/net/snowflake/client/jdbc/cloud/storage/SnowflakeS3Client.java
src/test/java/net/snowflake/client/jdbc/cloud/storage/SnowflakeS3ClientTest.java

SNOW-1446336: Use S3 regional url domain base on region name

---

src/test/java/net/snowflake/client/core/SFTrustManagerIT.java
src/test/java/net/snowflake/client/jdbc/RestRequestTest.java

SNOW-1446174: Allow 513 in SFTrustManager tests

---

src/main/java/net/snowflake/client/core/SFLoginInput.java
src/test/java/net/snowflake/client/core/SFLoginInputTest.java

SNOW-1460355: Fix getHostFromServerUrl

---

src/main/java/net/snowflake/client/core/arrow/ArrowResultUtil.java
src/main/java/net/snowflake/client/core/arrow/BigIntToTimestampLTZConverter.java
src/main/java/net/snowflake/client/core/arrow/StructuredTypeDateTimeConverter.java
src/test/java/net/snowflake/client/jdbc/ConnectionLatestIT.java

SNOW-1465374: Return consistent timestamps_ltz between JSON and ARROW result sets

---

src/main/java/net/snowflake/client/jdbc/SnowflakeFileTransferAgent.java
src/test/java/net/snowflake/client/jdbc/FileUploaderExpandFileNamesTest.java

SNOW-1369651: Do not fail file pattern expanding on file not found in different pattern

---

src/main/java/net/snowflake/client/jdbc/RestRequest.java
src/test/java/net/snowflake/client/jdbc/RestRequestTest.java

SNOW-1503887: Limit retry backoff to always be in range

---

src/main/java/net/snowflake/client/jdbc/SnowflakeUtil.java
src/test/java/net/snowflake/client/jdbc/DatabaseMetaDataResultSetLatestIT.java
src/test/java/net/snowflake/client/jdbc/SnowflakeUtilTest.java

SNOW-1479614: Fix conversion of OBJECT column nested fields metadata
Fixes #NNNN 

SNOW-1479614: Fix conversion of OBJECT column nested fields metadata

---

src/main/java/net/snowflake/client/core/SFArrowResultSet.java
src/main/java/net/snowflake/client/core/SFException.java
src/main/java/net/snowflake/client/core/SFFixedViewResultSet.java
src/main/java/net/snowflake/client/core/SFResultSet.java
src/main/java/net/snowflake/client/core/SFResultSetMetaData.java
src/main/java/net/snowflake/client/core/SFSession.java
src/main/java/net/snowflake/client/jdbc/SnowflakeResultSetSerializableV1.java
src/main/java/net/snowflake/client/jdbc/SnowflakeSQLException.java
src/main/java/net/snowflake/client/jdbc/SnowflakeSQLLoggedException.java

SNOW-1016468: Set last query id for all failed statements updated

---

src/main/java/net/snowflake/client/config/SFConnectionConfigParser.java
src/test/java/net/snowflake/client/config/SFConnectionConfigParserTest.java

SNOW-1454054: Add check of user permission for token file

---

src/main/java/net/snowflake/client/jdbc/SnowflakeColumnMetadata.java
src/main/java/net/snowflake/client/jdbc/SnowflakeDatabaseMetaData.java
src/main/java/net/snowflake/client/jdbc/SnowflakeResultSetSerializableV1.java
src/main/java/net/snowflake/client/jdbc/SnowflakeRichResultSetSerializableV1.java
src/main/java/net/snowflake/client/jdbc/SnowflakeUtil.java
src/test/java/net/snowflake/client/AbstractDriverIT.java
src/test/java/net/snowflake/client/jdbc/SnowflakeSerializableTest.java

SNOW-1016363 Add rich results metadata support for Coldbrew/Snowsight integration

---

CHANGELOG.rst
FIPS/pom.xml
parent-pom.xml
pom.xml
src/main/java/net/snowflake/client/jdbc/SnowflakeDriver.java

Bump version to 3.18.0 for release

---

src/test/java/net/snowflake/client/jdbc/SnowflakeDriverIT.java

SNOW-1618131: Remove error_on_generic_pruner integration test

---

src/main/java/net/snowflake/client/jdbc/SnowflakeFileTransferAgent.java

Fixes issue where the absence of the slf4j-api library from the classpath results in a NoClassDefFoundError/ClassNotFoundException because the class org.slf4j.LoggerFactory can't be loaded

SNOW-1614292: java.lang.ClassNotFoundException: org.slf4j.LoggerFactor

---

Jenkinsfile
src/test/java/net/snowflake/client/core/arrow/BaseConverterTest.java

SNOW-1668681: Run JDBC unit tests on AIX

---

src/main/java/net/snowflake/client/core/ResultUtil.java
src/main/java/net/snowflake/client/core/arrow/BitToBooleanConverter.java
src/main/java/net/snowflake/client/core/arrow/tostringhelpers/ArrowStringRepresentationBuilderBase.java
src/test/java/net/snowflake/client/core/arrow/BitToBooleanConverterTest.java
src/test/java/net/snowflake/client/core/json/StringConverterTest.java
src/test/java/net/snowflake/client/jdbc/ResultSetJsonVsArrowIT.java
src/test/java/net/snowflake/client/jdbc/ResultSetLatestIT.java
src/test/java/net/snowflake/client/jdbc/structuredtypes/StructuredTypesGetStringArrowJsonCompatibilityIT.java

Revert turning native arrow boolean primitives lowercase (changed in [PR#1882](https://github.com/snowflakedb/snowflake-jdbc/pull/1882)) to prevent introducing a breaking change. 
Structured types' booleans string representation will remain lowercase to preserve JSON-compatibility
SNOW-1374896
[SNOW-1700248](https://snowflakecomputing.atlassian.net/browse/SNOW-1700248)
I reverted the global boolean case change and implemented a structured type string builder one. Primitive booleans will remain UPPERCASED while booleans within structured types will be lowercased to provide JSON compatibility
[SNOW-1700248]: https://snowflakecomputing.atlassian.net/browse/SNOW-1700248?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJw …

SNOW-1700248 Revert turning native arrow boolean primitives lowercase

---

FIPS/pom.xml

SNOW-1528939 - Updated the 3rd party maven proxy reference from nexus to artifactory
As part of the security initiative, the artifactory team will be deprecating the 3rd party artifact proxy in Nexus. All the 3rd party artifacts will be called from artifactory.
Issue: #NNNN

SNOW-1528939 - Updated 3rd party maven proxy reference from nexus to artifactory

---

src/main/java/net/snowflake/client/core/CancellationReason.java
src/main/java/net/snowflake/client/core/SFBaseStatement.java
src/main/java/net/snowflake/client/core/SFStatement.java
src/main/java/net/snowflake/client/core/StmtUtil.java
src/main/java/net/snowflake/client/jdbc/SnowflakeStatementV1.java

SNOW-1732777: Log cancel query reason

---

src/test/java/net/snowflake/client/jdbc/SnowflakeDriverLatestIT.java

SNOW-1616480: Remove gcs presigned url test since it is not supported

---

src/main/java/net/snowflake/client/jdbc/SnowflakeFileTransferAgent.java
src/test/java/net/snowflake/client/jdbc/ConnectionLatestIT.java
src/test/java/net/snowflake/client/jdbc/GitRepositoryDownloadLatestIT.java
src/test/java/net/snowflake/client/jdbc/StreamLatestIT.java

SNOW-1708304: Download stream from git repository

---

src/test/java/net/snowflake/client/jdbc/ConnectionLatestIT.java
src/test/java/net/snowflake/client/jdbc/ConnectionWithOCSPModeIT.java

SNOW-799391: Ignore badssl timeouts in tests

---

src/main/java/net/snowflake/client/jdbc/SnowflakeFileTransferAgent.java

SNOW-1786156: Replace raw asserts with exceptions

---

src/main/java/net/snowflake/client/jdbc/cloud/storage/GcmEncryptionProvider.java

SNOW-1786192 Use 12 bytes as IV length for GCM

SNOW-1786192 Use 12 bytes as IV length for GCM

---

src/main/java/net/snowflake/client/jdbc/SnowflakePreparedStatementV1.java

SNOW-1799642: Add array bind supported log for prepared statements

---

src/main/java/net/snowflake/client/jdbc/SnowflakeFileTransferAgent.java
src/main/java/net/snowflake/client/jdbc/cloud/storage/SnowflakeGCSClient.java
src/main/java/net/snowflake/client/jdbc/cloud/storage/StageInfo.java
src/main/java/net/snowflake/client/jdbc/cloud/storage/StorageClientFactory.java
src/test/java/net/snowflake/client/jdbc/FileUploaderPrep.java
src/test/java/net/snowflake/client/jdbc/FileUploaderSessionlessTest.java
src/test/java/net/snowflake/client/jdbc/cloud/storage/StageInfoGcsCustomEndpointTest.java
src/test/resources/FileUploaderPrep/exampleAzure.json
src/test/resources/FileUploaderPrep/exampleGCS.json
src/test/resources/FileUploaderPrep/exampleGCSWithEndpoint.json
src/test/resources/FileUploaderPrep/exampleGCSWithUseRegionalUrl.json
src/test/resources/FileUploaderPrep/exampleS3.json
src/test/resources/FileUploaderPrep/exampleS3WithStageEndpoint.json

SNOW-1789749: Support regional GCS endpoints

---

src/test/java/net/snowflake/client/jdbc/ConnectionLatestIT.java

SNOW-1787626: Fix flaky test ConnectionLatestIT.testAsyncQueryOpenAndCloseConnection

---

.github/workflows/build-test.yml
.github/workflows/check-style.yml
.github/workflows/jira_close.yml
.github/workflows/jira_issue.yml
.github/workflows/snyk-issue.yml
.github/workflows/snyk-pr.yml

SNOW-1825712: Update GH actions versions

---

FIPS/pom.xml
parent-pom.xml
pom.xml

SNOW-1747516
Issue: #1926 
Native libraries used by conscrypt and grpc/netty are not relocated to a different name although their counterpart java classes are. This may cause a conflict with applications using the same dependencies but possibly different versions up to a JVM crash.
Modify maven-shade-plugin relocation configuration to rename the libraries using snowflake shade base:
* relocate grpc/netty tcnative and epoll libraries (note that Netty java loader detects relocation automatically as long as the base is the same for the java classes and the native library (minus dot '.' …

SNOW-1747516: Fix native libraries relocation

---

src/main/java/net/snowflake/client/config/SFConnectionConfigParser.java
src/main/java/net/snowflake/client/core/SFSessionProperty.java
src/main/java/net/snowflake/client/jdbc/SnowflakeUtil.java
src/test/java/net/snowflake/client/config/SFConnectionConfigParserTest.java

SNOW-1689931 Adding flag to skip token file permission verification

---

README.rst

SNOW-1548083: Remove experimental label from thin driver

---

src/main/java/net/snowflake/client/core/SFSession.java
src/main/java/net/snowflake/client/core/SFSessionProperty.java
src/main/java/net/snowflake/client/log/JDK14Logger.java
src/main/java/net/snowflake/client/log/StdOutConsoleHandler.java
src/test/java/net/snowflake/client/log/JDK14LoggerConsoleHandlerOverrideLatestIT.java

SNOW-1652680: Add option to override j.u.l.ConsoleHandler to write to stdout

---

src/main/java/net/snowflake/client/config/SFClientConfigParser.java
src/main/java/net/snowflake/client/core/CredentialManager.java
src/main/java/net/snowflake/client/core/FileCacheManager.java
src/main/java/net/snowflake/client/core/FileUtil.java
src/main/java/net/snowflake/client/core/IncidentUtil.java
src/main/java/net/snowflake/client/core/SFBaseSession.java
src/main/java/net/snowflake/client/core/SFSession.java
src/main/java/net/snowflake/client/core/SFStatement.java
src/main/java/net/snowflake/client/core/SecureStorageAppleManager.java
src/main/java/net/snowflake/client/core/SecureStorageLinuxManager.java
src/main/java/net/snowflake/client/core/SecureStorageWindowsManager.java
src/main/java/net/snowflake/client/core/SystemUtil.java
src/main/java/net/snowflake/client/jdbc/DefaultSFConnectionHandler.java
src/main/java/net/snowflake/client/jdbc/FileBackedOutputStream.java
src/main/java/net/snowflake/client/jdbc/SnowflakeCallableStatementV1.java
src/main/java/net/snowflake/client/jdbc/SnowflakeChunkDownloader.java
src/main/java/net/snowflake/client/jdbc/SnowflakeConnectString.java
src/main/java/net/snowflake/client/jdbc/SnowflakeConnectionV1.java
src/main/java/net/snowflake/client/jdbc/SnowflakeUtil.java
src/main/java/net/snowflake/client/jdbc/cloud/storage/SnowflakeAzureClient.java
src/main/java/net/snowflake/client/jdbc/cloud/storage/SnowflakeGCSClient.java
src/main/java/net/snowflake/client/jdbc/cloud/storage/SnowflakeS3Client.java

SNOW-1652680: Limit logging on std out and info level

---

src/main/java/net/snowflake/client/core/SFSession.java
src/main/java/net/snowflake/client/core/SFSessionProperty.java
src/main/java/net/snowflake/client/jdbc/DefaultSFConnectionHandler.java
src/main/java/net/snowflake/client/log/JDK14Logger.java
src/main/java/net/snowflake/client/log/StdErrOutThresholdAwareConsoleHandler.java
src/main/java/net/snowflake/client/log/UnknownJavaUtilLoggingLevelException.java
src/test/java/net/snowflake/client/log/JDK14LoggerConsoleHandlerOverrideLatestIT.java

SNOW-1652680: Add threshold for j.u.l. stderr stdout logging

---

.github/workflows/parameters_aws_auth_tests.json.gpg
Jenkinsfile
ci/container/test_authentication.sh
ci/test_authentication.sh
parent-pom.xml
pom.xml
src/test/java/net/snowflake/client/authentication/AuthConnectionParameters.java
src/test/java/net/snowflake/client/authentication/AuthTest.java
src/test/java/net/snowflake/client/authentication/ExternalBrowserIT.java
src/test/java/net/snowflake/client/authentication/IdTokenIT.java
src/test/java/net/snowflake/client/category/TestTags.java
src/test/java/net/snowflake/client/suites/AuthenticationTestSuite.java
src/test/java/net/snowflake/client/suites/UnitTestSuite.java

SNOW-1346234
I'm not sure if `src/test/java/net/snowflake/client/jdbc/ConnectionManual.java` should be deleted after adding those tests as it operates on account parameters i.e.: `alter account testaccount set ALLOW_ID_TOKEN=false` , so it may still be valid to keep it.
Issue: #NNNN

SNOW-1346234 add automated external browser tests

---

src/main/java/net/snowflake/client/jdbc/cloud/storage/EncryptionProvider.java
src/main/java/net/snowflake/client/jdbc/cloud/storage/GcmEncryptionProvider.java

SNOW-1850888 Initializes secure random in a more robust way.

SNOW-1850888 Fix secure random initialization

---

src/main/java/net/snowflake/client/core/SFArrowResultSet.java
src/main/java/net/snowflake/client/core/SFBaseResultSet.java
src/main/java/net/snowflake/client/core/SFJsonResultSet.java
src/main/java/net/snowflake/client/core/arrow/ArrayConverter.java
src/main/java/net/snowflake/client/core/arrow/MapConverter.java
src/main/java/net/snowflake/client/core/arrow/StructConverter.java
src/main/java/net/snowflake/client/core/arrow/VectorTypeConverter.java
src/main/java/net/snowflake/client/jdbc/SnowflakeBaseResultSet.java
src/main/java/net/snowflake/client/jdbc/SnowflakeResultSetV1.java
src/test/java/net/snowflake/client/jdbc/structuredtypes/ResultSetStructuredTypesLatestIT.java

SNOW-1848734: Fix for structured types as strings performance problems

---

Jenkinsfile

SNOW-1852300 use bptp-built tag for svn_revision

---

src/main/java/net/snowflake/client/jdbc/SnowflakeConnectionV1.java
src/test/java/net/snowflake/client/jdbc/BindingAndInsertingStructuredTypesLatestIT.java
src/test/java/net/snowflake/client/jdbc/SnowflakeConnectionV1Test.java

[SNOW-1844765](https://snowflakecomputing.atlassian.net/browse/SNOW-1844765)
As noticed in #1982 - apache spark may turn the type name lowerCase. This behaviour is incompatible with the current createArrayOf implementation in SnowflakeConnectionV1 since it infers the JDBCType from the exact string type name. 
- This change adds `toUpperCase` call to `JDBCType.valueOf` invocation to allow passing lower/random case strings as type names. 
- Adds unit tests to emphasise that this is a desired behaviour
[SNOW-1844765]: https://snowflakecomputing.atlassian.net/browse/SNOW-1844765?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SNOW-1844765 Make createArrayOf case-insensitive

---

README.rst
prepareNewVersion.sh

SNOW-1853396: Prepare new version script

---

parent-pom.xml

SNOW-1804062: Explicitly exclude old netty-common from transitive dependencies

---

.gitignore
src/main/java/net/snowflake/client/log/CommonsLoggingWrapper.java
src/main/java/net/snowflake/client/log/CommonsLoggingWrapperMode.java
src/main/java/net/snowflake/client/log/JCLWrapper.java
src/main/java/net/snowflake/client/log/SFLoggerUtil.java
src/test/java/net/snowflake/client/log/CommonsLoggingWrapperModeTest.java

SNOW-1229142: Improve commons logging wrapping

---

src/test/java/net/snowflake/client/jdbc/DatabaseMetaDataIT.java

SNOW-1898856: Make test getMaxBinaryLiteralLength and getMaxCharLiteralLength more robust

---

src/main/java/net/snowflake/client/core/SFSession.java
src/main/java/net/snowflake/client/jdbc/SnowflakeSQLLoggedException.java

SNOW-1880134: Improve exception message when getting query metadata

---

src/main/java/net/snowflake/client/jdbc/SnowflakeBasicDataSource.java
src/test/java/net/snowflake/client/jdbc/SnowflakeBasicDataSourceTest.java

SNOW-1903631
Issue: #2055
Simply check the parameter (username and password) before putting them into the ConcurrentHashMap so we get a clearer error message instead of a NullPointerException.

SNOW-1903631 Add more explicit error message when username or password is missing id DataSource

---

TestOnly/pom.xml
parent-pom.xml
thin_public_pom.xml

SNOW-1926811: Update netty version to 4.1.118.Final

---

src/main/java/net/snowflake/client/jdbc/SnowflakeUtil.java
src/test/java/net/snowflake/client/jdbc/SnowflakeUtilTest.java

SNOW-1660409: Fix directory permission for GET

---

src/main/java/net/snowflake/client/util/SecretDetector.java
src/test/java/net/snowflake/client/util/SecretDetectorTest.java

Add secret detector extension for OAuth

---

src/test/java/net/snowflake/client/jdbc/HeartbeatAsyncLatestIT.java
src/test/java/net/snowflake/client/jdbc/HeartbeatIT.java

SNOW-1935764: Explicitly pick account for heartbeat tests on jenkins

---

src/main/java/net/snowflake/client/core/SFBaseStatement.java
src/main/java/net/snowflake/client/core/SFStatement.java
src/main/java/net/snowflake/client/jdbc/SnowflakeStatementV1.java
src/test/java/net/snowflake/client/annotations/DontRunOnJenkins.java
src/test/java/net/snowflake/client/jdbc/StatementLatestIT.java

SNOW-1901399: Let query timeout be server side or client side, not both

---

src/main/java/net/snowflake/client/jdbc/SnowflakeFileTransferAgent.java
src/main/java/net/snowflake/client/jdbc/SnowflakeUtil.java
src/main/java/net/snowflake/client/jdbc/cloud/storage/SnowflakeAzureClient.java
src/main/java/net/snowflake/client/jdbc/cloud/storage/SnowflakeGCSClient.java
src/main/java/net/snowflake/client/jdbc/cloud/storage/SnowflakeS3Client.java
src/test/java/net/snowflake/client/jdbc/SnowflakeUtilTest.java

[SNOW-1949064](https://snowflakecomputing.atlassian.net/browse/SNOW-1949064).
This PR reverts changes introduced in [PR#2066](https://github.com/snowflakedb/snowflake-jdbc/pull/2066) and [PR#2080](https://github.com/snowflakedb/snowflake-jdbc/pull/2080) that changed the permissions of files downloaded with GET from 644 to 600.
This is a change in behaviour and should be released in the next major release, not the upcoming one hence the revert.
[SNOW-1949064]: https://snowflakecomputing.atlassian.net/browse/SNOW-1949064?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SNOW-1949064 Revert owner-only permissions enforcement for files downloaded with GET

---

src/main/java/net/snowflake/client/core/SFBaseSession.java
src/main/java/net/snowflake/client/jdbc/cloud/storage/SnowflakeGCSClient.java

SNOW-1405682 - disable the use of GCS default credentials as a default
We decided to set the value of `disableGcsDefaultCredentials` to `true` according to information that the current default configuration is wrong and generates a lot of customer frustration. When the customer uses the GCS global credential provider it is impossible to connect to the GCS storage driver because of incorrect credentials.
Issue: #NNNN

SNOW-1405682 - disable use of GCS default credentials as a default

---

src/main/java/net/snowflake/client/core/QueryExecDTO.java
src/main/java/net/snowflake/client/core/SFBaseStatement.java
src/main/java/net/snowflake/client/core/SFStatement.java
src/main/java/net/snowflake/client/core/StmtUtil.java
src/main/java/net/snowflake/client/jdbc/SnowflakeStatementV1.java
src/test/java/net/snowflake/client/jdbc/DataframeAstTest.java
src/test/java/net/snowflake/client/jdbc/MockConnectionTest.java

SNOW-1947501: Create AST API in JDBC

---

src/test/java/net/snowflake/client/jdbc/ConnectionIT.java
src/test/java/net/snowflake/client/jdbc/ConnectionLatestIT.java

SNOW-1957486 - fixed the assertion for the test of verifying connection with ssl disabled parameter.
Issue: #NNNN

SNOW-1957486 fix test

---

src/test/java/net/snowflake/client/jdbc/DatabaseMetaDataInternalLatestIT.java
src/test/java/net/snowflake/client/jdbc/DatabaseMetaDataLatestIT.java
src/test/java/net/snowflake/client/jdbc/LobSizeLatestIT.java

SNOW-1960848 - fix tests after MaxLobSize changes
Issue: #NNNN

SNOW-1960848 - fix tests after MaxLobSize changes

---

src/main/java/net/snowflake/client/core/FileCacheManager.java
src/main/java/net/snowflake/client/core/FileUtil.java
src/test/java/net/snowflake/client/core/FileCacheManagerTest.java

SNOW-1958601
- [] New public API is not unnecessary exposed (run `mvn verify` and inspect `target/japicmp/japicmp.html`)
Issue: #NNNN

SNOW-1958601: Fix NPE when cache folder is inaccessible

---

src/main/java/net/snowflake/client/jdbc/SnowflakeFileTransferAgent.java

Addresses point B of [APPS-53008](https://snowflakecomputing.atlassian.net/browse/APPS-53008)
* B. deep test SnowflakeTransferAgent functionality
* we cannot easily mock the StorageClient which is static final initialized on the class
* modifying the final qualifier is not safe and was deemed impractical, see [PR](https://github.com/snowflakedb/snapps/pull/68290), [discarded test](https://github.com/snowflakedb/snapps/blob/jc/cb_sf_proxy_deep_tests/src/coldbrew/file-io-utils/src/test/java/net/snowflake/client/core/SnowflakeFileTransferAgentTest.java#L297-L299) due to unsafe reflection
Issue: #NNNN
3. Please describe how your code solves the …

SNOW-0000: [APPS-53008] SnowflakeFileTransferAgent avoid query history clutter and enable test mocks 

---

src/test/java/net/snowflake/client/jdbc/ConnectionIT.java
src/test/java/net/snowflake/client/jdbc/ConnectionLatestIT.java
src/test/java/net/snowflake/client/jdbc/ConnectionWithDisableOCSPModeLatestIT.java

SNOW-2021007
Disable prod tests that fail due to changes in backend error responses, those tests will be changed in next quarter to be independent of backend.

SNOW-2021007: disable prod tests

---

src/main/java/net/snowflake/client/core/auth/wif/AzureIdentityAttestationCreator.java
src/test/java/net/snowflake/client/core/auth/wif/AzureIdentityAttestationCreatorLatestIT.java
src/test/resources/wiremock/mappings/wif/azure/successful_flow_azure_functions_v2_issuer.json
src/test/resources/wiremock/mappings/wif/azure/successful_flow_v2_issuer.json

SNOW-1902245 Accept both v1 and v2 formats of Entra ID issuers
Issue: #NNNN

SNOW-1902245: Accept v1 and v2 Entra ID issuers

---

src/main/java/net/snowflake/client/core/SFOauthLoginInput.java
src/main/java/net/snowflake/client/core/SFSession.java
src/main/java/net/snowflake/client/core/SFSessionProperty.java
src/main/java/net/snowflake/client/core/auth/oauth/OAuthAuthorizationCodeAccessTokenProvider.java
src/test/java/net/snowflake/client/core/OAuthAuthorizationCodeFlowLatestIT.java
src/test/resources/wiremock/mappings/oauth/authorization_code/successful_flow_with_single_use_refresh_tokens.json

SNOW-1955810
A Snowflake OAuth client can optionally include `enable_single_use_refresh_tokens=true` in the request body of the authorization code flow to opt-in to single-use refresh token semantics. This is part of a new security feature in Snowflake's native OAuth implementation.
To enable this, a user can set the `oauthEnableSingleUseRefreshTokens` session property.

SNOW-1955810 Support client-side opt-in of Refresh Token Rotation in Snowflake OAuth

---

src/main/java/net/snowflake/client/core/SessionUtil.java
src/test/java/net/snowflake/client/jdbc/DatabaseMetaDataLatestIT.java

SNOW-2021533 Move OCSP setup earlier in session initialization
Issue: #NNNN

SNOW-2021533 Move OCSP setup earlier in session initialization

---

src/test/java/net/snowflake/client/AbstractDriverIT.java
src/test/java/net/snowflake/client/jdbc/ConnectionIT.java
src/test/java/net/snowflake/client/jdbc/ConnectionLatestIT.java
src/test/java/net/snowflake/client/jdbc/ConnectionWithDisableOCSPModeLatestIT.java
src/test/java/net/snowflake/client/jdbc/ProxyLatestIT.java

SNOW-2021007
- redundant tests removed
- tests that verify disableOCSPChecks and insecureMode changed to verify successful connection - I don't see any reason for providing wrong credentials and verifying GS errors
- connectAndVerifySimpleQuery moved so it can be reused
Issue: #NNNN

SNOW-2021007 refactor OCSP tests

---

src/test/java/net/snowflake/client/jdbc/MultiStatementIT.java

Removing redundant tests for funcionallities tested on lower test levels
Issue: #NNNN

SNOW-2021007 remove redundant multistatement tests

---

src/test/java/net/snowflake/client/AbstractDriverIT.java
src/test/java/net/snowflake/client/jdbc/ConnectionIT.java
src/test/java/net/snowflake/client/jdbc/ConnectionLatestIT.java
src/test/java/net/snowflake/client/jdbc/FileUploaderExpandFileNamesTest.java
src/test/java/net/snowflake/client/jdbc/PreparedMultiStmtIT.java
src/test/java/net/snowflake/client/jdbc/PreparedStatement2LatestIT.java
src/test/java/net/snowflake/client/jdbc/ResultSetIT.java
src/test/java/net/snowflake/client/jdbc/ResultSetLatestIT.java
src/test/java/net/snowflake/client/jdbc/SnowflakeDriverIT.java
src/test/java/net/snowflake/client/jdbc/StatementIT.java
src/test/java/net/snowflake/client/jdbc/cloud/storage/SnowflakeAzureClientLatestIT.java
src/test/java/net/snowflake/client/pooling/ConnectionPoolingDataSourceIT.java

SNOW-2021007
- use error code from ErrorCode whenever possible, to make it clear it's jdbc driver error code
- remove GS error code details in cases when it's not relevant to the test case
- minor fixes
Issue: #NNNN

SNOW-2021007 refactor error codes usage in tests 

---

.github/workflows/build-test.yml
CHANGELOG.rst
FIPS/pom.xml
Jenkinsfile
parent-pom.xml
pom.xml
src/main/java/net/snowflake/client/core/SFTrustManager.java
src/main/java/net/snowflake/client/jdbc/SnowflakeDriver.java

SNOW-2133570 Fix trust manager algorithm name and bump to new version 3.20.1
Issue: #NNNN

SNOW-2133570 Fix trust manager algorithm name and bump to new version 3.20.1

---

.github/workflows/build-test.yml
CHANGELOG.rst
FIPS/pom.xml
Jenkinsfile
parent-pom.xml
pom.xml
src/main/java/net/snowflake/client/core/SFTrustManager.java
src/main/java/net/snowflake/client/jdbc/SnowflakeDriver.java

SNOW-2133570 Fix trust manager algorithm name and bump to new version 3.18.1
Issue: #NNNN

SNOW-2133570 Fix trust manager algorithm name and bump to new version 3.18.1

---

src/main/java/net/snowflake/client/core/SessionUtil.java
src/test/java/net/snowflake/client/core/OAuthLegacyFlowLatestIT.java
src/test/resources/wiremock/mappings/oauth/legacy_oauth/token_expired.json

SNOW-2172062: Fix access token expiration handling for legacy OAuth flow

---

pom.xml

SNOW-2183215
Issue: #NNNN
As described [here](https://central.sonatype.org/publish/publish-portal-ossrh-staging-api/#deploying) the way of publishing artefacts in Maven Central Repository required updated endpoint in the Maven publishing plugin configuration, this PR updates that

SNOW-2183215: Migrate to new Maven Central publishing API

---

parent-pom.xml

SNOW-2183215
Issue: #NNNN
This PR bumps the version of the `maven-gpg-plugin` to the latest version

SNOW-2183215: Bump maven-gpg-plugin version to latest

---

src/test/java/net/snowflake/client/jdbc/SnowflakeDriverLatestIT.java

SNOW-2154772 remove temporary fix for `testHTAPStatementParameterCaching` introduced in https://github.com/snowflakedb/snowflake-jdbc/pull/2243
Issue: #NNNN

SNOW-2154772 remove temporary fix for testHTAPStatementParameterCaching

---

src/main/java/net/snowflake/client/core/SFBaseSession.java
src/main/java/net/snowflake/client/core/SFSession.java
src/main/java/net/snowflake/client/core/SFSessionProperty.java
src/main/java/net/snowflake/client/jdbc/SnowflakeDatabaseMetaData.java
src/test/java/net/snowflake/client/jdbc/DatabaseMetaDataLatestIT.java

SNOW-1894342
Allows to disable treating SQL wildcards characters (`_` and `%`) as patterns in identifier names which allows for narrower metadata searches. 
When `true` (default)
```java
DatabaseMetaData.getColumns("MY_DB", "MY_SCHEMA", "MY_TABLE", null)
```
is translated to
```sql
show columns in database "MY_DB";
```
When `false`
```java
DatabaseMetaData.getColumns("MY_DB", "MY_SCHEMA", "MY_TABLE", null)
```
is translated to
```sql
show columns in table "MY_DB"."MY_SCHEMA"."MY_TABLE";
```
Issue: #NNNN
Please write a short description of how your code change solves the related …

SNOW-1894342: Add flag for using patterns in metadata SHOW ... IN ... commands

---

src/test/java/net/snowflake/client/jdbc/DatabaseMetaDataLatestIT.java

The failing test was `DatabaseMetaDataIT#testGetSchemas` this test is suppose to ignore all schemas generated in tests which are prefixed with `GENERATED_` since we replaced the underscore here it was not ignored thus failing when both of these tests were running simultaneously which happens sometimes on Github actions where we run 140+ actions on same environment.
Issue: #NNNN

SNOW-1894342 Fix flaky test

---

src/main/java/net/snowflake/client/jdbc/cloud/storage/S3HttpUtil.java

We explicitly set BASIC as the authentication method for Proxy connections made by the S3 client when a proxy user and password are provided. Previously, the AWS S3 client could potentially attempt to connect using other methods if those were provided by the Proxy server in the Proxy-Authenticate headers

SNOW-2249717: Force Proxy Basic Auth in S3 Client

---

src/main/java/net/snowflake/client/jdbc/SnowflakeDriver.java
src/test/java/net/snowflake/client/jdbc/SnowflakeDriverTest.java

This is for https://github.com/snowflakedb/snowflake-jdbc/issues/2295. The auto detection of the `default` connection from `connections.toml` implemented in https://github.com/snowflakedb/snowflake-jdbc/pull/1780, tested using the driver and it works just fine.
Relevant documentation piece: https://docs.snowflake.com/en/developer-guide/jdbc/jdbc-configure#connecting-using-the-connections-toml-file 
However apparently when used from HikariCP, the exact same setup leads to:
```
[main] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
java.lang.RuntimeException: Failed to get driver instance for jdbcUrl=jdbc:snowflake:auto
at com.zaxxer.hikari.util.DriverDataSource.<init>(DriverDataSource.java:120)
at com.zaxxer.hikari.pool.PoolBase.initializeDataSource(PoolBase.java:336) …
```

SNOW-2258880 add autoconfig to acceptsURL + add a test for it
